# Generated by Django 5.2.17 on 2026-09-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20)),
                ('depart', models.CharField(max_length=150)),
                ('depart_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('arrivee', models.CharField(max_length=150)),
                ('debut', models.DateTimeField()),
                ('fin_prevue', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en-cours', 'En cours'), ('termine', 'Termine')], default='en-cours', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='drivers.chauffeur')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=150)),
                ('heure', models.CharField(max_length=5)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='dispatch.trajet')),
            ],
            options={
                'ordering': ['heure'],
            },
        ),
    ]
