# Generated by Django 5.2.17 on 2026-09-25 02:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0002_vehicule_suivi_et_releves"),
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanEntretien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vidange", "Vidange et filtres"),
                            ("pneus", "Pneus"),
                            ("freins", "Freins"),
                            ("inspection", "Inspection mecanique"),
                            ("courroie", "Courroie de distribution"),
                            ("climatisation", "Climatisation"),
                            ("carrosserie", "Carrosserie"),
                            ("electrique", "Systeme electrique"),
                            ("reparation", "Reparation mecanique"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(max_length=150)),
                (
                    "intervalle_km",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "intervalle_jours",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("dernier_km", models.PositiveIntegerField(default=0)),
                ("derniere_date", models.DateField()),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_entretien",
                        to="fleet.vehicule",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicule__plaque", "type", "id"],
            },
        ),
        migrations.CreateModel(
            name="BonTravail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("preventif", "Preventif"),
                            ("correctif", "Correctif"),
                        ],
                        default="correctif",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vidange", "Vidange et filtres"),
                            ("pneus", "Pneus"),
                            ("freins", "Freins"),
                            ("inspection", "Inspection mecanique"),
                            ("courroie", "Courroie de distribution"),
                            ("climatisation", "Climatisation"),
                            ("carrosserie", "Carrosserie"),
                            ("electrique", "Systeme electrique"),
                            ("reparation", "Reparation mecanique"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifie"),
                            ("en-cours", "En cours"),
                            ("termine", "Termine"),
                            ("annule", "Annule"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("date_prevue", models.DateField()),
                ("debut", models.DateTimeField(blank=True, null=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("kilometrage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fournisseur",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "cout_pieces",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "cout_main_oeuvre",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes_cloture", models.TextField(blank=True, default="")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_travail_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bon_travail",
                        to="maintenance.incident",
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_travail",
                        to="fleet.vehicule",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_travail",
                        to="entretien.planentretien",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_prevue", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="planentretien",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("intervalle_km__isnull", False),
                    ("intervalle_jours__isnull", False),
                    _connector="OR",
                ),
                name="plan_entretien_intervalle_requis",
            ),
        ),
        migrations.AddIndex(
            model_name="bontravail",
            index=models.Index(
                fields=["statut", "date_prevue"], name="entretien_b_statut_e71a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bontravail",
            index=models.Index(
                fields=["vehicule", "statut"], name="entretien_b_vehicul_aebd8c_idx"
            ),
        ),
    ]
