# Generated by Django 5.2.17 on 2026-09-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionGPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaque", models.CharField(max_length=20)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("precision_m", models.FloatField(blank=True, null=True)),
                ("vitesse_kmh", models.FloatField(blank=True, null=True)),
                ("cap", models.FloatField(blank=True, null=True)),
                ("horodatage", models.DateTimeField()),
                ("recu_le", models.DateTimeField(auto_now_add=True)),
                (
                    "chauffeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="drivers.chauffeur",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="dispatch.trajet",
                    ),
                ),
            ],
            options={
                "ordering": ["horodatage"],
                "indexes": [
                    models.Index(
                        fields=["trajet", "-horodatage"],
                        name="suivi_posit_trajet__1989b5_idx",
                    ),
                    models.Index(
                        fields=["horodatage"], name="suivi_posit_horodat_884e67_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trajet", "horodatage"),
                        name="position_unique_par_instant",
                    )
                ],
            },
        ),
    ]
