# Generated by Django 5.2.17 on 2026-09-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('technique', 'Technique'), ('route', 'Route')], max_length=20)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('heure', models.CharField(max_length=5)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('traite', 'Traite')], default='ouvert', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='drivers.chauffeur')),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='dispatch.trajet')),
            ],
            options={
                'ordering': ['-date', '-heure'],
            },
        ),
    ]
