# Generated by Django 5.2.17 on 2026-09-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('modele', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['plaque'],
            },
        ),
    ]
