# Generated by Django 5.2.17 on 2026-09-25 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicule",
            name="annee",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="kilometrage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="mise_en_service",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="numero_serie",
            field=models.CharField(blank=True, default="", max_length=17),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("maintenance", "En maintenance"),
                    ("hors-service", "Hors service"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReleveKilometrage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kilometrage", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("initial", "Valeur initiale"),
                            ("manuel", "Saisie manuelle"),
                            ("trajet", "Fin de trajet"),
                            ("entretien", "Bon de travail"),
                        ],
                        default="manuel",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("releve_le", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releves_kilometrage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releves",
                        to="fleet.vehicule",
                    ),
                ),
            ],
            options={
                "ordering": ["-releve_le", "-id"],
                "indexes": [
                    models.Index(
                        fields=["vehicule", "-releve_le"],
                        name="fleet_relev_vehicul_cf8899_idx",
                    )
                ],
            },
        ),
    ]
