# Generated by Django 5.2.17 on 2026-09-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('telephone', models.CharField(max_length=30)),
                ('courriel', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('permis_numero', models.CharField(max_length=50)),
                ('permis_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en-trajet', 'En trajet'), ('hors-service', 'Hors service')], default='disponible', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('plaque_habituelle', models.ForeignKey(blank=True, db_column='plaque_habituelle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='fleet.vehicule', to_field='plaque')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
