# Generated by Django 5.2.17 on 2026-09-27 02:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_customapplication_customrecord_installedapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Grille tarifaire')),
                ('activity', models.CharField(choices=[('freight', 'Marchandises'), ('passengers', 'Voyageurs'), ('shuttle', 'Navettes et scolaire'), ('fuel', 'Carburants'), ('cold', 'Frigorifique'), ('bulk', 'Vrac')], default='freight', max_length=20, verbose_name='Activité')),
                ('origin', models.CharField(max_length=180, verbose_name='Départ')),
                ('destination', models.CharField(max_length=180, verbose_name='Destination')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('t', 't'), ('L', 'L'), ('m3', 'm3'), ('colis', 'colis'), ('voyageurs', 'voyageurs'), ('mission', 'mission')], default='t', max_length=15, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix HT par unité')),
                ('minimum', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum de facturation HT')),
                ('valid_from', models.DateField(verbose_name='Valable à partir du')),
                ('valid_until', models.DateField(verbose_name='Valable jusqu’au')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, verbose_name='Référence')),
                ('agreed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant HT convenu')),
                ('due_date', models.DateField(verbose_name='Échéance contractuelle')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions et responsabilités')),
                ('external_vehicle', models.CharField(blank=True, max_length=100, verbose_name='Véhicule du prestataire')),
                ('external_driver', models.CharField(blank=True, max_length=150, verbose_name='Chauffeur du prestataire')),
                ('completion_note', models.TextField(blank=True, verbose_name='Bilan de prestation')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Approuvée'), ('completed', 'Réalisée'), ('cancelled', 'Annulée')], default='draft', max_length=15, verbose_name='Statut')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.mission', verbose_name='Mission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.partner', verbose_name='Transporteur sous-traitant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, verbose_name='Numéro fournisseur')),
                ('date', models.DateField(verbose_name='Date')),
                ('due_date', models.DateField(verbose_name='Échéance')),
                ('lines', models.JSONField(default=list, verbose_name='Prestations facturées')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total HT')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxes')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total TTC')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réglé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('posted', 'Comptabilisée'), ('paid', 'Soldée'), ('cancelled', 'Annulée')], default='draft', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.purchase', verbose_name='Commande d’achat')),
                ('subcontract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.subcontract', verbose_name='Sous-traitance')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.partner', verbose_name='Fournisseur')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, verbose_name='Référence du règlement')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant réglé')),
                ('date', models.DateField(verbose_name='Date du règlement')),
                ('method', models.CharField(choices=[('bank', 'Virement'), ('cash', 'Espèces'), ('mobile', 'Mobile money'), ('cheque', 'Chèque')], default='bank', max_length=20, verbose_name='Mode')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.supplierbill', verbose_name='Facture fournisseur')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, verbose_name='Référence')),
                ('activity', models.CharField(choices=[('freight', 'Marchandises'), ('passengers', 'Voyageurs'), ('shuttle', 'Navettes et scolaire'), ('fuel', 'Carburants'), ('cold', 'Frigorifique'), ('bulk', 'Vrac')], default='freight', max_length=20, verbose_name='Activité')),
                ('origin', models.CharField(max_length=180, verbose_name='Départ')),
                ('destination', models.CharField(max_length=180, verbose_name='Destination')),
                ('description', models.TextField(blank=True, verbose_name='Prestation et conditions')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité par prestation')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('t', 't'), ('L', 'L'), ('m3', 'm3'), ('colis', 'colis'), ('voyageurs', 'voyageurs'), ('mission', 'mission')], default='mission', max_length=15, verbose_name='Unité')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix HT par prestation')),
                ('start_date', models.DateField(verbose_name='Début du contrat')),
                ('end_date', models.DateField(verbose_name='Fin du contrat')),
                ('recurrence', models.CharField(choices=[('once', 'Ponctuelle'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='monthly', max_length=12, verbose_name='Récurrence')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Prochaine prestation')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('paused', 'Suspendu'), ('closed', 'Clôturé')], default='draft', max_length=15, verbose_name='Statut')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.partner', verbose_name='Client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, verbose_name='Référence')),
                ('title', models.CharField(max_length=180, verbose_name='Incident')),
                ('occurred_at', models.DateTimeField(verbose_name='Survenu le')),
                ('severity', models.CharField(choices=[('minor', 'Mineure'), ('major', 'Majeure'), ('critical', 'Critique')], default='minor', max_length=15, verbose_name='Gravité')),
                ('category', models.CharField(choices=[('breakdown', 'Panne'), ('accident', 'Accident'), ('cargo', 'Marchandise'), ('delay', 'Retard'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Nature')),
                ('description', models.TextField(verbose_name='Faits constatés')),
                ('claim_reference', models.CharField(blank=True, max_length=100, verbose_name='Dossier assurance')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût estimé')),
                ('resolution', models.TextField(blank=True, verbose_name='Mesures prises et résolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('reported', 'Signalé'), ('resolved', 'Résolu')], default='draft', max_length=15, verbose_name='Statut')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.mission', verbose_name='Mission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'reference'), name='erp_incident_reference')],
            },
        ),
        migrations.AddConstraint(
            model_name='subcontract',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='erp_subcontract_reference'),
        ),
        migrations.AddConstraint(
            model_name='supplierbill',
            constraint=models.UniqueConstraint(fields=('organization', 'supplier', 'reference'), name='erp_supplier_bill_reference'),
        ),
        migrations.AddConstraint(
            model_name='supplierbill',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('purchase',), name='erp_one_bill_per_purchase'),
        ),
        migrations.AddConstraint(
            model_name='supplierbill',
            constraint=models.UniqueConstraint(condition=models.Q(('subcontract__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('subcontract',), name='erp_one_bill_per_subcontract'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='erp_supplier_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='transportcontract',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='erp_contract_reference'),
        ),
    ]
