# Generated by Django 5.2.17 on 2026-09-27 02:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_extended_tenant_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Période')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(verbose_name='Fin incluse')),
                ('closing_note', models.TextField(blank=True, verbose_name='Note de clôture')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturée le')),
                ('status', models.CharField(choices=[('draft', 'Ouverte'), ('closed', 'Clôturée')], default='draft', max_length=20, verbose_name='Statut')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(verbose_name='Fin incluse')),
                ('kind', models.CharField(choices=[('annual', 'Congé annuel'), ('unpaid', 'Sans solde'), ('sick', 'Maladie'), ('other', 'Autre')], default='annual', max_length=20, verbose_name='Nature')),
                ('reason', models.TextField(blank=True, verbose_name='Motif')),
                ('decision_note', models.TextField(blank=True, verbose_name='Motif de décision')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'À approuver'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Salarié')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=120, verbose_name='Référence du relevé / opération')),
                ('date', models.DateField(verbose_name='Date de valeur')),
                ('description', models.CharField(max_length=180, verbose_name='Libellé bancaire')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant (+ entrée / − sortie)')),
                ('reconciliation_note', models.TextField(blank=True, verbose_name='Note de rapprochement')),
                ('status', models.CharField(choices=[('draft', 'À rapprocher'), ('matched', 'Rapprochée')], default='draft', max_length=20, verbose_name='Statut')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.account', verbose_name='Compte de trésorerie')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.journalentry', verbose_name='Écriture rapprochée')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'account', 'reference'), name='erp_statement_reference'), models.UniqueConstraint(condition=models.Q(('status', 'matched')), fields=('organization', 'account', 'journal'), name='erp_statement_match')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date demandée')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='Justificatif du décaissement')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date du décaissement')),
                ('settlement_reference', models.CharField(blank=True, max_length=120, verbose_name='Justificatif du remboursement')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='Date du remboursement')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Approuvée'), ('disbursed', 'Versée'), ('settled', 'Remboursée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Salarié')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'reference'), name='erp_advance_reference')],
            },
        ),
    ]
