# Generated by Django 5.2.17 on 2026-09-27 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_delivery_tenant_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with_customer',
            field=models.BooleanField(default=False, verbose_name='Visible dans le portail client'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.partner'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('operations', 'Exploitation'), ('finance', 'Finance'), ('workshop', 'Atelier'), ('driver', 'Chauffeur'), ('viewer', 'Lecture seule'), ('client', 'Client externe')], max_length=20),
        ),
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='erp_portal_user_unique')],
            },
        ),
    ]
