# Generated by Django 5.2.17 on 2026-09-27 19:10

import apps.erp.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_portal_tenant_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('incident', 'Incident'), ('request', 'Demande atelier'), ('check', 'Contrôle avant départ'), ('mileage', 'Relevé compteur')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.incident')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.maintenance')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.mission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.erp.models.private_path)),
                ('title', models.CharField(max_length=180)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='erp.fieldreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'key'), name='erp_notification_read_unique')],
            },
        ),
    ]
