# Generated by Django 5.2.17 on 2026-10-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_portal_client_contact_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='tracking_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='tracking_lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='tracking_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='tracking_status',
            field=models.CharField(default='waiting', max_length=24),
        ),
        migrations.AddField(
            model_name='position',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='client_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('mission', 'client_id'), name='erp_position_client_once'),
        ),
    ]
