# Generated by Django 5.2.17 on 2026-10-04 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_mission_tracking_ended_at_mission_tracking_lost_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.partner', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='activity',
            field=models.CharField(choices=[('freight', 'Marchandises'), ('passengers', 'Voyageurs'), ('shuttle', 'Navettes et scolaire'), ('fuel', 'Carburants'), ('cold', 'Frigorifique'), ('bulk', 'Vrac')], default='freight', max_length=20, verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='destination',
            field=models.CharField(blank=True, max_length=180, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='origin',
            field=models.CharField(blank=True, max_length=180, verbose_name='Départ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=15, verbose_name='État du devis'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.CharField(choices=[('kg','kg'),('t','t'),('L','L'),('m3','m3'),('colis','colis'),('voyageurs','voyageurs'),('mission','mission')],default='mission', max_length=15, verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='partner',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='partner',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province / région'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='destination_contact',
            field=models.CharField(blank=True, max_length=180, verbose_name='Contact à destination'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='origin_contact',
            field=models.CharField(blank=True, max_length=180, verbose_name='Contact au départ'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='source_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_order', to='erp.invoice'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de fenêtre'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de fenêtre'),
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Courriel')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='erp.partner')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
