# Generated by Django 5.2.17 on 2026-10-04 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_client_messaging_tenant_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'resource', 'object_id', '-created_at'], name='erp_client_audit_lookup'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'customer', 'kind', 'status'], name='erp_customer_invoices'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['organization', 'kind', 'archived_at', 'name'], name='erp_client_directory'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['organization', 'customer', '-created_at'], name='erp_customer_orders'),
        ),
    ]
