# Generated by Django 5.2.17 on 2026-10-05 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


def install(apps, editor):
    if editor.connection.vendor != 'postgresql':
        return
    editor.execute('ALTER TABLE erp_quotelink ADD CONSTRAINT erp_quotelink_quote_tenant FOREIGN KEY (organization_id,quote_id) REFERENCES erp_invoice (organization_id,id) DEFERRABLE INITIALLY IMMEDIATE')


def uninstall(apps, editor):
    if editor.connection.vendor == 'postgresql':
        editor.execute('ALTER TABLE erp_quotelink DROP CONSTRAINT erp_quotelink_quote_tenant')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_operations_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('responded_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_link', to='erp.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RunPython(install, uninstall),
    ]
