"""schema initial
Auteur : Jonathan K-N

Cree les 7 tables de depart (groupes, comptes, comptes_groupes, vehicules,
chauffeurs, trajets, arrets, incidents) a partir des modeles SQLAlchemy de
backend/apps/*/models.py -- genere automatiquement par
`alembic revision --autogenerate`, revu avant d etre applique.

Revision ID: 00638b91a222
Revises:
Create Date: 2026-09-13 15:14:06.923890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00638b91a222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaque', sa.String(), nullable=False),
    sa.Column('modele', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicules_plaque'), 'vehicules', ['plaque'], unique=True)
    op.create_table('chauffeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('courriel', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('permis_numero', sa.String(), nullable=False),
    sa.Column('permis_expiration', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('plaque_habituelle', sa.String(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plaque_habituelle'], ['vehicules.plaque'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comptes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courriel', sa.String(), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chauffeur_id')
    )
    op.create_index(op.f('ix_comptes_courriel'), 'comptes', ['courriel'], unique=True)
    op.create_table('trajets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('plaque', sa.String(), nullable=False),
    sa.Column('depart', sa.String(), nullable=False),
    sa.Column('depart_adresse', sa.String(), nullable=True),
    sa.Column('arrivee', sa.String(), nullable=False),
    sa.Column('debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin_prevue', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trajet_id', sa.Integer(), nullable=False),
    sa.Column('lieu', sa.String(), nullable=False),
    sa.Column('heure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trajet_id'], ['trajets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comptes_groupes',
    sa.Column('compte_id', sa.Integer(), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.PrimaryKeyConstraint('compte_id', 'groupe_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trajet_id', sa.Integer(), nullable=True),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lieu', sa.String(), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], ),
    sa.ForeignKeyConstraint(['trajet_id'], ['trajets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('comptes_groupes')
    op.drop_table('arrets')
    op.drop_table('trajets')
    op.drop_index(op.f('ix_comptes_courriel'), table_name='comptes')
    op.drop_table('comptes')
    op.drop_table('chauffeurs')
    op.drop_index(op.f('ix_vehicules_plaque'), table_name='vehicules')
    op.drop_table('vehicules')
    op.drop_table('groupes')
    # ### end Alembic commands ###
