# Generated by Django 5.2.17 on 2026-09-25 13:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(choices=[('hebdomadaire', 'Chaque semaine'), ('deux-semaines', 'Aux deux semaines'), ('bimensuelle', 'Deux fois par mois'), ('mensuelle', 'Chaque mois')], default='deux-semaines', max_length=20)),
                ('seuil_heures_sup', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=5)),
                ('majoration_heures_sup', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('taux_vacances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('date_paiement', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validee'), ('payee', 'Payee')], default='brouillon', max_length=10)),
                ('calculee_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Retenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('taux_salarie', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('taux_employeur', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('plancher_annuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('plafond_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exemption_annuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='horaire', max_length=10)),
                ('nombre_trajets', models.PositiveIntegerField(default=0)),
                ('heures_regulieres', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('heures_sup', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('brut', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('brut_imposable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('retenues', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cotisations_employeur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_paie', to='drivers.chauffeur')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='paie.periodepaie')),
            ],
            options={
                'ordering': ['chauffeur__nom', 'chauffeur__prenom'],
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('gain', 'Gain'), ('retenue', 'Retenue'), ('employeur', 'Cotisation employeur')], max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=150)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('taux', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imposable', models.BooleanField(default=True)),
                ('manuelle', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.bulletinpaie')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfilPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('horaire', 'A l heure'), ('trajet', 'Au trajet'), ('fixe', 'Salaire fixe par paie')], default='horaire', max_length=10)),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('taux_trajet', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('salaire_periode', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('chauffeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_paie', to='drivers.chauffeur')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bulletinpaie',
            constraint=models.UniqueConstraint(fields=('periode', 'chauffeur'), name='un_bulletin_par_periode'),
        ),
    ]
