import {test,expect} from '@playwright/test'
import {mkdirSync,writeFileSync} from 'node:fs'
import {dirname} from 'node:path'
test.use({actionTimeout:30000})

test('CRM : client, devis, commande, mission, livraison, facture, paiements et portail isolé',async({page,browser,request},info)=>{
 test.setTimeout(360000)
 const stamp=Date.now()+'-'+info.project.name,password='Commercial-Test-938!',ownerEmail='crm-owner-'+stamp+'@example.test',driverEmail='crm-driver-'+stamp+'@example.test',clientEmail='crm-client-'+stamp+'@example.test'
 const registered=await request.post('/api/v2/auth/register',{data:{name:'Direction TEST CRM',email:ownerEmail,password,organization:{name:'TEST CRM '+stamp,country:'GN',currency:'USD',timezone:'Africa/Conakry',activities:['freight']}}})
 expect(registered.status()).toBe(201)
 const owner=await registered.json(),org=owner.organizations[0].id,headers={Authorization:'Bearer '+owner.access,'X-Organization':org}
 const proof:any={status:'running',profile:info.project.name,organization:org,owner_email:ownerEmail,customer_email:clientEmail,stage:'registered'};const proofPath=info.outputPath('crm-proof.json');mkdirSync(dirname(proofPath),{recursive:true});const saveProof=(stage:string)=>{proof.stage=stage;writeFileSync(proofPath,JSON.stringify(proof,null,2))};saveProof('registered')
 const post=async(path:string,data:any={})=>{const r=await request.post('/api/v2/'+path,{headers,data});expect(r.status(),(await r.text()).slice(0,500)).toBeGreaterThanOrEqual(200);expect(r.status()).toBeLessThan(300);return r.status()===204?null:await r.json()}
 const get=async(path:string)=>{const r=await request.get('/api/v2/'+path,{headers});expect(r.status()).toBe(200);return r.json()}
 const vehicle=await post('vehicles',{name:'TEST Camion CRM',plate:'CRM-'+stamp,capacity:'1000',capacity_unit:'kg'})
 const invitation=await post('team',{email:driverEmail,role:'driver'})
 const driverResponse=await request.post('/api/v2/auth/register',{data:{name:'Chauffeur TEST CRM',email:driverEmail,password,invitation:new URL(invitation.link).searchParams.get('invitation')}});expect(driverResponse.status()).toBe(201)
 const driverAccount=await driverResponse.json(),driver=(await get('employees')).results.find((x:any)=>x.email===driverEmail)
 expect(driver).toBeTruthy()
 const login=async(p:any,email:string)=>{await p.goto('/connexion');await p.getByLabel('Adresse courriel').fill(email);await p.getByLabel('Mot de passe',{exact:true}).fill(password);await p.getByRole('button',{name:'Se connecter',exact:true}).click()}
 await login(page,ownerEmail);await expect(page.locator('.workspace')).toBeVisible()
 const navigate=async(name:string)=>{const width=page.viewportSize()?.width||1280;if(width<=600)await page.getByRole('navigation',{name:'Navigation mobile'}).getByRole('button',{name:'Plus',exact:true}).click();else if(width<=900)await page.getByRole('button',{name:'Menu',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name,exact:true}).click()}
 if(info.project.name==='small')await page.setViewportSize({width:360,height:740})
 await navigate('Clients');await page.getByRole('button',{name:'+ Nouveau client',exact:true}).click()
 let dialog=page.getByRole('dialog')
 await dialog.getByLabel(/^Nom\s*\*?$/).fill('Client TEST Transport '+stamp)
 await dialog.getByLabel('Courriel').fill(clientEmail)
 await dialog.getByLabel('Nom du contact').fill('Contact TEST')
 await dialog.getByLabel('Notes',{exact:true}).fill('CONFIDENTIEL INTERNE '+stamp)
 await dialog.getByRole('button',{name:/Enregistrer/}).click();await expect(dialog).toHaveCount(0)
 const customer=(await get('clients')).results.find((x:any)=>x.email===clientEmail);expect(customer).toBeTruthy();proof.customer=customer.id;saveProof('client-created')
 await page.getByRole('button',{name:customer.name,exact:true}).click();await expect(page.getByRole('heading',{name:customer.name,exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Créer un devis',exact:true}).click();dialog=page.getByRole('dialog')
 await dialog.getByLabel('Départ',{exact:true}).fill('Conakry');await dialog.getByLabel('Destination',{exact:true}).fill('Kindia')
 await dialog.getByLabel('Description',{exact:true}).fill('Transport TEST CRM');await dialog.getByLabel('Quantité',{exact:true}).fill('2');await dialog.getByLabel('Prix unitaire',{exact:true}).fill('100')
 await dialog.getByRole('button',{name:/Enregistrer/}).click();await expect(dialog).toHaveCount(0)
 await page.getByRole('button',{name:'Devis',exact:true}).click();await page.getByRole('button',{name:'Marquer comme envoyé',exact:true}).click();await page.getByRole('button',{name:'Accepter',exact:true}).click();await page.getByRole('button',{name:'Créer la commande',exact:true}).click()
 await expect.poll(async()=> (await get('orders')).count).toBe(1)
 const quote=(await get('invoices?kind=quote')).results[0],order=(await get('orders')).results[0];expect(order.source_quote).toBe(quote.id);proof.quote=quote.id;proof.order=order.id;saveProof('order-created')
 await page.getByRole('navigation',{name:'Dossier client'}).getByRole('button',{name:'Commandes',exact:true}).click();await page.getByRole('button',{name:'Confirmer la commande',exact:true}).click();await page.getByRole('button',{name:'Planifier la mission',exact:true}).click();dialog=page.getByRole('dialog')
 await expect(dialog.getByLabel(/^Départ\s*\*?$/)).toHaveValue('Conakry')
 await dialog.getByLabel('Chauffeur',{exact:true}).selectOption(driver.id);await dialog.getByLabel('Véhicule',{exact:true}).selectOption(vehicle.id)
 await dialog.getByRole('button',{name:/Enregistrer/}).click();await expect(dialog).toHaveCount(0)
 await page.getByRole('button',{name:'Missions / Livraisons',exact:true}).click();await page.getByRole('button',{name:'Démarrer',exact:true}).click();await expect(page.getByRole('button',{name:'Terminer',exact:true})).toBeVisible()
 const mission=(await get('missions')).results[0];expect(mission.order).toBe(order.id);expect(mission.status).toBe('active');proof.mission=mission.id;saveProof('mission-active')
 const driverContext=await browser.newContext({...info.project.use,baseURL:process.env.TF_TEST_URL||'http://127.0.0.1:8000',permissions:['geolocation'],geolocation:{latitude:9.537,longitude:-13.678,accuracy:5}} as any)
 await driverContext.addInitScript(()=>{const geo=navigator.geolocation;const normalize=(p:any)=>({coords:p.coords,timestamp:p.timestamp>Date.now()*10?p.timestamp/1000:p.timestamp});const watch=geo.watchPosition.bind(geo),current=geo.getCurrentPosition.bind(geo);geo.watchPosition=(ok,error,opts)=>watch(p=>ok(normalize(p)),e=>{if(e.code!==2)error?.(e)},opts);geo.getCurrentPosition=(ok,error,opts)=>current(p=>ok(normalize(p)),error,opts)})
 try{const driverPage=await driverContext.newPage();await login(driverPage,driverEmail);await expect(driverPage.getByTestId('driver-tracking')).toBeVisible();const authorize=driverPage.getByRole('button',{name:/Autoriser|Activer le GPS/});if(await authorize.count())await authorize.first().click();await expect.poll(async()=> (await get('missions/'+mission.id+'/positions')).positions?.length||0,{timeout:60000}).toBeGreaterThan(0)}finally{await driverContext.close()}
 await page.getByRole('button',{name:'Terminer',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel(/^Quantité livrée/).fill('2');await dialog.getByRole('button',{name:/Clôturer la mission/}).click();await expect(dialog).toHaveCount(0)
 await page.getByRole('button',{name:'Justificatif signé',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Nom du destinataire',{exact:true}).fill('Destinataire TEST CRM');const pad=dialog.locator('.signature-pad');await pad.scrollIntoViewIfNeeded();const box=await pad.boundingBox();expect(box).not.toBeNull();await page.mouse.move(box!.x+20,box!.y+50);await page.mouse.down();await page.mouse.move(box!.x+100,box!.y+20,{steps:5});await page.mouse.move(box!.x+150,box!.y+70,{steps:5});await page.mouse.up();await dialog.getByRole('checkbox',{name:/Je confirme la réception/}).check();await dialog.getByRole('button',{name:'Confirmer la signature',exact:true}).click();await expect(dialog.getByText('Livraison signée',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Fermer',exact:true}).click()
 await page.getByRole('button',{name:'Créer la facture',exact:true}).click();await page.getByRole('button',{name:'Factures',exact:true}).click();await page.getByRole('button',{name:'Émettre la facture',exact:true}).click();await expect(page.getByRole('button',{name:'Enregistrer un paiement',exact:true})).toBeVisible()
 let invoice=(await get('invoices?kind=invoice')).results[0];expect(invoice.status).toBe('issued');expect(invoice.total).toBe('200.00')
 for(const [amount,reference] of [['75','CRM-PARTIAL-'+stamp],['125','CRM-FINAL-'+stamp]]){await page.getByRole('button',{name:'Enregistrer un paiement',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Montant',{exact:true}).fill(amount);await dialog.getByLabel(/^Référence du règlement/).fill(reference);await dialog.getByRole('button',{name:/Enregistrer/}).click();await expect(dialog).toHaveCount(0)}
 invoice=(await get('invoices?kind=invoice')).results[0];expect(invoice.status).toBe('paid');expect(invoice.balance).toBe('0');proof.invoice=invoice.id;proof.invoice_number=invoice.number;proof.invoice_status=invoice.status;proof.balance=invoice.balance;saveProof('paid')
 await page.getByRole('button',{name:'Aperçu',exact:true}).click();await expect(page.locator('.crm-metrics')).toContainText('0,00')
 await page.getByRole('button',{name:'Inviter au portail',exact:true}).click();await expect(page.getByRole('button',{name:'Renvoyer',exact:true})).toBeVisible();const invitations=(await get('portal-access/invitations')).results;expect(invitations.some((x:any)=>x.partner===customer.id&&x.status==='pending')).toBeTruthy()
 // The test obtains a fresh token through the existing resend operation.
 const portalInvite=await post('portal-access/invitations/'+invitations.find((x:any)=>x.partner===customer.id&&x.status==='pending').id+'/resend')
 const otherClient=await post('partners',{name:'TEST Autre client '+stamp,kind:'customer'})
 const today=new Date().toISOString().slice(0,10)
 const draft=await post('invoices',{customer:customer.id,kind:'invoice',date:today,due_date:today,lines:[{description:'BROUILLON PRIVÉ '+stamp,quantity:'1',price:'10',tax_rate:'0'}]})
 const documents:any[]=[]
 for(const [title,partner,shared] of [['TEST Document partagé',customer.id,true],['TEST Document privé',customer.id,false],['TEST Document autre client',otherClient.id,true]]){const r=await request.post('/api/v2/documents',{headers,multipart:{title:String(title)+' '+stamp,category:'other',customer:String(partner),shared_with_customer:String(shared),file:{name:'test-crm.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')}}});expect(r.status(),await r.text()).toBe(201);documents.push(await r.json())}
 await post('clients/'+otherClient.id+'/archive')
 const foreignResponse=await request.post('/api/v2/auth/register',{data:{name:'Direction TEST Isolation',email:'crm-foreign-'+stamp+'@example.test',password,organization:{name:'TEST CRM Isolation '+stamp,country:'GN',currency:'USD',timezone:'Africa/Conakry',activities:['freight']}}});expect(foreignResponse.status()).toBe(201);const foreign=await foreignResponse.json(),foreignHeaders={Authorization:'Bearer '+foreign.access,'X-Organization':foreign.organizations[0].id}
 for(const path of ['clients/'+customer.id,'clients/'+customer.id+'/activity','invoices/'+invoice.id,'documents/'+documents[0].id])expect((await request.get('/api/v2/'+path,{headers:foreignHeaders})).status()).toBe(404)
 expect((await request.patch('/api/v2/partners/'+customer.id,{headers:foreignHeaders,data:{name:'INTERDIT'}})).status()).toBe(404)
 const portalContext=await browser.newContext({...info.project.use,baseURL:process.env.TF_TEST_URL||'http://127.0.0.1:8000'} as any)
 let portalAccount:any
 try{const clientPage=await portalContext.newPage();await clientPage.goto('/app'+new URL(portalInvite.link).search);await clientPage.getByLabel('Votre nom complet').fill('Client TEST CRM');await clientPage.getByLabel('Adresse courriel').fill(clientEmail);await clientPage.getByLabel('Mot de passe',{exact:true}).fill(password);await clientPage.getByRole('button',{name:'Rejoindre mon entreprise',exact:true}).click();await expect(clientPage.locator('.client-portal')).toBeVisible();await expect(clientPage.locator('.client-portal')).toContainText(order.reference);await clientPage.getByRole('button',{name:'Mes factures',exact:true}).click();await expect(clientPage.locator('.client-portal')).toContainText(invoice.number);await expect(clientPage.locator('.client-portal')).not.toContainText('CONFIDENTIEL INTERNE');portalAccount=await (await request.post('/api/v2/auth/login',{data:{email:clientEmail,password}})).json();const h={Authorization:'Bearer '+portalAccount.access,'X-Organization':org};for(const resource of ['employees','clients','tracking','messaging/conversations'])expect((await request.get('/api/v2/'+resource,{headers:h})).status()).toBe(403);const published=(await (await request.get('/api/v2/portal/invoices',{headers:h})).json()).results;expect(published.some((x:any)=>x.id===draft.id||x.id===quote.id)).toBeFalsy();
 await clientPage.getByRole('button',{name:'Mes documents',exact:true}).click();await expect(clientPage.locator('.client-portal')).toContainText(documents[0].title);await expect(clientPage.locator('.client-portal')).not.toContainText(documents[1].title);await expect(clientPage.locator('.client-portal')).not.toContainText(documents[2].title);
 expect((await request.get('/api/v2/portal/document/'+documents[0].id,{headers:h})).status()).toBe(200);for(const d of documents.slice(1))expect((await request.get('/api/v2/portal/document/'+d.id,{headers:h})).status()).toBe(404);
 await post('clients/'+customer.id+'/conversation');await post('clients/'+customer.id+'/messages',{body:'TEST Votre livraison est confirmée '+stamp,client_id:crypto.randomUUID()});
 await clientPage.getByRole('button',{name:'Messages',exact:true}).click();await expect(clientPage.locator('.client-discussion')).toContainText('TEST Votre livraison est confirmée '+stamp);await clientPage.getByLabel('Votre message').fill('TEST Merci pour la livraison '+stamp);await clientPage.getByRole('button',{name:'Envoyer le message',exact:true}).click();await expect(clientPage.locator('.client-discussion')).toContainText('TEST Merci pour la livraison '+stamp);expect((await get('clients/'+customer.id+'/messages')).count).toBe(2);
 expect(await clientPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await clientPage.screenshot({path:'test-results/crm-portal-'+info.project.name+'.png',fullPage:true})}finally{await portalContext.close()}
 await page.getByRole('button',{name:'Archiver le client',exact:true}).click();await expect(page.getByRole('button',{name:'Restaurer le client',exact:true})).toBeVisible();expect((await get('clients')).results.some((x:any)=>x.id===customer.id)).toBeFalsy();expect((await get('orders')).count).toBe(1);expect((await get('payments')).count).toBe(2);await page.getByRole('button',{name:'Restaurer le client',exact:true}).click();await expect(page.getByRole('button',{name:'Archiver le client',exact:true})).toBeVisible();expect((await get('clients')).count).toBe(1);await page.getByRole('button',{name:'Archiver le client',exact:true}).click();await expect(page.getByRole('button',{name:'Restaurer le client',exact:true})).toBeVisible()
 const access=(await get('portal-access')).results.find((x:any)=>x.email===clientEmail);await page.getByRole('button',{name:'Suspendre',exact:true}).click();await expect(page.getByRole('button',{name:'Réactiver',exact:true})).toBeVisible();expect((await get('portal-access')).results.find((x:any)=>x.id===access.id).active).toBeFalsy()
 await post('employees/'+driver.id+'/remove');expect((await request.patch('/api/v2/vehicles/'+vehicle.id,{headers,data:{status:'retired'}})).status()).toBe(200)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/crm-complete-'+info.project.name+'.png',fullPage:true});proof.status='passed';proof.customer_archived=true;proof.portal_suspended=true;proof.driver_removed=true;proof.vehicle_retired=true;saveProof('completed')
})
