// Auteur : Jonathan Kakesa (JonathanK-N).
import {test,expect} from '@playwright/test'

test('Livraison signée par le chauffeur et justificatif dans le portail client',async({page,request})=>{
 test.setTimeout(240000)
 const suffix=Date.now(),password='Livraison-Recette-934!'
 const register=async(email:string,invitation='',organization:any=undefined)=>{
  const response=await request.post('/api/v2/auth/register',{data:{name:'Contact recette',email,password,invitation,organization}})
  expect(response.status()).toBe(201);return await response.json()
 }
 const admin=await register(`direction-livraison-${suffix}@example.test`,'',{name:'Transport livraison',country:'GN',currency:'GNF',timezone:'Africa/Conakry',activities:['freight']})
 const headers={Authorization:'Bearer '+admin.access,'X-Organization':admin.organizations[0].id}
 const post=async(path:string,data:any)=>{const response=await request.post('/api/v2/'+path,{headers,data});expect(response.ok(),await response.text()).toBeTruthy();return await response.json()}
 const driverEmail=`chauffeur-livraison-${suffix}@example.test`
 const invited=await post('team',{email:driverEmail,role:'driver'})
 const driver=await register(driverEmail,new URL(invited.link).searchParams.get('invitation')!)
 const employee=await post('employees',{name:'Chauffeur recette',job:'driver',user:driver.user.id})
 const vehicle=await post('vehicles',{plate:'SIGN-'+suffix,name:'Camion',capacity:20,capacity_unit:'t'})
 const customer=await post('partners',{name:'Client livraison'})
 const order=await post('orders',{reference:'CMD-'+suffix,customer:customer.id,origin:'Conakry',destination:'Kindia',planned_date:'2026-09-27'})
 await post(`orders/${order.id}/actions/confirm`,{})
 const departure=new Date(Date.now()+3600000),arrival=new Date(Date.now()+18000000)
 const trip=await post('missions',{reference:'LIV-'+suffix,order:order.id,vehicle:vehicle.id,driver:employee.id,origin:'Conakry',destination:'Kindia',departure:departure.toISOString(),arrival:arrival.toISOString()})
 await post(`missions/${trip.id}/actions/start`,{})
 await post(`missions/${trip.id}/actions/complete`,{loaded_quantity:10,delivered_quantity:10,delivery_note:'Colis livrés.'})
 await page.goto('/connexion')
 await page.getByLabel('Adresse courriel').fill(driverEmail)
 await page.getByLabel('Mot de passe',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Se connecter',exact:true}).click()
 await page.locator('.sidebar').getByRole('button',{name:'Terrain & notifications',exact:true}).click()
 await page.getByRole('button',{name:'Nouvelle déclaration',exact:true}).click()
 await page.getByRole('combobox',{name:'Mission',exact:true}).selectOption(trip.id)
 await page.getByLabel('Objet',{exact:true}).fill('Pneu endommagé recette')
 await page.getByLabel('Description et anomalies',{exact:true}).fill('Dégradation constatée après livraison.')
 await page.getByRole('button',{name:'Enregistrer la déclaration',exact:true}).click()
 const fieldCard=page.locator('.field-card').filter({hasText:'Pneu endommagé recette'})
 await expect(fieldCard.getByRole('heading',{name:'Pneu endommagé recette'})).toBeVisible()
 await fieldCard.locator('input[type=file]').setInputFiles({name:'constat.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nconstat recette')})
 await fieldCard.getByRole('button',{name:'Joindre le fichier',exact:true}).click()
 await expect(fieldCard.getByRole('button',{name:'constat.pdf'})).toBeVisible()
 const incidentResult=await request.get('/api/v2/incidents',{headers})
 const incident=(await incidentResult.json()).results[0]
 await post(`incidents/${incident.id}/actions/resolve`,{resolution:'Pneu remplacé par atelier.'})
 await page.getByRole('button',{name:'Actualiser le suivi',exact:true}).click()
 await expect(fieldCard.getByText('Pneu remplacé par atelier.',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:/Notifications/}).last().click()
 await page.getByRole('button',{name:'Marquer comme lu',exact:true}).first().click()
 await page.setViewportSize({width:390,height:844})
 await expect(page.locator('.field-workspace')).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.screenshot({path:'test-results/terrain-mobile.png',fullPage:true})
 await page.setViewportSize({width:1280,height:720})
 await page.locator('.sidebar').getByRole('button',{name:'Missions',exact:true}).click()
 await page.getByRole('button',{name:'Justificatif signé',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByLabel('Nom du destinataire',{exact:true}).fill('Destinataire recette')
 await dialog.getByLabel('Réserves du destinataire',{exact:true}).fill('Marchandise reçue sans écart.')
 await dialog.locator('.signature-pad').scrollIntoViewIfNeeded()
 const box=await dialog.locator('.signature-pad').boundingBox();expect(box).not.toBeNull()
 await page.mouse.move(box!.x+30,box!.y+box!.height*.65);await page.mouse.down()
 await page.mouse.move(box!.x+90,box!.y+box!.height*.25,{steps:5})
 await page.mouse.move(box!.x+160,box!.y+box!.height*.65,{steps:5});await page.mouse.up()
 await dialog.getByRole('checkbox',{name:'Je confirme la réception',exact:false}).check()
 await dialog.getByRole('button',{name:'Confirmer la signature',exact:true}).click()
 await expect(dialog.getByText('Livraison signée',{exact:true})).toBeVisible()
 const pdf=page.waitForEvent('download')
 await dialog.getByRole('button',{name:'Télécharger le justificatif PDF',exact:true}).click()
 expect(await (await pdf).failure()).toBeNull()
 await page.screenshot({path:'test-results/livraison-signee.png',fullPage:true})
 await dialog.getByRole('button',{name:'Fermer',exact:true}).click()
 await page.getByTitle('Se déconnecter').click()
 const email=`client-livraison-${suffix}@example.test`
 const portal=await post('portal-access',{email,partner:customer.id})
 await register(email,new URL(portal.link).searchParams.get('invitation')!)
 await page.goto('/connexion');await page.getByLabel('Adresse courriel').fill(email)
 await page.getByLabel('Mot de passe',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Se connecter',exact:true}).click()
 await expect(page.locator('.client-portal')).toBeVisible()
 await expect(page.getByText(order.reference,{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Mes livraisons',exact:true}).click()
 const proof=page.waitForEvent('download')
 await page.getByRole('button',{name:'Livraison signée',exact:true}).click()
 expect(await (await proof).failure()).toBeNull()
 await page.screenshot({path:'test-results/portail-client.png',fullPage:true})
 await page.reload();await expect(page.locator('.client-portal')).toBeVisible()
})

test('Accueil réel, inscription, flotte, session et sortie',async({page})=>{
 const errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByRole('heading',{name:/Votre transport/})).toBeVisible()
 await expect(page.locator('.hero img').first()).toBeVisible()
 await page.screenshot({path:'test-results/accueil.png',fullPage:true})
 await page.goto('/commencer')
 const suffix=Date.now()
 await page.getByLabel('Votre nom complet').fill('Jonathan Recette')
 await page.getByLabel('Adresse courriel').fill(`recette-${suffix}@example.test`)
 await page.getByLabel('Mot de passe',{exact:true}).fill('Recette-Transport-493!')
 await page.getByLabel('Nom de l’entreprise').fill(`Transport Recette ${suffix}`)
 await page.getByRole('button',{name:'Créer mon entreprise'}).click()
 await expect(page.locator('.workspace')).toBeVisible()
 await expect(page.getByRole('heading',{name:'Vue d’ensemble'})).toBeVisible()
 await page.screenshot({path:'test-results/espace-entreprise.png',fullPage:true})
 await page.getByRole('button',{name:'Flotte',exact:true}).click()
 await page.getByRole('button',{name:'Nouveau',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByLabel('Immatriculation').fill('RC-TEST-001')
 await dialog.getByLabel('Marque / modèle').fill('Mercedes Actros')
 await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.getByText('RC-TEST-001')).toBeVisible()
 await page.reload()
 await expect(page.locator('.workspace')).toBeVisible()
 await expect(page.getByText('RC-TEST-001')).toBeVisible()
 await page.getByTitle('Se déconnecter').click()
 await expect(page.getByRole('button',{name:'Se connecter',exact:true})).toBeVisible()
 await page.goto('/app')
 await expect(page.getByRole('button',{name:'Se connecter',exact:true})).toBeVisible()
 expect(errors).toEqual([])
})

test('Accueil mobile sans débordement',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await expect(page.getByRole('heading',{name:/Votre transport/})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.screenshot({path:'test-results/accueil-mobile.png',fullPage:true})
})

test('Facture émise dans le navigateur et entreprise indépendante',async({page,request})=>{
 const suffix=Date.now(),password='Recette-Finance-392!'
 async function register(label:string,country:string,currency:string){
  const email=`${label}-${suffix}@example.test`
  const response=await request.post('/api/v2/auth/register',{data:{name:'Direction '+label,email,password,organization:{name:'Transport '+label,country,currency,timezone:'Africa/Conakry',activities:['freight']}}})
  expect(response.status()).toBe(201)
  const data=await response.json()
  return {email,headers:{Authorization:'Bearer '+data.access,'X-Organization':data.organizations[0].id}}
 }
 const a=await register('Guinee','GN','GNF'),b=await register('Cameroun','CM','XAF')
 const customerResponse=await request.post('/api/v2/partners',{headers:a.headers,data:{name:'Client recette facturation'}})
 expect(customerResponse.status()).toBe(201)
 const customer=await customerResponse.json()
 await page.goto('/connexion')
 await page.getByLabel('Adresse courriel').fill(a.email)
 await page.getByLabel('Mot de passe',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Se connecter',exact:true}).click()
 await expect(page.locator('.workspace')).toBeVisible()
 await page.locator('.sidebar').getByRole('button',{name:'Facturation',exact:true}).click()
 await page.getByRole('button',{name:'Nouveau',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByRole('combobox',{name:/Client/}).selectOption(customer.id)
 await dialog.getByLabel(/^Date/).fill('2026-09-26')
 await dialog.getByLabel(/^Échéance/).fill('2026-10-26')
 await dialog.getByLabel('Description',{exact:true}).fill('Conakry — Kindia')
 await dialog.getByLabel('Prix unitaire',{exact:true}).fill('100')
 await dialog.getByLabel('Taxe (%)',{exact:true}).fill('18')
 await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click()
 await expect(dialog).not.toBeVisible()
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'Émettre',exact:true}).click()
 await expect(page.locator('tbody .status')).toHaveText('Émise')
 const invoices=await (await request.get('/api/v2/invoices',{headers:a.headers})).json()
 expect(invoices.results[0].total).toBe('118.00')
 const forbidden=await request.get('/api/v2/invoices/'+invoices.results[0].id,{headers:b.headers})
 expect(forbidden.status()).toBe(404)
 const isolated=await (await request.get('/api/v2/invoices',{headers:b.headers})).json()
 expect(isolated.count).toBe(0)
 await page.screenshot({path:'test-results/facturation.png',fullPage:true})
})

test('Studio : créer une application et retrouver ses fiches',async({page,request})=>{
 const email=`studio-${Date.now()}@example.test`,password='Studio-Recette-459!'
 const result=await request.post('/api/v2/auth/register',{data:{name:'Direction Studio',email,password,organization:{name:'Transport Studio',country:'GN',currency:'GNF',timezone:'Africa/Conakry',activities:['freight']}}})
 expect(result.status()).toBe(201)
 await page.goto('/connexion')
 await page.getByLabel('Adresse courriel').fill(email)
 await page.getByLabel('Mot de passe',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Se connecter',exact:true}).click()
 await page.locator('.sidebar').getByRole('button',{name:'Applications',exact:true}).click()
 await expect(page.getByText('Paiements connectés',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Créer une application',exact:true}).click()
 const studio=page.getByRole('dialog')
 await studio.getByLabel('Nom de l’application',{exact:true}).fill('Contrôles documentaires')
 await studio.getByLabel('Libellé',{exact:true}).fill('Référence contrôle')
 await studio.getByRole('button',{name:'Créer mon application',exact:true}).click()
 await expect(studio).not.toBeVisible()
 await page.screenshot({path:'test-results/applications.png',fullPage:true})
 await page.locator('.sidebar').getByRole('button',{name:'Contrôles documentaires',exact:true}).click()
 await page.getByRole('button',{name:'Nouvelle fiche',exact:true}).click()
 await page.getByRole('dialog').getByLabel(/Référence contrôle/).fill('CONTROLE-001')
 await page.getByRole('dialog').getByRole('button',{name:'Enregistrer',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await expect(page.getByText('CONTROLE-001',{exact:true})).toBeVisible()
 await page.reload()
 await expect(page.getByText('CONTROLE-001',{exact:true})).toBeVisible()
})

test('Personnel : créer, soumettre et approuver un congé',async({page,request})=>{
 const email=`personnel-${Date.now()}@example.test`,password='Personnel-Recette-459!'
 const result=await request.post('/api/v2/auth/register',{data:{name:'Direction Personnel',email,password,organization:{name:'Transport Personnel',country:'GN',currency:'GNF',timezone:'Africa/Conakry',activities:['freight']}}})
 expect(result.status()).toBe(201)
 const auth=await result.json(),headers={Authorization:'Bearer '+auth.access,'X-Organization':auth.organizations[0].id}
 const employeeResponse=await request.post('/api/v2/employees',{headers,data:{name:'Chauffeur congés'}})
 expect(employeeResponse.status()).toBe(201)
 const employee=await employeeResponse.json()
 await page.goto('/connexion')
 await page.getByLabel('Adresse courriel').fill(email)
 await page.getByLabel('Mot de passe',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Se connecter',exact:true}).click()
 await page.locator('.sidebar').getByRole('button',{name:'Congés & absences',exact:true}).click()
 await page.getByRole('button',{name:'Nouveau',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByLabel(/^Salarié/).selectOption(employee.id)
 await dialog.getByLabel(/^Début/).fill('2027-01-10')
 await dialog.getByLabel(/^Fin incluse/).fill('2027-01-15')
 await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click()
 await expect(dialog).not.toBeVisible()
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'Soumettre',exact:true}).click()
 await expect(page.locator('tbody .status')).toHaveText('À approuver')
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'Valider',exact:true}).click()
 await expect(page.locator('tbody .status')).toHaveText('Approuvé')
 await page.reload()
 await expect(page.locator('tbody .status')).toHaveText('Approuvé')
 await page.screenshot({path:'test-results/personnel.png',fullPage:true})
})
