// Auteur : Jonathan Kakesa (JonathanK-N).
import {test,expect} from '@playwright/test'

test('Accueil réel, inscription, flotte, session et sortie',async({page})=>{
 const errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByRole('heading',{name:/Votre transport/})).toBeVisible()
 await expect(page.locator('.hero img').first()).toBeVisible()
 await page.screenshot({path:'test-results/accueil.png',fullPage:true})
 await page.goto('/commencer')
 const suffix=Date.now()
 await page.getByLabel('Votre nom complet').fill('Jonathan Recette')
 await page.getByLabel('Adresse courriel').fill(`recette-${suffix}@example.test`)
 await page.getByLabel('Mot de passe',{exact:true}).fill('Recette-Transport-493!')
 await page.getByLabel('Nom de l’entreprise').fill(`Transport Recette ${suffix}`)
 await page.getByRole('button',{name:'Créer mon entreprise'}).click()
 await expect(page.locator('.workspace')).toBeVisible()
 await expect(page.getByRole('heading',{name:'Vue d’ensemble'})).toBeVisible()
 await page.screenshot({path:'test-results/espace-entreprise.png',fullPage:true})
 await page.getByRole('button',{name:'Flotte',exact:true}).click()
 await page.getByRole('button',{name:'Nouveau',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByLabel('Immatriculation').fill('RC-TEST-001')
 await dialog.getByLabel('Marque / modèle').fill('Mercedes Actros')
 await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.getByText('RC-TEST-001')).toBeVisible()
 await page.reload()
 await expect(page.locator('.workspace')).toBeVisible()
 await expect(page.getByText('RC-TEST-001')).toBeVisible()
 await page.getByTitle('Se déconnecter').click()
 await expect(page.getByRole('button',{name:'Se connecter',exact:true})).toBeVisible()
 await page.goto('/app')
 await expect(page.getByRole('button',{name:'Se connecter',exact:true})).toBeVisible()
 expect(errors).toEqual([])
})

test('Accueil mobile sans débordement',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await expect(page.getByRole('heading',{name:/Votre transport/})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.screenshot({path:'test-results/accueil-mobile.png',fullPage:true})
})

test('Facture émise dans le navigateur et entreprise indépendante',async({page,request})=>{
 const suffix=Date.now(),password='Recette-Finance-392!'
 async function register(label:string,country:string,currency:string){
  const email=`${label}-${suffix}@example.test`
  const response=await request.post('/api/v2/auth/register',{data:{name:'Direction '+label,email,password,organization:{name:'Transport '+label,country,currency,timezone:'Africa/Conakry',activities:['freight']}}})
  expect(response.status()).toBe(201)
  const data=await response.json()
  return {email,headers:{Authorization:'Bearer '+data.access,'X-Organization':data.organizations[0].id}}
 }
 const a=await register('Guinee','GN','GNF'),b=await register('Cameroun','CM','XAF')
 const customerResponse=await request.post('/api/v2/partners',{headers:a.headers,data:{name:'Client recette facturation'}})
 expect(customerResponse.status()).toBe(201)
 const customer=await customerResponse.json()
 await page.goto('/connexion')
 await page.getByLabel('Adresse courriel').fill(a.email)
 await page.getByLabel('Mot de passe',{exact:true}).fill(password)
 await page.getByRole('button',{name:'Se connecter',exact:true}).click()
 await expect(page.locator('.workspace')).toBeVisible()
 await page.locator('.sidebar').getByRole('button',{name:'Facturation',exact:true}).click()
 await page.getByRole('button',{name:'Nouveau',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByRole('combobox',{name:/Client/}).selectOption(customer.id)
 await dialog.getByLabel(/^Date/).fill('2026-09-26')
 await dialog.getByLabel(/^Échéance/).fill('2026-10-26')
 await dialog.getByLabel('Description',{exact:true}).fill('Conakry — Kindia')
 await dialog.getByLabel('Prix unitaire',{exact:true}).fill('100')
 await dialog.getByLabel('Taxe (%)',{exact:true}).fill('18')
 await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click()
 await expect(dialog).not.toBeVisible()
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'Émettre',exact:true}).click()
 await expect(page.locator('tbody .status')).toHaveText('Émise')
 const invoices=await (await request.get('/api/v2/invoices',{headers:a.headers})).json()
 expect(invoices.results[0].total).toBe('118.00')
 const forbidden=await request.get('/api/v2/invoices/'+invoices.results[0].id,{headers:b.headers})
 expect(forbidden.status()).toBe(404)
 const isolated=await (await request.get('/api/v2/invoices',{headers:b.headers})).json()
 expect(isolated.count).toBe(0)
 await page.screenshot({path:'test-results/facturation.png',fullPage:true})
})
