import {test,expect} from '@playwright/test'

test.use({actionTimeout:20000})

test('GPS obligatoire : deux sessions Leaflet, navigation, offline, permissions et fin de mission',async({browser,request},info)=>{
 test.setTimeout(240000)
 const stamp=Date.now()+'-'+info.project.name,password='Gps-Recette-938!',email='gps-owner-'+stamp+'@example.test',driverEmail='gps-driver-'+stamp+'@example.test'
 const register=async(address:string,invitation='')=>{const r=await request.post('/api/v2/auth/register',{data:{name:address===email?'Direction GPS TEST':'Chauffeur GPS TEST',email:address,password,invitation,organization:{name:'TEST GPS '+stamp,country:'GN',currency:'USD',timezone:'America/Toronto',activities:['freight']}}});expect(r.status(),await r.text()).toBe(201);return r.json()}
 const owner=await register(email),org=owner.organizations[0].id,headers={Authorization:'Bearer '+owner.access,'X-Organization':org}
 const post=async(path:string,data:any)=>{const r=await request.post('/api/v2/'+path,{headers,data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
 const invitation=await post('team',{email:driverEmail,role:'driver'}),driver=await register(driverEmail,new URL(invitation.link).searchParams.get('invitation')!)
 const other=await register('gps-other-'+stamp+'@example.test'),otherOrg=other.organizations[0].id,otherHeaders={Authorization:'Bearer '+other.access,'X-Organization':otherOrg}
 const secondInvite=await request.post('/api/v2/team',{headers:otherHeaders,data:{email:driverEmail,role:'driver'}});expect(secondInvite.status(),await secondInvite.text()).toBe(201)
 const accepted=await request.post('/api/v2/invitation/accept',{headers:{Authorization:'Bearer '+driver.access},data:{token:new URL((await secondInvite.json()).link).searchParams.get('invitation')}});expect(accepted.status(),await accepted.text()).toBe(200)
 const employee=(await (await request.get('/api/v2/employees',{headers})).json()).results.find((e:any)=>e.user===driver.user.id);expect(employee).toBeTruthy();await request.patch('/api/v2/employees/'+employee.id,{headers,data:{active:true}})
 const vehicle=await post('vehicles',{plate:'GPS-'+stamp,name:'Camion GPS TEST',capacity:20,capacity_unit:'t'})
 const mission=await post('missions',{reference:'GPS-'+stamp,vehicle:vehicle.id,driver:employee.id,origin:'Sherbrooke',destination:'Montréal',departure:new Date(Date.now()+60000).toISOString(),arrival:new Date(Date.now()+7200000).toISOString()})
 const baseURL=process.env.TF_TEST_URL||'http://127.0.0.1:8000',a=await browser.newContext({baseURL,viewport:{width:1360,height:900}}),b=await browser.newContext({...info.project.use,baseURL,permissions:['geolocation'],geolocation:{latitude:45.4042,longitude:-71.8929,accuracy:12}} as any),admin=await a.newPage(),phone=await b.newPage()
 await a.addInitScript(()=>{const original=Date.now.bind(Date);Date.now=()=>original()-300000})
 const errors:string[]=[],events:any[]=[];for(const page of [admin,phone])page.on('pageerror',e=>errors.push(e.message))
 admin.on('websocket',ws=>ws.on('framereceived',e=>{try{events.push(JSON.parse(String(e.payload)))}catch{}}))
 await a.route('https://tile.openstreetmap.org/**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/58BAwAI/AL+XJ/PAAAAAElFTkSuQmCC','base64')}))
 await b.route('https://tile.openstreetmap.org/**',r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/58BAwAI/AL+XJ/PAAAAAElFTkSuQmCC','base64')}))
 await b.addInitScript(()=>{const w=window as any,native=navigator.geolocation,measured=(p:GeolocationPosition)=>({coords:p.coords,timestamp:p.timestamp>Date.now()*10?p.timestamp/1000:p.timestamp});w.gpsTest={watch:null,error:null,cleared:0,currentCalls:0,initial:true,nativeCurrent:(success:any,error:any)=>{let retries=0;const read=()=>native.getCurrentPosition(p=>success(measured(p)),e=>{if(e.code===2&&retries++<20)setTimeout(read,100);else error(new Error('GPS natif '+e.code+': '+e.message))},{enableHighAccuracy:true,maximumAge:5000,timeout:10000});read()},permission:{state:'denied',onchange:null}};Object.defineProperty(navigator,'geolocation',{value:{watchPosition:(success:any,error:any,options:any)=>{w.gpsTest.watch=success;w.gpsTest.error=error;return native.watchPosition(p=>{if(!w.gpsTest.initial)success(measured(p))},e=>{if(e.code!==2)error(e)},options)},clearWatch:(id:number)=>{native.clearWatch(id);w.gpsTest.watch=null;w.gpsTest.cleared++},getCurrentPosition:(success:any,error:any,options:any)=>{w.gpsTest.currentCalls++;native.getCurrentPosition(p=>success(measured(p)),error,options)}}});Object.defineProperty(navigator,'permissions',{value:{query:async()=>w.gpsTest.permission}})})
 await b.addInitScript(()=>{const w=window as any;w.gpsWake={active:0,requests:0};Object.defineProperty(navigator,'wakeLock',{value:{request:async()=>{w.gpsWake.requests++;await new Promise(r=>setTimeout(r,20));const held={released:false,release:async()=>{if(!held.released){held.released=true;w.gpsWake.active--}}};w.gpsWake.active++;return held}}})})
 async function login(page:any,address:string){await page.goto('/connexion');await page.getByLabel('Adresse courriel').fill(address);await page.getByLabel('Mot de passe',{exact:true}).fill(password);await page.getByRole('button',{name:'Se connecter',exact:true}).click();await expect(page.locator('.workspace')).toBeVisible()}
 async function navigate(page:any,name:string){if((page.viewportSize()?.width||1280)<=600)await page.getByRole('navigation',{name:'Navigation mobile'}).getByRole('button',{name:'Plus',exact:true}).click();else if((page.viewportSize()?.width||1280)<=900)await page.getByRole('button',{name:'Menu',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name,exact:true}).click()}
 async function switchCompany(id:string){const width=phone.viewportSize()?.width||1280;if(width<=600)await phone.getByRole('navigation',{name:'Navigation mobile'}).getByRole('button',{name:'Plus',exact:true}).click();else if(width<=900)await phone.getByRole('button',{name:'Menu',exact:true}).click();await phone.getByLabel('Entreprise active').selectOption(id);await expect.poll(()=>phone.evaluate(()=>sessionStorage.getItem('transitflow.organization'))).toBe(id);await expect(phone.locator('.workspace')).toBeVisible();const close=phone.getByRole('button',{name:'Fermer le menu',exact:true});if(await close.isVisible())await close.click()}
 async function emit(lng:number){await phone.evaluate(()=>{(window as any).gpsTest.initial=false});await b.setGeolocation({latitude:45.4042,longitude:lng,accuracy:12});await phone.evaluate((longitude:number)=>new Promise<void>((resolve,reject)=>{const t=(window as any).gpsTest;let retries=0;const read=()=>t.nativeCurrent((point:any)=>{if(Math.abs(point.coords.longitude-longitude)>0.000001){if(retries++<20)setTimeout(read,100);else reject(new Error('Ancienne mesure native'));return}t.watch?.(point);resolve()},reject);read()}),lng)}
 const positions=async()=> (await (await request.get('/api/v2/missions/'+mission.id+'/positions',{headers})).json()).positions
 try{
  await login(admin,email);await navigate(admin,'Suivi en direct');await expect(admin.getByTestId('tracking-map')).toBeVisible()
  await login(phone,driverEmail);expect(await phone.evaluate(()=>(window as any).gpsTest.watch)).toBeNull()
  await post('missions/'+mission.id+'/actions/start',{})
  await expect(phone.getByTestId('driver-tracking')).toContainText('Localisation requise')
  expect(await phone.evaluate(()=>(window as any).gpsTest.watch)).toBeNull()
  expect((await positions()).length).toBe(0)
  await expect(admin.locator(`[data-mission="${mission.id}"] [data-state]`)).toHaveAttribute('data-state','permission_required')
  await phone.evaluate(()=>{const t=(window as any).gpsTest;t.permission.state='prompt'})
  await phone.getByRole('button',{name:'Autoriser la localisation',exact:true}).click()
  await expect(phone.getByTestId('driver-tracking')).toContainText('Suivi GPS actif')
  await expect.poll(()=>phone.evaluate(()=>!!(window as any).gpsTest.watch)).toBe(true)
  expect(await phone.getByRole('button',{name:/arrêter|désactiver|pause/i}).count()).toBe(0);await expect.poll(()=>phone.evaluate(()=>(window as any).gpsWake.active)).toBe(1)
  expect(await phone.locator('.sidebar').getByRole('button',{name:'Suivi en direct',exact:true}).count()).toBe(0)
  await phone.waitForTimeout(16000);expect(await phone.evaluate(()=>(window as any).gpsTest.currentCalls)).toBeGreaterThan(0);await emit(-71.8929);await expect.poll(async()=> (await positions()).length).toBe(1)
  const card=admin.locator(`[data-mission="${mission.id}"]`);await expect(card).toContainText('-71.892900');await expect(card.locator('[data-state]')).toHaveAttribute('data-state','online')
  await expect(admin.locator('.leaflet-control-attribution')).toContainText('OpenStreetMap');expect(events.some(e=>e.type==='tracking')).toBeTruthy()
  await admin.evaluate(()=>{(window as any).gpsMapElement=document.querySelector('.leaflet-container');(window as any).gpsMarkerElement=document.querySelector('.leaflet-overlay-pane path')})
  await navigate(phone,'Terrain & notifications');await switchCompany(otherOrg);await expect(phone.getByTestId('driver-tracking')).toContainText('TEST GPS '+stamp);expect(await phone.evaluate(()=>!!(window as any).gpsTest.watch)).toBe(true)
  await phone.waitForTimeout(10500);await emit(-71.8939);await expect(card).toContainText('-71.893900')
  expect(await admin.evaluate(()=>document.querySelector('.leaflet-container')===(window as any).gpsMapElement)).toBe(true)
  expect(await admin.evaluate(()=>document.querySelector('.leaflet-overlay-pane path')===(window as any).gpsMarkerElement)).toBe(true)
  await b.setOffline(true);await phone.waitForTimeout(10500);await emit(-71.8949);await phone.waitForTimeout(10500);await emit(-71.8959)
  await phone.waitForTimeout(26000);await expect(card.locator('[data-state]')).toHaveAttribute('data-state','recent');await expect(phone.getByTestId('driver-tracking')).toContainText('Hors connexion — suivi GPS actif');await expect(phone.getByTestId('driver-tracking')).toContainText('2 positions en attente')
  await expect(card).toContainText('-71.893900');await b.setOffline(false);await expect.poll(async()=> (await positions()).length).toBe(4);await expect(card).toContainText('-71.895900');await expect(phone.getByTestId('driver-tracking')).not.toContainText('positions en attente')
  await phone.evaluate(()=>{const t=(window as any).gpsTest;t.permission.state='denied';t.permission.onchange?.();t.error?.({code:1})})
  await expect(phone.getByTestId('driver-tracking')).toContainText('Suivi GPS interrompu');await expect.poll(()=>phone.evaluate(()=>(window as any).gpsWake.active)).toBe(0);await expect(card.locator('[data-state]')).toHaveAttribute('data-state','permission_required');expect((await positions()).length).toBe(4);await expect(card).toContainText('-71.895900')
  await phone.evaluate(()=>{const t=(window as any).gpsTest;t.permission.state='granted';t.permission.onchange?.();Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'))});await expect.poll(()=>phone.evaluate(()=>!!(window as any).gpsTest.watch)).toBe(true)
  await expect.poll(()=>phone.evaluate(()=>(window as any).gpsWake.active)).toBe(1);await phone.waitForTimeout(10500);await emit(-71.8969);await expect(card.locator('[data-state]')).toHaveAttribute('data-state','online')
  await phone.evaluate(()=>{(window as any).gpsTest.error({code:2})});await expect(card.locator('[data-state]')).toHaveAttribute('data-state','unavailable');await expect(card).toContainText('-71.896900');await phone.waitForTimeout(10500);await emit(-71.8979);await expect(card.locator('[data-state]')).toHaveAttribute('data-state','online')
  expect(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  if(info.project.name==='small'){await phone.setViewportSize({width:360,height:740});expect(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
  await phone.screenshot({path:info.outputPath('gps-driver-'+info.project.name+'.png'),fullPage:true});await admin.screenshot({path:info.outputPath('gps-fleet-'+info.project.name+'.png')})
  await switchCompany(org);await navigate(phone,'Missions');await phone.getByRole('button',{name:'Terminer',exact:true}).first().click();const dialog=phone.getByRole('dialog',{name:'Terminer la mission'});await dialog.getByRole('button',{name:'Clôturer la mission',exact:true}).click();await expect(dialog).toHaveCount(0)
  await expect(phone.getByTestId('driver-tracking')).toHaveCount(0);await expect.poll(()=>phone.evaluate(()=>(window as any).gpsWake.active)).toBe(0);await expect.poll(()=>phone.evaluate(()=>(window as any).gpsTest.watch)).toBeNull();const finished=(await positions()).length;await emit(-71.99);await phone.waitForTimeout(1000);expect((await positions()).length).toBe(finished)
  await expect(card).toHaveCount(0)
  await navigate(admin,'Missions');await admin.locator('tbody tr').filter({hasText:mission.reference}).locator('.record-link').click();await expect(admin.getByRole('heading',{name:'Parcours GPS réel'})).toBeVisible();await expect(admin.locator('.tracking-panel .leaflet-overlay-pane path')).toHaveCount(3)
  await phone.evaluate(async([user,org,mission,prior])=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('transitflow-mission-gps',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise<void>((resolve,reject)=>{const tx=db.transaction('points','readwrite');for(const timestamp of [prior.timestamp,new Date(Date.now()+1000).toISOString()]){const id=crypto.randomUUID();tx.objectStore('points').put({key:id,user,organization:org,mission,point:{...prior,client_id:id,timestamp}})}tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();window.dispatchEvent(new Event('online'))},[driver.user.id,org,mission.id,(await positions())[0]])
  await expect.poll(()=>phone.evaluate(()=>new Promise<number>((resolve,reject)=>{const r=indexedDB.open('transitflow-mission-gps',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('points').objectStore('points').count();q.onsuccess=()=>{resolve(q.result);db.close()};q.onerror=()=>reject(q.error)}}))).toBe(0)
  expect((await positions()).length).toBe(finished)
  expect(errors).toEqual([])
 }finally{await a.close();await b.close()}
})
