<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,computed,onMounted} from 'vue'
import {Truck,Route,Bus,Wrench,Package,Wallet,FileText,CreditCard,Plus,ArrowUpRight,Check,Search,Settings2,Layers3,X,ChevronUp,ChevronDown,Trash2,LoaderCircle,Users,CalendarDays,Folder} from 'lucide-vue-next'
import {api} from './api'
const emit=defineEmits(['changed','open'])
const store=ref<any>({applications:[],custom:[],admin:false}),query=ref(''),category=ref('Toutes'),loading=ref(true),busy=ref(''),error=ref(''),notice=ref('')
const studio=ref(false),editing=ref<any>(null),saving=ref(false),studioError=ref('')
const form=ref<any>({name:'',description:'',icon:'folder',color:'green',fields:[],read_roles:[],write_roles:[]})
const icons:Record<string,any>={truck:Truck,route:Route,bus:Bus,wrench:Wrench,package:Package,wallet:Wallet,file:FileText,'credit-card':CreditCard,folder:Folder,users:Users,calendar:CalendarDays}
const roles=[['operations','Exploitation'],['finance','Finance'],['workshop','Atelier'],['driver','Chauffeurs'],['viewer','Lecture seule']]
const categories=['Toutes','Exploitation','Gestion','Collaboration','Connexions','Mes applications']
const types=[['text','Texte court'],['textarea','Texte long'],['number','Nombre'],['date','Date'],['checkbox','Oui / non'],['select','Liste de choix'],['email','Courriel']]
const visible=computed(()=>store.value.applications.filter((a:any)=>(category.value==='Toutes'||a.category===category.value)&&a.name.toLowerCase().includes(query.value.toLowerCase())))
const custom=computed(()=>store.value.custom.filter((a:any)=>(category.value==='Toutes'||category.value==='Mes applications')&&a.name.toLowerCase().includes(query.value.toLowerCase())))
async function load(){loading.value=true;try{store.value=await api('applications')}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function toggle(app:any){
 if(app.installed&&!confirm(`Désactiver ${app.name} ? Vos données seront conservées.`))return
 busy.value=app.key;error.value=''
 try{store.value=await api('applications','POST',{key:app.key,enabled:!app.installed});notice.value=app.installed?'Application désactivée. Données conservées.':app.pending?'Application ajoutée. Les connexions partenaires restent en attente.':'Application installée avec ses dépendances.';emit('changed')}catch(e:any){error.value=e.message}finally{busy.value=''}
}
function edit(app:any=null){editing.value=app;studioError.value='';form.value=app?JSON.parse(JSON.stringify(app)):{name:'',description:'',icon:'folder',color:'green',fields:[{key:'title',label:'Libellé',type:'text',required:true,options:[]}],read_roles:['operations'],write_roles:['operations']};studio.value=true}
function addField(){form.value.fields.push({key:'field_'+crypto.randomUUID().replaceAll('-','').slice(0,12),label:'',type:'text',required:false,options:[]})}
function move(index:number,direction:number){const target=index+direction;if(target<0||target>=form.value.fields.length)return;[form.value.fields[index],form.value.fields[target]]=[form.value.fields[target],form.value.fields[index]]}
function access(role:string){return form.value.write_roles.includes(role)?'write':form.value.read_roles.includes(role)?'read':'none'}
function setAccess(role:string,value:string){form.value.read_roles=form.value.read_roles.filter((r:string)=>r!==role);form.value.write_roles=form.value.write_roles.filter((r:string)=>r!==role);if(value!=='none')form.value.read_roles.push(role);if(value==='write')form.value.write_roles.push(role)}
async function save(){saving.value=true;studioError.value='';try{await api('applications/custom'+(editing.value?'/'+editing.value.id:''),editing.value?'PATCH':'POST',form.value);studio.value=false;notice.value='Votre application est prête.';await load();emit('changed')}catch(e:any){studioError.value=e.message}finally{saving.value=false}}
async function toggleCustom(app:any){if(app.enabled&&!confirm(`Désactiver ${app.name} en conservant ses fiches ?`))return;try{await api('applications/custom/'+app.id,'PATCH',{enabled:!app.enabled});await load();emit('changed')}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template>
 <section class="applications-page">
  <div class="apps-intro"><div><span class="eyebrow">UN ERP À VOTRE MESURE</span><h2>Les bons outils.<br>Pour votre entreprise.</h2><p>Composez votre espace de travail. Activez les applications utiles à votre activité et créez vos propres outils internes.</p></div><div class="apps-intro-art" aria-hidden="true"><Layers3 :size="48"/><span>Votre entreprise</span><div><Truck/><Wallet/><Users/></div></div></div>
  <div v-if="error" class="error-box" role="alert">{{error}}</div><div v-if="notice" class="info-box" role="status">{{notice}}</div>
  <div class="apps-toolbar"><div class="search-box"><Search :size="18"/><input v-model="query" type="search" aria-label="Rechercher une application" placeholder="Rechercher une application…"/></div><button v-if="store.admin" class="primary" @click="edit()"><Plus :size="18"/>Créer une application</button></div>
  <div class="app-categories" aria-label="Catégories d’applications"><button v-for="c in categories" :class="{selected:category===c}" :aria-pressed="category===c" @click="category=c">{{c}}</button></div>
  <div v-if="loading" class="app-grid" aria-label="Chargement des applications"><div v-for="i in 6" class="app-skeleton"></div></div>
  <div v-else class="app-grid">
   <article v-for="app in visible" :key="app.key" class="application-card"><div class="app-card-top"><span class="app-icon" :class="app.category==='Connexions'?'purple':'green'"><component :is="icons[app.icon]||Layers3" :size="26"/></span><span v-if="app.installed" class="app-installed"><Check :size="13"/>Installée</span><span v-else class="muted app-category">{{app.category}}</span></div><h3>{{app.name}}</h3><p>{{app.description}}</p><div v-if="app.pending" class="app-pending">API partenaires en attente</div><footer><span v-if="app.depends.length" class="field-help">{{app.depends.length}} dépendance(s) gérée(s)</span><span v-else class="field-help">Application indépendante</span><button v-if="store.admin" :class="app.installed?'text-btn':'secondary small'" :disabled="!!busy" @click="toggle(app)"><LoaderCircle v-if="busy===app.key" :size="15" class="spin"/>{{app.installed?'Désactiver':app.pending?'Ajouter en attente':'Installer'}}<Plus v-if="!app.installed&&busy!==app.key" :size="15"/></button></footer></article>
   <article v-for="app in custom" :key="app.id" class="application-card custom"><div class="app-card-top"><span class="app-icon" :class="app.color"><component :is="icons[app.icon]||Folder" :size="26"/></span><span class="app-installed" :class="{disabled:!app.enabled}">{{app.enabled?'Application interne':'Désactivée'}}</span></div><h3>{{app.name}}</h3><p>{{app.description||'Un outil créé pour les besoins de votre entreprise.'}}</p><footer><button v-if="app.enabled" class="text-btn" @click="emit('open',app)">Ouvrir <ArrowUpRight :size="16"/></button><div v-if="store.admin" class="row-actions"><button class="icon-btn" :aria-label="'Configurer '+app.name" @click="edit(app)"><Settings2 :size="17"/></button><button class="text-btn" @click="toggleCustom(app)">{{app.enabled?'Désactiver':'Activer'}}</button></div></footer></article>
  </div><p v-if="!loading&&!visible.length&&!custom.length" class="empty-state">Aucune application ne correspond à votre recherche.</p>
  <div v-if="studio" class="modal-backdrop" @click.self="studio=false"><section class="editor studio-editor" role="dialog" aria-modal="true" aria-label="Créer ou configurer une application"><header class="editor-head"><div><span class="eyebrow">STUDIO TRANSITFLOW</span><h2>{{editing?'Configurer l’application':'Votre nouvelle application'}}</h2></div><button class="icon-btn" aria-label="Fermer le studio" @click="studio=false"><X/></button></header><form class="editor-body" @submit.prevent="save"><div v-if="studioError" class="error-box" role="alert">{{studioError}}</div><div class="form-grid"><label>Nom de l’application<input v-model="form.name" required maxlength="80" placeholder="Ex. Contrôles de chargement"/></label><label>Couleur<select v-model="form.color"><option value="green">Vert</option><option value="blue">Bleu</option><option value="purple">Violet</option><option value="orange">Orange</option></select></label><label class="span-2">Description<textarea v-model="form.description" maxlength="500" rows="2" placeholder="À quoi sert cette application ?"></textarea></label><label>Icône<select v-model="form.icon"><option v-for="i in [['folder','Dossier'],['truck','Transport'],['users','Équipe'],['file','Document'],['package','Colis'],['calendar','Calendrier'],['wrench','Atelier'],['wallet','Finance']]" :value="i[0]">{{i[1]}}</option></select></label></div>
   <div class="studio-section-heading"><div><h3>Les champs de vos fiches</h3><p class="field-help">Définissez les informations à recueillir. Les identifiants sont gérés automatiquement.</p></div><button type="button" class="secondary small" :disabled="form.fields.length>=30" @click="addField"><Plus :size="15"/>Ajouter un champ</button></div>
   <div class="studio-field" v-for="(field,index) in form.fields" :key="field.key"><div class="studio-field-number">{{index+1}}</div><label>Libellé<input v-model="field.label" required maxlength="80" placeholder="Ex. Numéro du bon"/></label><label>Type<select v-model="field.type"><option v-for="t in types" :value="t[0]">{{t[1]}}</option></select></label><label class="checkbox-label"><input type="checkbox" v-model="field.required"/>Obligatoire</label><div class="row-actions"><button type="button" class="icon-btn" :disabled="index===0" aria-label="Monter le champ" @click="move(index,-1)"><ChevronUp :size="16"/></button><button type="button" class="icon-btn" :disabled="index===form.fields.length-1" aria-label="Descendre le champ" @click="move(index,1)"><ChevronDown :size="16"/></button><button type="button" class="icon-btn danger-text" :disabled="form.fields.length===1" aria-label="Supprimer le champ" @click="form.fields.splice(index,1)"><Trash2 :size="16"/></button></div><label v-if="field.type==='select'" class="studio-options">Options (une par ligne)<textarea :value="field.options.join('\n')" @change="field.options=($event.target as HTMLTextAreaElement).value.split('\n').map(x=>x.trim()).filter(Boolean)" required rows="3"></textarea></label></div>
   <div class="studio-section-heading"><div><h3>Qui peut utiliser cette application ?</h3><p class="field-help">Les propriétaires et administrateurs conservent l’accès complet.</p></div></div><div class="studio-permissions"><label v-for="role in roles">{{role[1]}}<select :value="access(role[0])" @change="setAccess(role[0],($event.target as HTMLSelectElement).value)"><option value="none">Aucun accès</option><option value="read">Consulter</option><option v-if="role[0]!=='viewer'" value="write">Consulter et modifier</option></select></label></div>
   <footer class="editor-footer"><button type="button" class="secondary" @click="studio=false">Annuler</button><button class="primary" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="16"/>{{editing?'Enregistrer les modifications':'Créer mon application'}}</button></footer></form></section></div>
 </section>
</template>
