<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {Package,Truck,FileText,Folder,LogOut,Download,ChevronLeft,ChevronRight,LoaderCircle,X,Printer} from 'lucide-vue-next'
import {api,download,money} from './api'
import ClientDiscussion from './ClientDiscussion.vue'
import FinancialPreview from './FinancialPreview.vue'
const props=defineProps<{session:any,organization:any}>(),emit=defineEmits(['logout','organization'])
const section=ref('orders'),rows=ref<any[]>([]),count=ref(0),page=ref(1),loading=ref(true),error=ref(''),invoice=ref<any>(null)
const sections=[['orders','Mes commandes',Package],['deliveries','Mes livraisons',Truck],['invoices','Mes factures',FileText],['documents','Mes documents',Folder],['messages','Messages',FileText]]
const labels:Record<string,string>={received:'Commande reçue',in_progress:'En cours',delivered:'Livrée',invoiced:'Facturée',confirmed:'Confirmée',completed:'Terminée',cancelled:'Annulée',planned:'Planifiée',active:'En cours',issued:'Émise',paid:'Soldée',partial:'Partiellement payée',quote:'Devis',invoice:'Facture',credit:'Avoir'}
async function load(){if(section.value==='messages')return;loading.value=true;error.value='';try{const result=await api('portal/'+section.value+'?page='+page.value);rows.value=result.results;count.value=result.count}catch(e:any){error.value=e.message}finally{loading.value=false}}
function navigate(key:string){section.value=key;page.value=1;invoice.value=null;load()}
async function getFile(path:string,name:string){error.value='';try{await download('portal/'+path,name)}catch(e:any){error.value=e.message}}
function day(value:string){return value?new Date(value.length===10?value+'T12:00:00':value).toLocaleDateString('fr-FR'):'—'}
function print(){window.print()}
onMounted(load)
</script>
<template>
 <div class="client-portal"><header class="portal-header"><a class="brand" href="/app"><img class="brand-mark" src="/icons/icon-192.png" width="36" height="36" alt=""/>Transit<span>Flow</span><small>CLIENT</small></a><div class="portal-header-actions"><select aria-label="Prestataire actif" :value="organization.id" @change="emit('organization',($event.target as HTMLSelectElement).value)"><option v-for="org in session.organizations" :value="org.id">{{org.name}}</option></select><button class="secondary" @click="emit('logout')"><LogOut :size="16"/>Déconnexion</button></div></header>
 <main class="portal-body"><div class="portal-welcome"><span class="eyebrow">VOTRE ESPACE CLIENT PRIVÉ</span><h1>Bonjour {{session.user.name}}.</h1><p>Suivez les prestations de {{organization.name}} pour {{organization.customer}}.</p></div><nav class="portal-tabs" aria-label="Sections du portail"><button v-for="item in sections" :class="{active:section===item[0]}" @click="navigate(String(item[0]))"><component :is="item[2]" :size="18"/>{{item[1]}}</button></nav><div v-if="error" class="error-box" role="alert">{{error}}</div><ClientDiscussion v-if="section==='messages'"/><section v-else class="panel"><div v-if="loading" class="empty-state" role="status"><LoaderCircle class="spin"/>Chargement de votre espace…</div><div v-else-if="!rows.length" class="empty-state"><Folder :size="34"/><h2>Aucun élément à afficher</h2><p>Les informations publiées par votre transporteur apparaîtront ici.</p></div><div v-else class="table-wrap"><table>
 <thead><tr v-if="section==='orders'"><th>COMMANDE</th><th>TRAJET</th><th>DATE PRÉVUE</th><th>MONTANT HT</th><th>STATUT</th></tr><tr v-else-if="section==='deliveries'"><th>LIVRAISON</th><th>TRAJET</th><th>ARRIVÉE PRÉVUE</th><th>STATUT</th><th>JUSTIFICATIF</th></tr><tr v-else-if="section==='invoices'"><th>DOCUMENT</th><th>ÉCHÉANCE</th><th>TOTAL TTC</th><th>RÉGLÉ</th><th>SOLDE</th><th>STATUT</th></tr><tr v-else><th>DOCUMENT</th><th>DATE</th><th></th></tr></thead>
 <tbody><tr v-for="row in rows" :key="row.id"><template v-if="section==='orders'"><td data-label="Commande"><strong>{{row.reference}}</strong></td><td data-label="Trajet">{{row.origin}} → {{row.destination}}</td><td data-label="Date prévue">{{day(row.planned_date)}}</td><td data-label="Montant HT">{{money(row.amount,organization.currency)}}</td><td data-label="Statut"><span class="status" :class="row.status">{{labels[row.stage]||labels[row.status]}}</span></td></template><template v-else-if="section==='deliveries'"><td data-label="Livraison">{{row.reference}}</td><td data-label="Trajet">{{row.origin}} → {{row.destination}}</td><td data-label="Arrivée prévue">{{day(row.arrival)}}</td><td data-label="Statut"><span class="status" :class="row.status">{{labels[row.status]}}</span></td><td data-label="Justificatif"><button v-if="row.signed" class="text-btn" @click="getFile('receipt/'+row.id,'livraison-'+row.reference+'.pdf')"><Download :size="16"/>Livraison signée</button><span v-else>En attente</span></td></template><template v-else-if="section==='invoices'"><td data-label="Document"><button class="record-link" @click="invoice=row">{{labels[row.kind]}} {{row.number}}</button></td><td data-label="Échéance">{{day(row.due_date)}}</td><td data-label="Total TTC">{{money(row.total,organization.currency)}}</td><td data-label="Réglé">{{money(row.paid,organization.currency)}}</td><td data-label="Solde">{{money(row.balance,organization.currency)}}</td><td data-label="Statut"><span class="status" :class="row.status">{{labels[row.payment_state||row.status]}}</span></td></template><template v-else><td data-label="Document">{{row.title}}</td><td data-label="Date">{{day(row.created_at)}}</td><td data-label="Fichier"><button class="text-btn" @click="getFile('document/'+row.id,row.title)"><Download :size="16"/>Télécharger</button></td></template></tr></tbody></table></div><footer class="table-pagination"><span>{{count}} élément(s)</span><div><button class="icon-btn" aria-label="Page précédente" :disabled="page===1" @click="page--;load()"><ChevronLeft :size="18"/></button><b>{{page}}</b><button class="icon-btn" aria-label="Page suivante" :disabled="page*25>=count" @click="page++;load()"><ChevronRight :size="18"/></button></div></footer></section></main>
 <FinancialPreview v-if="invoice" :invoice="invoice" :organization="organization" :customer="invoice.customer_details||{name:organization.customer}" @close="invoice=null"/>
 </div>
</template>
<style scoped>
.client-portal{min-height:100vh;background:#f5f8f5;color:#163d36}.portal-header{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:22px 5%;background:white;border-bottom:1px solid #e2eae4}.portal-header-actions{display:flex;align-items:center;gap:14px}.portal-header-actions select{max-width:340px}.portal-body{max-width:1250px;margin:auto;padding:50px 28px}.portal-welcome h1{font-size:34px;margin:14px 0}.portal-welcome p{color:#66796d}.portal-tabs{display:flex;gap:12px;flex-wrap:wrap;margin:32px 0 20px}.portal-tabs button{display:flex;align-items:center;gap:9px;padding:13px 20px;border-radius:9px;border:1px solid #dce7df;background:white;color:#63786b}.portal-tabs button.active{background:#176d57;border-color:#176d57;color:white}.portal-notes{white-space:pre-wrap}.portal-invoice .editor-body>p,.portal-invoice .editor-body>h3{margin:14px 0}@media(max-width:700px){.portal-header{align-items:flex-start;flex-direction:column}.portal-header-actions{width:100%;flex-wrap:wrap}.portal-header-actions select{max-width:100%;flex:1}.portal-body{padding:30px 16px}.portal-tabs{gap:7px}.portal-tabs button{padding:11px;font-size:12px}}@media(max-width:700px){.table-wrap{overflow:visible}table,tbody,tr,td{display:block;width:100%;min-width:0}thead{display:none}tr{padding:12px 0;border-bottom:1px solid #dce7df}td{display:flex;justify-content:space-between;gap:16px;text-align:right;overflow-wrap:anywhere;border:0;padding:8px 12px}td::before{content:attr(data-label);font-weight:600;text-align:left;flex-shrink:0}td button{min-height:44px}.portal-invoice{max-width:100%}}@media print{.portal-header,.portal-body,.portal-print,.portal-invoice .icon-btn{display:none!important}.modal-backdrop{position:static;display:block;background:white}.portal-invoice{position:static;width:100%;height:auto;max-height:none;box-shadow:none}.portal-invoice .editor-body{overflow:visible}}
</style>
