<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue'
import {Plus,Search,ChevronLeft,ChevronRight,X,Save,Trash2,LoaderCircle,Folder} from 'lucide-vue-next'
import {api} from './api'
const props=defineProps<{application:any}>()
const rows=ref<any[]>([]),page=ref(1),count=ref(0),query=ref(''),loading=ref(true),error=ref(''),editing=ref(false),selected=ref<any>(null),data=ref<any>({}),saving=ref(false),formError=ref('')
let searchTimer:any
const endpoint=`applications/custom/${props.application.id}/records`
async function load(){loading.value=true;error.value='';try{const r=await api(endpoint+'?page='+page.value+'&q='+encodeURIComponent(query.value));rows.value=r.results;count.value=r.count}catch(e:any){error.value=e.message}finally{loading.value=false}}
function search(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page.value=1;load()},250)}
function open(row:any=null){selected.value=row;data.value=row?JSON.parse(JSON.stringify(row.data)):Object.fromEntries(props.application.fields.map((f:any)=>[f.key,f.type==='checkbox'?false:'']));formError.value='';editing.value=true}
async function save(){saving.value=true;formError.value='';try{await api(endpoint+(selected.value?'/'+selected.value.id:''),selected.value?'PATCH':'POST',{data:data.value,revision:selected.value?.revision});editing.value=false;await load()}catch(e:any){formError.value=e.message}finally{saving.value=false}}
async function remove(){if(!confirm('Supprimer cette fiche ?'))return;saving.value=true;try{await api(endpoint+'/'+selected.value.id,'DELETE',{revision:selected.value.revision});editing.value=false;await load()}catch(e:any){formError.value=e.message}finally{saving.value=false}}
function display(value:any){return value===true?'Oui':value===false?'Non':value===null||value===''||value===undefined?'—':String(value)}
onMounted(load);onUnmounted(()=>clearTimeout(searchTimer))
</script>
<template>
 <section class="custom-workspace"><div v-if="error" class="error-box" role="alert">{{error}}</div><div class="apps-toolbar"><div class="search-box"><Search :size="18"/><input v-model="query" @input="search" type="search" aria-label="Rechercher une fiche" placeholder="Rechercher une fiche…"/></div><button v-if="application.writable" class="primary" @click="open()"><Plus :size="18"/>Nouvelle fiche</button></div><section class="panel resource-panel"><div v-if="loading" class="empty-state" role="status"><LoaderCircle class="spin"/>Chargement des fiches…</div><div v-else-if="!rows.length" class="empty-state"><Folder :size="36"/><h3>{{query?'Aucun résultat':'Votre application est prête.'}}</h3><p>{{query?'Essayez un autre terme.':'Créez votre première fiche pour commencer.'}}</p></div><div v-else class="table-wrap"><table><thead><tr><th v-for="f in application.fields.slice(0,5)">{{f.label}}</th><th>MODIFICATION</th><th></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="(f,index) in application.fields.slice(0,5)"><button v-if="index===0" class="record-link" @click="open(row)">{{display(row.data[f.key])}}</button><span v-else>{{display(row.data[f.key])}}</span></td><td>{{new Date(row.updated_at).toLocaleDateString('fr-FR')}}</td><td><button class="icon-btn" aria-label="Ouvrir la fiche" @click="open(row)"><ChevronRight :size="18"/></button></td></tr></tbody></table></div><footer class="table-pagination"><span>{{count}} fiche(s)</span><div><button class="icon-btn" :disabled="page===1" aria-label="Page précédente" @click="page--;load()"><ChevronLeft :size="18"/></button><b>{{page}}</b><button class="icon-btn" :disabled="page*25>=count" aria-label="Page suivante" @click="page++;load()"><ChevronRight :size="18"/></button></div></footer></section>
 <div v-if="editing" class="modal-backdrop" @click.self="editing=false"><section class="editor" role="dialog" aria-modal="true" :aria-label="application.name"><header class="editor-head"><div><span class="eyebrow">{{application.name}}</span><h2>{{selected?selected.title:'Nouvelle fiche'}}</h2></div><button class="icon-btn" aria-label="Fermer" @click="editing=false"><X/></button></header><form class="editor-body" @submit.prevent="save"><div v-if="formError" class="error-box" role="alert">{{formError}}</div><div class="form-grid"><label v-for="f in application.fields" :class="{'span-2':f.type==='textarea','checkbox-label':f.type==='checkbox'}">{{f.label}}<span v-if="f.required" class="required">*</span><textarea v-if="f.type==='textarea'" v-model="data[f.key]" rows="4" :required="f.required" maxlength="5000" :disabled="!application.writable"></textarea><select v-else-if="f.type==='select'" v-model="data[f.key]" :required="f.required" :disabled="!application.writable"><option value="">Sélectionner</option><option v-for="value in f.options" :value="value">{{value}}</option></select><input v-else-if="f.type==='checkbox'" type="checkbox" v-model="data[f.key]" :disabled="!application.writable"/><input v-else v-model="data[f.key]" :type="f.type" :step="f.type==='number'?'any':undefined" :required="f.required" :maxlength="f.type==='text'?500:undefined" :disabled="!application.writable"/></label></div><footer class="editor-footer"><button v-if="selected&&application.writable" type="button" class="icon-btn danger-text" aria-label="Supprimer la fiche" :disabled="saving" @click="remove"><Trash2 :size="18"/></button><button class="secondary" type="button" @click="editing=false">Fermer</button><button v-if="application.writable" class="primary" :disabled="saving"><Save :size="17"/>Enregistrer</button></footer></form></section></div>
 </section>
</template>
