<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {Download,Paperclip,ChevronLeft,ChevronRight} from 'lucide-vue-next'
import {api,download} from './api'
const props=defineProps<{mission:any,canUpload:boolean}>()
const rows=ref<any[]>([]),count=ref(0),page=ref(1),title=ref(''),shared=ref(false),file=ref<File|null>(null),input=ref<HTMLInputElement|null>(null),busy=ref(false),error=ref('')
async function load(){try{const result=await api(`missions/${props.mission.id}/delivery-documents?page=${page.value}`);rows.value=result.results;count.value=result.count}catch(e:any){error.value=e.message}}
async function save(){if(!file.value)return;busy.value=true;error.value='';try{const data=new FormData();data.append('file',file.value);data.append('title',title.value);data.append('shared_with_customer',String(shared.value));await api(`missions/${props.mission.id}/delivery-documents`,'POST',data);title.value='';file.value=null;shared.value=false;if(input.value)input.value.value='';page.value=1;await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function getFile(row:any){try{await download('documents/'+row.id+'/download',row.title)}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><section class="delivery-documents"><h3><Paperclip :size="17"/>Photos et documents complémentaires</h3><p class="field-help">Ajoutez les photos de réception et les bons associés à cette mission.</p><div v-if="error" class="error-box" role="alert">{{error}}</div><ul v-if="rows.length"><li v-for="row in rows" :key="row.id"><div>{{row.title}}<small>{{row.shared_with_customer?'Partagé avec le client':'Usage interne'}}</small></div><button class="icon-btn" :aria-label="'Télécharger '+row.title" @click="getFile(row)"><Download :size="16"/></button></li></ul><div v-if="count>25" class="row-actions"><button class="icon-btn" aria-label="Documents précédents" :disabled="page===1" @click="page--;load()"><ChevronLeft :size="17"/></button><span>{{page}}</span><button class="icon-btn" aria-label="Documents suivants" :disabled="page*25>=count" @click="page++;load()"><ChevronRight :size="17"/></button></div><form v-if="canUpload" class="form-grid" @submit.prevent="save"><label class="span-2">Titre du document<input v-model="title" required maxlength="180"/></label><label class="span-2">Photo ou document (JPEG, PNG, PDF · 10 Mo)<input ref="input" type="file" accept="image/jpeg,image/png,application/pdf" required @change="file=($event.target as HTMLInputElement).files?.[0]||null"/></label><label v-if="mission.order" class="checkbox-label span-2"><input v-model="shared" type="checkbox"/>Partager ce document dans le portail du client</label><button class="secondary" :disabled="busy||!file">Ajouter le document</button></form></section></template>
<style scoped>.delivery-documents{border-top:1px solid #dce6df;margin-top:30px;padding-top:22px}.delivery-documents h3{display:flex;gap:8px;align-items:center}.delivery-documents ul{list-style:none;margin:18px 0;padding:0}.delivery-documents li{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px;border-bottom:1px solid #e7eee9;font-size:13px}.delivery-documents small{display:block;color:#7a8a80;margin-top:5px}.delivery-documents form{margin-top:20px}</style>
