<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue'
import {X,Download,RotateCcw,LoaderCircle,CheckCircle2} from 'lucide-vue-next'
import {api,download} from './api'
import DeliveryDocuments from './DeliveryDocuments.vue'
const props=defineProps<{mission:any,canSign:boolean}>(),emit=defineEmits(['close'])
const loading=ref(true),busy=ref(false),error=ref(''),receipt=ref<any>(null),consentText=ref('')
const recipient=ref(''),reservations=ref(''),consent=ref(false),signature=ref<number[][][]>([])
const drawing=ref(false),pad=ref<SVGSVGElement|null>(null)
let previousFocus:HTMLElement|null=null
function point(event:PointerEvent){const box=pad.value!.getBoundingClientRect();return [Math.max(0,Math.min(600,(event.clientX-box.left)*600/box.width)),Math.max(0,Math.min(200,(event.clientY-box.top)*200/box.height))]}
function start(event:PointerEvent){if(busy.value||receipt.value)return;pad.value?.setPointerCapture(event.pointerId);drawing.value=true;signature.value.push([point(event)])}
function move(event:PointerEvent){if(!drawing.value)return;const current=signature.value[signature.value.length-1];if(signature.value.reduce((sum,stroke)=>sum+stroke.length,0)>=4000){drawing.value=false;error.value='Signature trop détaillée. Effacez puis signez à nouveau.';return}current.push(point(event))}
function stop(){drawing.value=false;signature.value=signature.value.filter(stroke=>stroke.length>=2)}
function path(stroke:number[][]){return stroke.map((p,i)=>(i?'L':'M')+p[0]+','+p[1]).join(' ')}
async function load(){loading.value=true;try{const result=await api(`missions/${props.mission.id}/receipt`);receipt.value=result.receipt;consentText.value=result.consent}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function save(){stop();busy.value=true;error.value='';try{const result=await api(`missions/${props.mission.id}/receipt`,'POST',{recipient_name:recipient.value,reservations:reservations.value,signature:signature.value,consent:consent.value});receipt.value=result.receipt}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function pdf(){try{await download(`missions/${props.mission.id}/receipt/pdf`,`livraison-${props.mission.reference}.pdf`)}catch(e:any){error.value=e.message}}
function keyboard(event:KeyboardEvent){if(event.key==='Escape'&&!busy.value)emit('close');if(event.key==='Tab'){const controls=Array.from(document.querySelectorAll<HTMLElement>('.receipt-editor button:not(:disabled),.receipt-editor input:not(:disabled),.receipt-editor textarea:not(:disabled)'));const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}
onMounted(()=>{previousFocus=document.activeElement as HTMLElement;document.addEventListener('keydown',keyboard);document.querySelector<HTMLButtonElement>('.receipt-editor button')?.focus();load()})
onUnmounted(()=>{document.removeEventListener('keydown',keyboard);previousFocus?.focus()})
</script>
<template>
 <div class="modal-backdrop" @click.self="!busy&&emit('close')"><section class="editor receipt-editor" role="dialog" aria-modal="true" aria-label="Justificatif de livraison"><header class="editor-head"><div><span class="eyebrow">{{mission.reference}}</span><h2>Justificatif de livraison</h2></div><button class="icon-btn" aria-label="Fermer" :disabled="busy" @click="emit('close')"><X/></button></header>
 <div class="editor-body"><div v-if="error" class="error-box" role="alert">{{error}}</div><div v-if="loading" role="status"><LoaderCircle class="spin"/>Chargement du justificatif…</div>
 <template v-else-if="receipt"><div class="receipt-confirmed"><CheckCircle2/><div><strong>Livraison signée</strong><p>{{receipt.recipient_name}} · {{new Date(receipt.signed_at).toLocaleString('fr-FR')}}</p></div></div><dl class="receipt-summary"><dt>Trajet</dt><dd>{{receipt.snapshot.origin}} → {{receipt.snapshot.destination}}</dd><dt>Quantité livrée</dt><dd>{{receipt.snapshot.delivered_quantity}} {{receipt.snapshot.unit}}</dd><dt>Réserves</dt><dd>{{receipt.reservations||'Aucune réserve indiquée.'}}</dd></dl><svg class="signature-pad recorded" viewBox="0 0 600 200" role="img" aria-label="Signature enregistrée du destinataire"><path v-for="stroke in receipt.signature" :d="path(stroke)"/></svg><p class="field-help">Le justificatif signé conserve les informations de la livraison et ne peut plus être modifié.</p><button class="primary" @click="pdf"><Download :size="17"/>Télécharger le justificatif PDF</button></template>
 <form v-else-if="canSign&&mission.status==='completed'" @submit.prevent="save"><p>Présentez le bilan au destinataire avant de recueillir son accord et sa signature.</p><dl class="receipt-summary"><dt>Trajet</dt><dd>{{mission.origin}} → {{mission.destination}}</dd><dt>Quantité livrée</dt><dd>{{mission.delivered_quantity}}</dd><dt>Bilan du chauffeur</dt><dd>{{mission.delivery_note||'Aucune réserve indiquée.'}}</dd></dl><div class="form-grid"><label class="span-2">Nom du destinataire<input v-model="recipient" required minlength="2" maxlength="150" autocomplete="name"/></label><label class="span-2">Réserves du destinataire<textarea v-model="reservations" rows="4" maxlength="5000" placeholder="État de la marchandise, écart ou observation…"></textarea></label></div><div class="signature-heading"><h3>Signature du destinataire</h3><button type="button" class="text-btn" @click="signature=[]"><RotateCcw :size="15"/>Effacer</button></div><p class="field-help">Tracez la signature au doigt, au stylet ou à la souris dans le cadre.</p><svg ref="pad" class="signature-pad" viewBox="0 0 600 200" aria-label="Cadre de signature du destinataire" role="img" @pointerdown.prevent="start" @pointermove.prevent="move" @pointerup="stop" @pointercancel="stop" @lostpointercapture="stop"><path v-for="stroke in signature" :d="path(stroke)"/></svg><label class="checkbox-label receipt-consent"><input v-model="consent" type="checkbox" required/>{{consentText}}</label><p class="field-help">La signature est conservée avec le justificatif. Après confirmation, son contenu est verrouillé.</p><footer class="editor-footer"><button type="button" class="secondary" :disabled="busy" @click="emit('close')">Annuler</button><button class="primary" :disabled="busy||!signature.length||!consent"><LoaderCircle v-if="busy" class="spin" :size="17"/>Confirmer la signature</button></footer></form>
 <p v-else>Aucun justificatif signé n’a encore été enregistré pour cette livraison.</p><DeliveryDocuments v-if="!loading" :mission="mission" :canUpload="canSign"/></div></section></div>
</template>
<style scoped>
.signature-pad{display:block;width:100%;height:auto;aspect-ratio:3;border:1px dashed #9eb8a9;border-radius:10px;background:#fcfdfb;touch-action:none;margin:14px 0;cursor:crosshair}.signature-pad path{fill:none;stroke:#173f38;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.signature-pad.recorded{cursor:default}.signature-heading{display:flex;align-items:center;justify-content:space-between;margin-top:24px}.receipt-consent{align-items:flex-start;line-height:1.7;margin:20px 0}.receipt-summary{display:grid;grid-template-columns:135px 1fr;gap:12px;padding:20px;background:#f3f7f3;border-radius:10px;margin:20px 0;font-size:13px}.receipt-summary dt{color:#697b70}.receipt-summary dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.receipt-confirmed{display:flex;gap:12px;color:#16785d;background:#edf7f0;border-radius:10px;padding:18px}.receipt-confirmed p{margin-top:6px}@media(max-width:600px){.receipt-summary{grid-template-columns:1fr;gap:6px}.receipt-summary dd{margin-bottom:10px}}
</style>
