<script setup lang="ts">
import {ref,computed,onUnmounted,watch} from 'vue'
import {api} from './api'
const props=defineProps<{initial:any,currency:string}>()
const data=ref(props.initial),start=ref(props.initial.start),end=ref(props.initial.end),error=ref(''),busy=ref(false)
const metrics=computed(()=>Object.entries(data.value.current as Record<string,string|number|null>).map(([key,value])=>({key,value})))
let alive=true,generation=0
watch(()=>props.initial,value=>{if(value){generation++;data.value=value;start.value=value.start;end.value=value.end;busy.value=false;error.value=''}})
const labels:any={revenue_ht:'Chiffre d’affaires HT',receipts:'Encaissements clients',approved_expenses:'Dépenses validées',completed_missions:'Missions terminées',commercial_margin:'Marge commerciale',quotes_sent:'Devis envoyés',quotes_accepted:'Devis acceptés',quote_acceptance_rate:'Acceptation des devis',orders:'Commandes prévues',missions:'Missions prévues',completion_rate:'Réalisation des missions',late_missions:'Missions en retard',vehicles_used:'Véhicules mobilisés',incidents:'Incidents survenus',maintenance:'Interventions prévues'}
const money=(value:any)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:props.currency,maximumFractionDigits:2}).format(value||0)
function metric(key:string,value:any,change=false){if(value===null||value===undefined)return 'Non calculable';const unit=data.value.units?.[key]||(key==='completed_missions'?'count':'money');return unit==='money'?money(value):unit==='percent'?Number(value).toLocaleString('fr-FR',{maximumFractionDigits:2})+(change?' points':' %'):Number(value).toLocaleString('fr-FR')}
async function reload(){const version=++generation;busy.value=true;error.value='';try{const result=await api('dashboard?'+new URLSearchParams({start:start.value,end:end.value}));if(alive&&version===generation){if(!result.direction)throw new Error('Cette synthèse n’est plus accessible.');data.value=result.direction}}catch(e:any){if(alive&&version===generation)error.value=e.message}finally{if(alive&&version===generation)busy.value=false}}
onUnmounted(()=>{alive=false;generation++})
</script>
<template><section class="direction-dashboard" aria-label="Tableau de bord Direction"><header><div><h2>Pilotage de l’entreprise</h2><p>Fuseau {{data.timezone}} · comparaison avec {{data.previous_start}} → {{data.previous_end}}</p></div><form @submit.prevent="reload"><label>Début<input v-model="start" type="date" required/></label><label>Fin<input v-model="end" type="date" required/></label><button class="primary" :disabled="busy">{{busy?'Actualisation…':'Appliquer la période'}}</button></form></header><p v-if="error" class="error-box" role="alert">{{error}}</p><div class="direction-cards"><article v-for="{key,value} in metrics" :key="key" class="stat-card"><template v-if="value!==null"><span>{{labels[key]}}</span><strong>{{metric(key,value)}}</strong><small>Précédent : {{metric(key,data.previous[key])}}</small><small>Écart : {{Number(data.changes[key])>0?'+':''}}{{metric(key,data.changes[key],true)}}</small><p>{{data.definitions[key]}}</p></template><template v-else><span>{{labels[key]}}</span><p>Aucune base de calcul, module ou accès indisponible.</p></template></article></div><section v-if="data.fleet_now" class="panel direction-balances"><h2>Disponibilité actuelle</h2><p>{{data.fleet_now.available}} véhicule(s) disponible(s) pour les {{data.fleet_now.window_minutes}} prochaines minutes, selon les mêmes règles de planning et d’atelier que le Centre. Cette situation ne constitue pas un historique de disponibilité.</p></section><section v-if="data.top_clients?.length" class="panel direction-balances"><h2>Principaux clients de la période</h2><p>Chiffre d’affaires HT net des avoirs, selon les dates des documents émis. Les devis et brouillons sont exclus.</p><dl><template v-for="(client,index) in data.top_clients" :key="index"><dt>{{client.name}}</dt><dd>{{money(client.revenue_ht)}}</dd></template></dl></section><section class="panel direction-balances direction-receivables"><h2>Créances actuelles</h2><p>Ces soldes correspondent à la situation actuelle, indépendamment de la période choisie.</p><dl><dt>À encaisser</dt><dd>{{money(data.receivable_now)}}</dd><dt>Dont en retard</dt><dd>{{money(data.overdue_now)}}</dd></dl><p>{{data.definitions.receivable_now}}</p></section></section></template>
<style scoped>.direction-dashboard header{display:flex;justify-content:space-between;flex-wrap:wrap;gap:16px}.direction-dashboard form{display:flex;align-items:end;flex-wrap:wrap;gap:12px}.direction-dashboard label{display:flex;flex-direction:column;gap:6px}.direction-dashboard input,.direction-dashboard button{min-height:44px}.direction-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin:20px 0}.direction-cards article{min-width:0;overflow-wrap:anywhere}.direction-cards strong{font-size:28px}.direction-cards small{display:block}.direction-cards p,.direction-balances p{font-size:13px;line-height:1.5}.direction-balances{padding:20px}.direction-balances dl{display:grid;grid-template-columns:1fr auto;gap:12px}.direction-balances dd{margin:0}@media(max-width:480px){.direction-cards{grid-template-columns:1fr}.direction-dashboard form{width:100%}.direction-dashboard form label{flex:1;min-width:120px}.direction-dashboard form button{width:100%}}</style>
