<script setup lang="ts">
import {ref,computed,onUnmounted} from 'vue'
import {api} from './api'
const props=defineProps<{initial:any,currency:string}>()
const data=ref(props.initial),start=ref(props.initial.start),end=ref(props.initial.end),error=ref(''),busy=ref(false)
const metrics=computed(()=>Object.entries(data.value.current as Record<string,string|number|null>).map(([key,value])=>({key,value})))
let alive=true,generation=0
const labels:any={revenue_ht:'Chiffre d’affaires HT',receipts:'Encaissements clients',approved_expenses:'Dépenses validées',completed_missions:'Missions terminées',commercial_margin:'Marge commerciale'}
const money=(value:any)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:props.currency,maximumFractionDigits:2}).format(Number(value))
async function reload(){const version=++generation;busy.value=true;error.value='';try{const result=await api('dashboard?'+new URLSearchParams({start:start.value,end:end.value}));if(alive&&version===generation){if(!result.direction)throw new Error('Cette synthèse n’est plus accessible.');data.value=result.direction}}catch(e:any){if(alive&&version===generation)error.value=e.message}finally{if(alive&&version===generation)busy.value=false}}
onUnmounted(()=>{alive=false;generation++})
</script>
<template><section class="direction-dashboard" aria-label="Tableau de bord Direction"><header><div><h2>Pilotage de l’entreprise</h2><p>Fuseau {{data.timezone}} · comparaison avec {{data.previous_start}} → {{data.previous_end}}</p></div><form @submit.prevent="reload"><label>Début<input v-model="start" type="date" required/></label><label>Fin<input v-model="end" type="date" required/></label><button class="primary" :disabled="busy">{{busy?'Actualisation…':'Appliquer la période'}}</button></form></header><p v-if="error" class="error-box" role="alert">{{error}}</p><div class="direction-cards"><article v-for="{key,value} in metrics" :key="key" class="stat-card"><template v-if="value!==null"><span>{{labels[key]}}</span><strong>{{key==='completed_missions'?value:money(value)}}</strong><small>Précédent : {{key==='completed_missions'?data.previous[key]:money(data.previous[key])}}</small><small>Écart : {{Number(data.changes[key])>0?'+':''}}{{key==='completed_missions'?Number(data.changes[key]):money(data.changes[key])}}</small><p>{{data.definitions[key]}}</p></template><template v-else><span>{{labels[key]}}</span><p>Module ou accès indisponible.</p></template></article></div><section class="panel direction-balances"><h2>Créances actuelles</h2><p>Ces soldes correspondent à la situation actuelle, indépendamment de la période choisie.</p><dl><dt>À encaisser</dt><dd>{{money(data.receivable_now)}}</dd><dt>Dont en retard</dt><dd>{{money(data.overdue_now)}}</dd></dl><p>{{data.definitions.receivable_now}}</p></section></section></template>
<style scoped>.direction-dashboard header{display:flex;justify-content:space-between;flex-wrap:wrap;gap:16px}.direction-dashboard form{display:flex;align-items:end;flex-wrap:wrap;gap:12px}.direction-dashboard label{display:flex;flex-direction:column;gap:6px}.direction-dashboard input,.direction-dashboard button{min-height:44px}.direction-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin:20px 0}.direction-cards article{min-width:0;overflow-wrap:anywhere}.direction-cards strong{font-size:28px}.direction-cards small{display:block}.direction-cards p,.direction-balances p{font-size:13px;line-height:1.5}.direction-balances{padding:20px}.direction-balances dl{display:grid;grid-template-columns:1fr auto;gap:12px}.direction-balances dd{margin:0}@media(max-width:480px){.direction-cards{grid-template-columns:1fr}.direction-dashboard form{width:100%}.direction-dashboard form label{flex:1;min-width:120px}.direction-dashboard form button{width:100%}}</style>
