<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue'
import {Bell,ClipboardCheck,Plus,Download,RefreshCw} from 'lucide-vue-next'
import {api,download} from './api'
const props=defineProps<{role:string}>()
const emit=defineEmits(['navigate'])
const tab=ref('notifications'),rows=ref<any[]>([]),count=ref(0),page=ref(1),unread=ref(0),busy=ref(false),error=ref(''),notice=ref(''),formOpen=ref(false)
const trips=ref<any[]>([]),tripPage=ref(1),tripCount=ref(0),query=ref(''),files=ref<Record<string,File>>({}),titles=ref<Record<string,string>>({})
const checks=[['brakes','Freins'],['tires','Pneus'],['lights','Éclairage'],['fluids','Niveaux et fuites'],['equipment','Équipements de sécurité'],['documents','Documents du véhicule']]
const kinds:Record<string,string>={incident:'Incident',request:'Demande d’intervention',check:'Contrôle avant départ',mileage:'Relevé kilométrique'}
const statuses:Record<string,string>={reported:'Signalé',resolved:'Résolu',planned:'Planifiée',active:'En cours',completed:'Terminée',cancelled:'Annulée',recorded:'Enregistré'}
const form=ref<any>({mission:'',kind:'incident',title:'',description:'',severity:'minor',category:'breakdown',mileage:'',checks:{}})
let timer:ReturnType<typeof setInterval>|undefined
async function load(){error.value='';try{const result=await api(`field/${tab.value}?page=${page.value}`);rows.value=result.results;count.value=result.count;if(tab.value==='notifications')unread.value=result.unread}catch(e:any){error.value=e.message}}
function navigate(value:string){tab.value=value;page.value=1;load()}
async function search(){try{const result=await api(`field/context?page=${tripPage.value}&q=${encodeURIComponent(query.value)}`);trips.value=result.results;tripCount.value=result.count}catch(e:any){error.value=e.message}}
async function create(){formOpen.value=true;tripPage.value=1;await search()}
async function save(){busy.value=true;error.value='';try{const data={...form.value,checks:form.value.kind==='check'?Object.fromEntries(checks.map(([key])=>[key,form.value.checks[key]==='ok'])):{}};if(form.value.mileage==='')delete data.mileage;await api('field/reports','POST',data);formOpen.value=false;form.value={mission:'',kind:'incident',title:'',description:'',severity:'minor',category:'breakdown',mileage:'',checks:{}};notice.value='Déclaration enregistrée et disponible pour le traitement.';tab.value='reports';page.value=1;await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function mark(row:any){try{await api('field/notifications','POST',{key:row.key});await load()}catch(e:any){error.value=e.message}}
async function attach(row:any){busy.value=true;error.value='';try{const data=new FormData();data.append('file',files.value[row.id]);data.append('title',titles.value[row.id]||files.value[row.id].name);await api(`field/reports/${row.id}/attachments`,'POST',data);delete files.value[row.id];await load();notice.value='Pièce jointe enregistrée.'}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function getFile(item:any){try{await download('field/attachments/'+item.id,item.title)}catch(e:any){error.value=e.message}}
onMounted(()=>{load();timer=setInterval(()=>{if(!document.hidden&&!formOpen.value&&!busy.value)load()},60000)})
onUnmounted(()=>clearInterval(timer))
</script>
<template>
 <section class="field-workspace"><div class="field-toolbar"><div><h2>Terrain et suivi véhicule</h2><p>Déclarez les événements, contrôlez votre véhicule et suivez leur traitement.</p></div><button v-if="role!=='workshop'" class="primary" @click="create"><Plus :size="17"/>Nouvelle déclaration</button></div>
 <div v-if="error" class="error-box" role="alert">{{error}}</div><div v-if="notice" class="success-box" role="status">{{notice}}</div>
 <div class="field-tabs"><button :class="tab==='notifications'?'primary':'secondary'" @click="navigate('notifications')"><Bell :size="17"/>Notifications <span v-if="unread">({{unread}} non lues)</span></button><button :class="tab==='reports'?'primary':'secondary'" @click="navigate('reports')"><ClipboardCheck :size="17"/>Déclarations et suivi</button><button class="icon-btn" aria-label="Actualiser le suivi" @click="load"><RefreshCw :size="17"/></button></div>
 <section v-if="formOpen" class="panel field-form"><h3>Nouvelle déclaration terrain</h3><div class="form-row"><label>Rechercher une mission ou un véhicule<input v-model="query" type="search" @keyup.enter="tripPage=1;search()"/></label><button class="secondary" @click="tripPage=1;search()">Rechercher</button></div><div v-if="tripCount>25" class="field-tabs"><button class="secondary" :disabled="tripPage===1" @click="tripPage--;search()">Missions précédentes</button><button class="secondary" :disabled="tripPage*25>=tripCount" @click="tripPage++;search()">Missions suivantes</button></div>
 <form @submit.prevent="save"><div class="form-grid"><label>Mission<select v-model="form.mission" required><option value="">Sélectionner</option><option v-for="trip in trips" :key="trip.id" :value="trip.id">{{trip.reference}} · {{trip.vehicle}} · {{trip.mileage}} km</option></select></label><label>Type de déclaration<select v-model="form.kind"><option v-for="(name,key) in kinds" :value="key">{{name}}</option></select></label><label class="span-2">Objet<input v-model="form.title" required maxlength="180"/></label><label class="span-2">Description et anomalies<textarea v-model="form.description" rows="4" maxlength="10000" :required="['incident','request'].includes(form.kind)"></textarea></label><label>Compteur kilométrique<input v-model="form.mileage" type="number" min="0" step="1" :required="['check','mileage'].includes(form.kind)"/></label><template v-if="form.kind==='incident'"><label>Gravité<select v-model="form.severity"><option value="minor">Mineure</option><option value="major">Majeure</option><option value="critical">Critique</option></select></label><label>Nature<select v-model="form.category"><option value="breakdown">Panne</option><option value="accident">Accident</option><option value="cargo">Marchandise</option><option value="delay">Retard</option><option value="other">Autre</option></select></label></template><template v-if="form.kind==='check'"><label v-for="[key,name] in checks" :key="key">{{name}}<select v-model="form.checks[key]" required><option value="">À contrôler</option><option value="ok">Conforme</option><option value="fault">Anomalie</option></select></label><p class="field-help span-2">Une anomalie crée une demande atelier et bloque le démarrage jusqu’à un nouveau contrôle conforme. Joignez les photos après enregistrement.</p></template></div><footer class="editor-footer"><button type="button" class="secondary" :disabled="busy" @click="formOpen=false">Annuler</button><button class="primary" :disabled="busy">Enregistrer la déclaration</button></footer></form></section>
 <p class="field-help" v-if="tab==='notifications'">Notifications dans l’application, actualisées toutes les minutes lorsque cet écran est ouvert. Les changements et nouvelles échéances réapparaissent comme non lus.</p>
 <div v-if="!rows.length" class="panel empty-state">Aucun élément à afficher.</div>
 <div class="field-cards"><article v-for="row in rows" :key="row.id||row.key" class="panel field-card" :class="[row.severity,{'is-read':row.read}]"><template v-if="tab==='notifications'"><div class="field-toolbar"><h3>{{row.title}}</h3><span class="status">{{row.read?'Lu':row.severity==='urgent'?'Prioritaire':'Non lu'}}</span></div><p>{{row.body}}</p><button v-if="!row.read" class="text-btn" @click="mark(row)">Marquer comme lu</button></template><template v-else><div class="field-toolbar"><h3>{{row.title}}</h3><span class="status">{{statuses[row.status]}}</span></div><small>{{kinds[row.kind]}} · {{row.mission}} · {{new Date(row.created_at).toLocaleString('fr-FR')}} · {{row.author}}</small><p>{{row.description}}</p><p v-if="row.mileage!==null">Compteur : {{row.mileage}} km</p><ul v-if="row.kind==='check'"><li v-for="[key,name] in checks">{{name}} : {{row.checks[key]?'Conforme':'Anomalie'}}</li></ul><blockquote v-if="row.response"><strong>Retour du traitement</strong><p>{{row.response}}</p></blockquote><div class="field-tabs"><button v-for="file in row.attachments" class="text-btn" @click="getFile(file)"><Download :size="16"/>{{file.title}}</button></div><form v-if="role!=='workshop'" class="field-upload" @submit.prevent="attach(row)"><label>Photo ou justificatif (10 Mo maximum)<input type="file" accept="image/jpeg,image/png,application/pdf" required @change="files[row.id]=($event.target as HTMLInputElement).files![0]"/></label><button class="secondary" :disabled="busy||!files[row.id]">Joindre le fichier</button></form><div v-if="role!=='driver'" class="field-tabs"><button v-if="row.incident" class="text-btn" @click="emit('navigate','incidents')">Traiter dans Incidents</button><button v-if="row.maintenance&&role!=='operations'" class="text-btn" @click="emit('navigate','maintenance')">Traiter dans Entretien</button></div></template></article></div>
 <footer class="table-pagination"><span>{{count}} élément(s)</span><div><button class="secondary" :disabled="page===1" @click="page--;load()">Précédent</button><span>{{page}}</span><button class="secondary" :disabled="page*25>=count" @click="page++;load()">Suivant</button></div></footer></section>
</template>
<style scoped>
.field-toolbar,.field-tabs,.field-upload{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.field-toolbar p,.field-help{color:#63796b;margin-top:10px}.field-tabs{justify-content:flex-start;margin:22px 0}.field-form,.field-card{padding:24px}.field-form h3{margin-bottom:20px}.field-cards{display:grid;gap:16px}.field-card p{white-space:pre-wrap;overflow-wrap:anywhere;margin:14px 0;line-height:1.6}.field-card small{display:block;margin-top:12px;color:#64786b}.field-card.urgent{border-left:4px solid #b73c32}.field-card.warning{border-left:4px solid #b78420}.field-card.is-read{background:#f5f8f5}.field-upload{border-top:1px solid #dbe5de;padding-top:16px;margin-top:16px}.field-card blockquote{border-left:3px solid #16785d;padding:12px;background:#eef6f0}.field-card ul{padding-left:20px;line-height:1.8}.field-card{animation:field-in .2s ease-out}@keyframes field-in{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.field-card{animation:none}}@media(max-width:600px){.field-form,.field-card{padding:16px}.field-upload input{max-width:100%}.field-toolbar h2{font-size:22px}}
</style>
