<script setup lang="ts">
import {ref,onMounted,onUnmounted,computed,nextTick} from 'vue'
import {money} from './api'
const props=defineProps<{invoice:any,organization:any,customer:any,returnFocus?:HTMLElement}>(),emit=defineEmits(['close'])
const controls=ref<HTMLElement|null>(null),title=computed(()=>({quote:'Devis',invoice:'Facture',credit:'Avoir'} as any)[props.invoice.kind]||'Document')
const day=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('fr-FR'):'-'
const amount=(value:any)=>money(value,props.organization.currency)
let focus:HTMLElement|null=null,app:HTMLElement|null=null,previousInert=false
onMounted(async()=>{focus=props.returnFocus||document.activeElement as HTMLElement;document.addEventListener('keydown',keys,true);app=document.getElementById('app');if(app){previousInert=app.inert;app.inert=true}await nextTick();controls.value?.querySelector<HTMLButtonElement>('button')?.focus()})
onUnmounted(()=>{document.removeEventListener('keydown',keys,true);if(app)app.inert=previousInert;if(focus?.isConnected)focus.focus()})
function keys(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();emit('close');return}if(event.key!=='Tab')return;const buttons=controls.value?.querySelectorAll<HTMLButtonElement>('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function print(){window.print()}
</script>
<template><Teleport to="body"><div class="financial-preview" @click.self="emit('close')" @keydown.stop="keys"><section role="dialog" aria-modal="true" :aria-label="title+' '+(invoice.number||'Brouillon')"><header ref="controls" class="financial-controls"><h2>Aperçu du document</h2><button class="secondary" @click="print">Imprimer / enregistrer en PDF</button><button class="secondary" @click="emit('close')">Fermer le document</button></header><article class="financial-document"><header class="financial-identity"><div><img src="/icons/icon-192.png" width="56" height="56" alt="TransitFlow"/><h1>{{organization.name}}</h1><p>{{organization.address}}</p><p>{{organization.email}}<span v-if="organization.phone"> - {{organization.phone}}</span></p><p v-if="organization.registration">Registre : {{organization.registration}}</p><p v-if="organization.tax_number">Identifiant fiscal : {{organization.tax_number}}</p></div><div><h2>{{title}}</h2><strong>{{invoice.number||'Brouillon sans numéro'}}</strong><p v-if="invoice.status==='draft'" class="financial-draft">BROUILLON - document non émis</p><p v-if="invoice.status==='cancelled'">Document annulé</p></div></header><section class="financial-details"><div><h3>Client</h3><strong>{{customer.name}}</strong><p>{{customer.address}}</p><p>{{customer.email}}</p><p v-if="customer.tax_number">Identifiant fiscal : {{customer.tax_number}}</p></div><div><p>Date : {{day(invoice.date)}}</p><p>{{invoice.kind==='quote'?'Valable jusqu’au':'Échéance'}} : {{day(invoice.due_date)}}</p><p v-if="invoice.relations?.order">Commande : {{invoice.relations.order}}</p><p v-if="invoice.relations?.mission">Mission : {{invoice.relations.mission}}</p><p v-if="invoice.relations?.original">Document d'origine : {{invoice.relations.original}}</p></div></section><p v-if="invoice.origin||invoice.destination">{{invoice.origin}} → {{invoice.destination}}</p><table><thead><tr><th>Prestation</th><th>Quantité</th><th>Prix HT</th><th>Taxe</th><th>Total TTC</th></tr></thead><tbody><tr v-for="(line,index) in invoice.lines" :key="index"><td data-label="Prestation">{{line.description}}</td><td data-label="Quantité">{{line.quantity}}</td><td data-label="Prix HT">{{amount(line.price)}}</td><td data-label="Taxe">{{line.tax_rate}} %</td><td data-label="Total TTC">{{line.total===undefined?'—':amount(line.total)}}</td></tr></tbody></table><dl class="financial-totals"><dt>Total HT</dt><dd>{{amount(invoice.subtotal)}}</dd><dt>Taxes</dt><dd>{{amount(invoice.tax)}}</dd><dt><strong>Total TTC</strong></dt><dd><strong>{{amount(invoice.total)}}</strong></dd><template v-if="invoice.kind==='invoice'"><dt>Réglé</dt><dd>{{amount(invoice.paid)}}</dd><dt>Solde restant</dt><dd>{{amount(invoice.balance)}}</dd></template></dl><p v-if="invoice.notes" class="financial-notes">{{invoice.notes}}</p><footer>{{organization.name}} - {{title}} {{invoice.number||'Brouillon'}} - {{organization.currency}}</footer></article></section></div></Teleport></template>
<style>
.financial-preview{position:fixed;inset:0;z-index:200;background:#163d3677;overflow:auto;padding:24px}.financial-preview>section{max-width:900px;margin:auto;background:white;border-radius:12px}.financial-controls{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:20px;border-bottom:1px solid #dde5df}.financial-controls button{min-height:44px}.financial-document{padding:32px;color:#163d36;background:white;overflow-wrap:anywhere}.financial-document p{white-space:pre-line;margin:8px 0}.financial-identity,.financial-details{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px}.financial-identity>div:last-child,.financial-details>div:last-child{text-align:right}.financial-document h1{font-size:25px;margin:10px 0}.financial-document h2{font-size:24px}.financial-document table{width:100%;min-width:0;border-collapse:collapse;margin:24px 0}.financial-document th,.financial-document td{padding:12px 8px;border-bottom:1px solid #dde5df;vertical-align:top;text-align:right}.financial-document th:first-child,.financial-document td:first-child{text-align:left;width:40%}.financial-totals{display:grid;grid-template-columns:1fr auto;gap:10px;max-width:360px;margin:24px 0 24px auto}.financial-totals dd{margin:0;text-align:right}.financial-document footer{border-top:1px solid #dde5df;padding-top:16px;font-size:12px}.financial-draft{font-weight:bold;color:#895500}@media(max-width:600px){.financial-preview{padding:8px}.financial-document{padding:16px}.financial-identity,.financial-details{grid-template-columns:1fr;gap:12px}.financial-identity>div:last-child,.financial-details>div:last-child{text-align:left}.financial-document table,.financial-document tbody,.financial-document tr,.financial-document td{display:block;width:100%}.financial-document thead{display:none}.financial-document tr{margin-bottom:16px}.financial-document td{display:flex;justify-content:space-between;gap:16px}.financial-document td:first-child{width:100%}.financial-document td::before{content:attr(data-label);font-weight:600;text-align:left}.financial-controls{padding:16px}.financial-controls button{flex:1}.financial-totals{max-width:none}}
@media print{@page{size:A4;margin:14mm;@bottom-right{content:counter(page) " / " counter(pages);font-size:9pt;color:#163d36}}html:has(.financial-preview),body:has(.financial-preview){background:white!important}body:has(.financial-preview)>*:not(.financial-preview){display:none!important}.financial-preview{position:static;padding:0;background:white;overflow:visible}.financial-preview>section{max-width:none;border-radius:0}.financial-controls{display:none!important}.financial-document{padding:0;font-size:10pt}.financial-identity,.financial-details{grid-template-columns:1fr 1fr;break-inside:avoid}.financial-identity>div:last-child,.financial-details>div:last-child{text-align:right}.financial-document table{display:table;width:100%}.financial-document thead{display:table-header-group}.financial-document tbody{display:table-row-group}.financial-document tr{display:table-row;break-inside:avoid}.financial-document td,.financial-document th{display:table-cell;width:auto;padding:8px}.financial-document td::before{display:none}.financial-document td:first-child{width:40%}.financial-totals{max-width:360px;break-inside:avoid}.financial-document footer{break-inside:avoid}}
</style>
