import {reactive} from 'vue'
import {api,organization} from './api'
import {subscribeActivity} from './activity'
export const gps=reactive({missions:[] as any[],state:'waiting',pending:0,error:'',offline:!navigator.onLine})
let watchId:number|undefined,timer:any,unsubscribe:()=>void=()=>{},permission:PermissionStatus|undefined,wake:any,alive=false,tenant='',user=0,epoch=0,loading=false,sending=false
let config:any={},last:GeolocationPosition|null=null,sequence=Promise.resolve(),memory:any[]=[]
const database=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('transitflow-mission-gps',1);request.onupgradeneeded=()=>request.result.createObjectStore('points',{keyPath:'key'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})
async function store(mode:IDBTransactionMode,operation:(s:IDBObjectStore)=>IDBRequest<any>):Promise<any>{const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('points',mode),request=operation(tx.objectStore('points'));let result:any;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
async function queued(){const rows=await store('readonly',s=>s.getAll());return rows.filter((p:any)=>p.user===user&&p.organization===tenant).concat(memory)}
export async function purgeGps(userId?:number,org?:string){await sequence.catch(()=>{});const rows=await store('readonly',s=>s.getAll());for(const row of rows)if((!userId||row.user===userId)&&(!org||row.organization===org))await store('readwrite',s=>s.delete(row.key))}
function distance(a:GeolocationPosition,b:GeolocationPosition){const r=Math.PI/180,x=(b.coords.latitude-a.coords.latitude)*r,y=(b.coords.longitude-a.coords.longitude)*r;return 12742000*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(a.coords.latitude*r)*Math.cos(b.coords.latitude*r)*Math.sin(y/2)**2))}
async function lock(){if(!alive||!gps.missions.length||document.visibilityState!=='visible')return;try{wake=await (navigator as any).wakeLock?.request('screen')}catch{}}
function clearWatch(){if(watchId!==undefined)navigator.geolocation.clearWatch(watchId);watchId=undefined;wake?.release().catch(()=>{});wake=null;last=null}
async function state(value:string){gps.state=value;if(!navigator.onLine)return;for(const mission of gps.missions)try{await api(`missions/${mission.id}/tracking`,'POST',{state:value})}catch{}}
function denied(error:GeolocationPositionError){if(!alive)return;gps.error=error.code===1?'TransitFlow n’a plus accès à votre position. La localisation est obligatoire pendant une mission active. Réactivez l’autorisation de localisation pour poursuivre normalement.':'Le GPS ne fournit pas de position. Gardez TransitFlow ouvert et vérifiez la localisation de votre appareil.';if(error.code===1)clearWatch();state(error.code===1?'permission_required':'unavailable')}
function accept(point:GeolocationPosition,force=false){if(!alive||!gps.missions.length||!Number.isFinite(point.coords.latitude)||!Number.isFinite(point.coords.longitude)||point.coords.accuracy>config.max_accuracy)return;if(!gps.missions.some(m=>point.timestamp>=Date.parse(m.started_at)))return;if(last&&!force){const elapsed=point.timestamp-last.timestamp;if(elapsed<config.sample_seconds*1000)return;if(distance(last,point)<config.movement_metres&&elapsed<config.stationary_seconds*1000)return}last=point;gps.state='capturing';gps.error='';const generation=epoch,targets=gps.missions.filter(m=>point.timestamp>=Date.parse(m.started_at)),selectedTenant=tenant,selectedUser=user;sequence=sequence.catch(()=>{}).then(async()=>{if(generation!==epoch)return;for(const mission of targets){const client_id=crypto.randomUUID(),row={key:client_id,user:selectedUser,organization:selectedTenant,mission:mission.id,point:{client_id,timestamp:new Date(point.timestamp).toISOString(),latitude:point.coords.latitude,longitude:point.coords.longitude,accuracy:point.coords.accuracy,speed:point.coords.speed,heading:point.coords.heading}};try{await store('readwrite',s=>s.put(row))}catch{memory.push(row);gps.error='Stockage local indisponible : gardez cette fenêtre ouverte pour conserver les positions en mémoire.'}}gps.pending=(await queued().catch(()=>memory)).length;flush()})}
export async function authorizeGps(){if(!alive||!gps.missions.length||watchId!==undefined)return;if(!navigator.geolocation){state('unavailable');return}watchId=navigator.geolocation.watchPosition(p=>accept(p),denied,{enableHighAccuracy:true,maximumAge:5000,timeout:30000});state('capturing');lock()}
async function permissionCheck(){try{permission=await navigator.permissions.query({name:'geolocation'});permission.onchange=()=>{if(!alive)return;if(permission?.state==='granted')authorizeGps();else{clearWatch();state('permission_required')}};if(permission.state==='granted')authorizeGps();else state('permission_required')}catch{state('permission_required')}}
async function migrateLegacy(){const prefix=`transitflow.positions.${user}.${tenant}.`;for(const key of Object.keys(localStorage)){if(!key.startsWith(prefix)||!/^[-a-f0-9]{36}$/.test(key.slice(prefix.length)))continue;try{const points=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(points))continue;for(const point of points){const client_id=point.client_id||crypto.randomUUID();await store('readwrite',s=>s.put({key:client_id,user,organization:tenant,mission:key.slice(prefix.length),point:{...point,client_id}}))}localStorage.removeItem(key)}catch{gps.error='Les positions précédentes restent conservées dans ce navigateur : stockage local indisponible.'}}}
async function refreshContext(){if(!alive||loading||!navigator.onLine)return;loading=true;const generation=epoch;try{const data=await api('tracking');if(generation!==epoch)return;config=data.config;const previous=gps.missions.map(x=>x.id).join();gps.missions=data.missions.filter((m:any)=>m.driver_user===user);if(!gps.missions.length){clearWatch();gps.state='ended';await flush()}else if(previous!==gps.missions.map(x=>x.id).join()||watchId===undefined&&gps.state==='waiting'){clearWatch();await permissionCheck()}await flush()}catch(e:any){if(e.status===403||e.status===401){clearWatch();gps.missions=[]}gps.error=e.message}finally{loading=false}}
export async function flush(){if(!alive||sending||!navigator.onLine)return;sending=true;const generation=epoch;try{let rows=await queued();gps.pending=rows.length;for(const mission of new Set(rows.map((x:any)=>x.mission))){const all=rows.filter((x:any)=>x.mission===mission);for(let i=0;i<all.length;i+=200){if(generation!==epoch)return;const batch=all.slice(i,i+200);try{await api(`missions/${mission}/positions`,'POST',{positions:batch.map((r:any)=>r.point)})}catch(e:any){if(generation!==epoch)return;if([401,403,404].includes(e.status)){if(gps.missions.some(m=>m.id===mission))clearWatch();gps.missions=gps.missions.filter(m=>m.id!==mission);for(const row of batch)await store('readwrite',s=>s.delete(row.key));continue}throw e}for(const row of batch){await store('readwrite',s=>s.delete(row.key));memory=memory.filter(p=>p.key!==row.key)}}}if(generation===epoch)gps.pending=(await queued()).length}catch(e:any){gps.error=e.message}finally{sending=false}}
export async function finalGps(mission:string){if(!gps.missions.some(m=>m.id===mission))return;if(watchId!==undefined)await new Promise<void>(resolve=>navigator.geolocation.getCurrentPosition(p=>{accept(p,true);resolve()},()=>resolve(),{enableHighAccuracy:true,maximumAge:0,timeout:3000}));await sequence;await flush()}
function online(){gps.offline=false;refreshContext();flush()}
function offline(){gps.offline=true}
function visibility(){if(document.visibilityState==='visible'){wake?.release().catch(()=>{});lock();refreshContext();flush()}}
export function startGps(userId:number){stopGps();alive=true;tenant=organization;user=userId;gps.pending=0;gps.error='';gps.state='waiting';gps.offline=!navigator.onLine;unsubscribe=subscribeActivity(e=>{if(e.type==='tracking'||e.type==='tracking_access'||e.type==='resync'||e.type==='notification')refreshContext()});window.addEventListener('online',online);window.addEventListener('offline',offline);document.addEventListener('visibilitychange',visibility);timer=setInterval(()=>{if(watchId!==undefined&&gps.missions.length&&last&&Date.now()-last.timestamp>=config.stationary_seconds*1000)navigator.geolocation.getCurrentPosition(p=>accept(p),denied,{enableHighAccuracy:true,maximumAge:5000,timeout:15000});if(gps.state==='capturing'&&gps.missions.length&&Date.now()-(last?.timestamp||Date.parse(gps.missions[0].started_at))>config.lost_seconds*1000){gps.error='Aucune position GPS récente. Gardez TransitFlow ouvert au premier plan.';state('unavailable')}refreshContext();flush()},15000);migrateLegacy().finally(refreshContext)}
export function stopGps(){alive=false;epoch++;clearWatch();clearInterval(timer);unsubscribe();permission&&(permission.onchange=null);window.removeEventListener('online',online);window.removeEventListener('offline',offline);document.removeEventListener('visibilitychange',visibility);gps.missions=[];memory=[]}
export const trackingLabel:Record<string,string>={online:'En ligne',recent:'Position récente',lost:'Signal perdu',waiting:'Localisation requise',permission_required:'Permission localisation requise',unavailable:'GPS indisponible',ended:'Suivi terminé',capturing:'Suivi GPS actif'}
