<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue'
import {api} from './api'
import {subscribeActivity,connectionState} from './activity'
import {trackingLabel} from './gps'
import TrackingMap from './TrackingMap.vue'
const emit=defineEmits(['mission']),data=ref<any>(null),selected=ref(''),error=ref('');let unsubscribe:()=>void,timer:any,debounce:any,loading=false,again=false,alive=true,lastRequest=0
async function load(){if(loading){again=true;return}loading=true;lastRequest=Date.now();try{const result=await api('tracking');if(alive)data.value=result;error.value=''}catch(e:any){error.value=e.message}finally{loading=false;if(again&&alive){again=false;debounce=setTimeout(()=>{debounce=null;load()},Math.max(0,1000-(Date.now()-lastRequest)))}}}
function freshness(){if(!data.value)return;const now=Date.now();for(const mission of data.value.missions){if(['permission_required','unavailable'].includes(mission.state))continue;const age=(now-Date.parse(mission.last?.timestamp||mission.started_at))/1000;mission.state=age>=data.value.config.lost_seconds?'lost':!mission.last?'waiting':age<=data.value.config.online_seconds?'online':'recent'}}
onMounted(()=>{load();unsubscribe=subscribeActivity(e=>{if(['tracking','resync'].includes(e.type)){if(!debounce)debounce=setTimeout(()=>{debounce=null;load()},Math.max(200,1000-(Date.now()-lastRequest)))}});timer=setInterval(freshness,5000)});onUnmounted(()=>{alive=false;unsubscribe?.();clearTimeout(debounce);clearInterval(timer)})
</script>
<template><section class="panel live-tracking"><p>{{connectionState}} · positions enregistrées en base. {{data?.missions.length||0}} mission(s) active(s).</p><p v-if="error" role="alert">{{error}}</p><template v-if="data"><TrackingMap :missions="data.missions" :tiles="data.tiles" :selected="selected" @mission="emit('mission',$event)"/><div class="tracking-list"><article v-for="mission in data.missions" :key="mission.id" :data-mission="mission.id"><button class="secondary" @click="selected=mission.id">{{mission.plate}} · {{mission.vehicle}}</button><strong>{{mission.reference}} · {{mission.driver}}</strong><p>{{mission.origin}} → {{mission.destination}}</p><span class="status" :data-state="mission.state">{{trackingLabel[mission.state]}}</span><p v-if="mission.last">{{Number(mission.last.latitude).toFixed(6)}}, {{Number(mission.last.longitude).toFixed(6)}} · {{new Date(mission.last.timestamp).toLocaleString('fr-FR')}}<br/><span v-if="mission.last.accuracy!=null">Précision {{Math.round(mission.last.accuracy)}} m · </span><span v-if="mission.last.speed!=null">{{(mission.last.speed*3.6).toFixed(1)}} km/h</span></p><p v-else>Aucune position enregistrée.</p><button class="text-btn" @click="emit('mission',mission.id)">Voir la mission</button></article></div></template></section></template>
