<script setup lang="ts">
import {ref,onMounted,onUnmounted,nextTick,watch} from 'vue'
import {api,download} from './api'
import {subscribeActivity,updateCounts,typing,connectionState} from './activity'
const props=defineProps<{conversation?:string}>(),emit=defineEmits(['navigate'])
const conversations=ref<any[]>([]),selected=ref<any>(null),messages=ref<any[]>([]),search=ref(''),peopleSearch=ref(''),people=ref<any[]>([]),chosen=ref<number[]>([]),kind=ref('direct'),title=ref(''),creating=ref(false),body=ref(''),file=ref<File|null>(null),error=ref(''),busy=ref(false),cursor=ref<number|null>(null),listPage=ref(1),listMore=ref(false),memberForm=ref(false),typingName=ref(''),stream=ref<HTMLElement|null>(null)
let unsubscribe:()=>void=()=>{},searchTimer:any,peopleTimer:any,typingTimer:any,lastTyping=0,clientId=crypto.randomUUID(),alive=true,generation=0,pending=false,queued=false,lastContent=''
async function list(){try{const result=await api(`messaging/conversations?page=${listPage.value}&q=${encodeURIComponent(search.value)}`);if(!alive)return;conversations.value=result.results;listMore.value=!!result.next}catch(e:any){error.value=e.message}}
async function collaborators(){try{const result=await api('messaging/collaborators?q='+encodeURIComponent(peopleSearch.value));if(alive)people.value=result.results}catch(e:any){error.value=e.message}}
function findPeople(){clearTimeout(peopleTimer);peopleTimer=setTimeout(collaborators,300)}
async function downloadFile(id:string,name:string){try{await download("messaging/attachments/"+id,name)}catch(e:any){error.value=e.message}}
function find(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{listPage.value=1;list()},300)}
async function select(identity:string){const version=++generation;error.value='';messages.value=[];cursor.value=null
 try{const row=await api('messaging/conversations/'+identity);if(!alive||version!==generation)return;selected.value=row;history.replaceState({},'','/app#messages?conversation='+identity);await sync(true)}catch(e:any){error.value=e.message}}
async function sync(scroll=false){if(!selected.value)return;const nearBottom=stream.value?stream.value.scrollHeight-stream.value.scrollTop-stream.value.clientHeight<100:false;if(pending){queued=true;return}pending=true;const identity=selected.value.id,version=generation
 try{const [row,result]=await Promise.all([api('messaging/conversations/'+identity),api(`messaging/conversations/${identity}/messages`)]);if(!alive||version!==generation)return;selected.value=row
  const all=new Map(messages.value.map(m=>[m.id,m]));result.results.forEach((m:any)=>all.set(m.id,m));messages.value=Array.from(all.values()).sort((a,b)=>a.sequence-b.sequence);if(cursor.value===null)cursor.value=result.before
  if(document.visibilityState==='visible'){await api(`messaging/conversations/${identity}/read`,'POST',{sequence:row.sequence});await updateCounts();await list()}
  if(scroll||nearBottom){await nextTick();stream.value?.scrollTo({top:stream.value.scrollHeight})}
 }catch(e:any){error.value=e.message}finally{pending=false;if(queued){queued=false;sync()}}}
async function older(){if(!cursor.value||!selected.value)return;try{const r=await api(`messaging/conversations/${selected.value.id}/messages?before=${cursor.value}`);messages.value=[...r.results,...messages.value];cursor.value=r.before}catch(e:any){error.value=e.message}}
async function create(){busy.value=true;error.value='';try{const row=await api('messaging/conversations','POST',{kind:kind.value,title:title.value,participants:chosen.value});creating.value=false;chosen.value=[];title.value='';await list();await select(row.id)}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function send(){if(busy.value||(!body.value.trim()&&!file.value)||!selected.value)return;busy.value=true;error.value=''
 try{const signature=body.value+'|'+(file.value?file.value.name+file.value.size+file.value.lastModified:'');if(signature!==lastContent){clientId=crypto.randomUUID();lastContent=signature}let data:any={body:body.value,client_id:clientId};if(file.value){data=new FormData();data.append('body',body.value);data.append('client_id',clientId);data.append('file',file.value)}
  await api(`messaging/conversations/${selected.value.id}/messages`,'POST',data);body.value='';file.value=null;clientId=crypto.randomUUID();const input=document.querySelector<HTMLInputElement>('.message-file');if(input)input.value='';await sync(true);await list()
 }catch(e:any){error.value=e.message}finally{busy.value=false}}
function back(){selected.value=null;generation++;history.replaceState({},'','/app#messages')}
function viewport(){document.documentElement.style.setProperty('--chat-viewport',(window.visualViewport?.height||innerHeight)+'px')}
function composing(){if(selected.value&&Date.now()-lastTyping>3000){lastTyping=Date.now();typing(selected.value.id)}}
async function manage(action:string,identity?:number){if(!selected.value)return;try{selected.value=await api('messaging/conversations/'+selected.value.id,'PATCH',action==='archive'?{active:!selected.value.active}:action==='title'?{title:title.value}:{[action]:identity});await list();await updateCounts()}catch(e:any){error.value=e.message}}
async function receive(event:any){if(event.type==='typing'&&event.conversation===selected.value?.id){typingName.value=selected.value.participants.find((p:any)=>p.id===event.member)?.name||'Un collaborateur';clearTimeout(typingTimer);typingTimer=setTimeout(()=>typingName.value='',4500);return}await list();if(selected.value&&(event.type==='resync'||event.conversation===selected.value.id))await sync()}
watch(()=>props.conversation,id=>{if(id)select(id)})
onMounted(async()=>{viewport();window.visualViewport?.addEventListener('resize',viewport);unsubscribe=subscribeActivity(receive);await list();if(props.conversation)await select(props.conversation)})
onUnmounted(()=>{window.visualViewport?.removeEventListener('resize',viewport);alive=false;generation++;unsubscribe();clearTimeout(searchTimer);clearTimeout(peopleTimer);clearTimeout(typingTimer)})
</script>
<template>
 <section class="messaging" :class="{'has-selection':selected}">
  <aside class="conversation-list panel" aria-label="Conversations"><header><h2>Conversations</h2><button class="primary" @click="creating=true;collaborators()">Nouvelle discussion</button></header><label>Rechercher une conversation<input v-model="search" type="search" @input="find"/></label><p class="muted" role="status">{{connectionState}}</p>
   <button v-for="row in conversations" :key="row.id" class="conversation-item" :aria-current="selected?.id===row.id?'true':undefined" @click="select(row.id)"><span class="user-avatar">{{row.title.slice(0,1)}}</span><span><strong>{{row.title}}</strong><small>{{row.last_message||'Aucun message'}}</small><time v-if="row.last_message_at">{{new Date(row.last_message_at).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'})}}</time></span><b v-if="row.unread" class="unread-badge">{{row.unread}}</b></button>
   <p v-if="!conversations.length">Aucune conversation.</p><footer><button class="secondary" :disabled="listPage===1" @click="listPage--;list()">Précédent</button><button class="secondary" :disabled="!listMore" @click="listPage++;list()">Suivant</button></footer>
  </aside>
  <div class="conversation-detail panel" aria-label="Conversation active">
   <p v-if="error" role="alert" class="error-box">{{error}}</p><p v-if="!selected" class="empty-state">Choisissez une conversation ou démarrez une discussion.</p>
   <template v-else><header><button class="secondary conversation-back" @click="back">Retour</button><div><h2>{{selected.title}}</h2><p>{{selected.participants.filter((p:any)=>p.active).map((p:any)=>p.name).join(', ')}}</p><button v-if="selected.mission" class="text-btn" @click="emit('navigate','missions',selected.mission)">{{selected.mission_reference}} · Ouvrir la mission</button></div><button v-if="selected.can_manage&&selected.kind!=='direct'" class="secondary" @click="memberForm=!memberForm;title=selected.title;collaborators()">Gérer le groupe</button></header>
    <section v-if="memberForm" class="group-manager"><form @submit.prevent="manage('title')"><label>Titre du groupe<input v-model="title" maxlength="150" required/></label><button class="secondary">Renommer</button></form><p v-for="p in selected.participants.filter((p:any)=>p.active)" :key="p.id">{{p.name}}<button class="text-btn" @click="manage('remove',p.id)">Retirer</button></p><label>Ajouter un collaborateur<select @change="manage('add',Number(($event.target as HTMLSelectElement).value))"><option value="">Sélectionner</option><option v-for="p in people.filter((p:any)=>!selected.participants.some((x:any)=>x.active&&x.id===p.id))" :key="p.id" :value="p.id">{{p.name}}</option></select></label><button class="secondary" @click="manage('archive')">{{selected.active?'Archiver':'Réactiver'}}</button></section>
    <div ref="stream" class="message-stream" role="log" aria-label="Historique des messages" aria-live="polite"><button v-if="cursor" class="secondary" @click="older">Messages précédents</button><article v-for="message in messages" :key="message.id" class="message-bubble" :class="{own:message.own}"><strong>{{message.sender}}</strong><p>{{message.body}}</p><button v-for="a in message.attachments" :key="a.id" class="text-btn" @click="downloadFile(a.id,a.name)">{{a.name}} · Télécharger</button><small>{{new Date(message.created_at).toLocaleString('fr-FR')}} · {{message.own?(message.readers.length?'Lu par '+message.readers.join(', '):'Envoyé'):''}}</small></article></div>
    <p v-if="typingName" class="typing-status" role="status">{{typingName}} écrit…</p><form v-if="selected.active" class="message-composer" @submit.prevent="send"><label>Votre message<textarea v-model="body" rows="2" maxlength="10000" @input="composing" @keydown.ctrl.enter.prevent="send"></textarea></label><label class="file-label">Pièce jointe · PDF, PNG ou JPEG, 10 Mo<input class="message-file" type="file" accept="application/pdf,image/png,image/jpeg" @change="file=($event.target as HTMLInputElement).files?.[0]||null"/></label><button class="primary" :disabled="busy||(!body.trim()&&!file)">{{busy?'Envoi…':'Envoyer'}}</button></form><p v-else>Conversation archivée.</p>
   </template>
  </div>
 </section>
 <div v-if="creating" class="modal-backdrop"><section class="editor" role="dialog" aria-modal="true" aria-label="Nouvelle discussion"><header class="editor-head"><h2>Nouvelle discussion</h2><button class="secondary" @click="creating=false">Fermer</button></header><form class="editor-body" @submit.prevent="create"><p v-if="error" role="alert" class="error-box">{{error}}</p><label>Type<select v-model="kind" @change="chosen=[]"><option value="direct">Discussion privée</option><option value="group">Groupe</option></select></label><label v-if="kind==='group'">Titre<input v-model="title" required maxlength="150"/></label><label>Rechercher un collaborateur<input v-model="peopleSearch" type="search" @input="findPeople"/></label><label v-for="person in people" :key="person.id" class="person-choice"><input v-if="kind==='group'" v-model="chosen" type="checkbox" :value="person.id"/><input v-else type="radio" name="participant" :checked="chosen[0]===person.id" @change="chosen=[person.id]"/>{{person.name}} · {{person.role}}</label><footer class="editor-footer"><button class="primary" :disabled="busy||!chosen.length">Créer la conversation</button></footer></form></section></div>
</template>
<style scoped>
.messaging{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(0,2fr);gap:16px;height:calc(100dvh - 230px);min-height:480px}.conversation-list{padding:20px;overflow:auto}.conversation-list header,.conversation-detail header{display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap}.conversation-list h2,.conversation-detail h2{font-size:20px}.conversation-list label{display:block;margin:16px 0}.conversation-item{display:flex;align-items:center;gap:12px;width:100%;padding:14px 8px;border:0;border-bottom:1px solid #e3eae5;background:white;text-align:left;color:#123c33;min-height:72px}.conversation-item[aria-current=true]{background:#e8f2ed}.conversation-item>span:nth-child(2){min-width:0;flex:1}.conversation-item strong,.conversation-item small,.conversation-item time{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.conversation-item small,.conversation-item time{font-size:13px;color:#52665b;margin-top:5px}.conversation-detail{min-width:0;display:flex;flex-direction:column;overflow:hidden}.conversation-detail>header{padding:16px;border-bottom:1px solid #e3eae5}.conversation-detail header p{font-size:13px;line-height:1.5}.message-stream{overflow:auto;min-height:100px;flex:1;padding:20px;overscroll-behavior:contain}.message-bubble{padding:14px;background:#f1f5f2;border-radius:12px;margin:0 0 14px;max-width:90%;width:fit-content;overflow-wrap:anywhere}.message-bubble.own{margin-left:auto;background:#e0efe6}.message-bubble p{white-space:pre-wrap;line-height:1.6;margin:8px 0}.message-bubble small{display:block;font-size:12px;color:#52665b}.message-composer{padding:16px;border-top:1px solid #dce7df;display:grid;gap:10px;flex-shrink:0}.message-composer label{margin:0}.message-composer textarea{resize:vertical;max-height:160px}.message-file{max-width:100%;font-size:13px}.file-label{font-size:12px}.typing-status{padding:0 20px;font-size:13px}.conversation-back{display:none}.group-manager{padding:16px;max-height:260px;overflow:auto}.group-manager form,.group-manager p{display:flex;align-items:center;gap:12px;justify-content:space-between;margin:8px 0}.person-choice{display:flex;gap:12px;align-items:center;min-height:44px}.conversation-list footer{display:flex;gap:12px;margin-top:16px}.unread-badge{background:#126b56;color:white;border-radius:12px;padding:3px 8px;font-size:12px}
@media(max-width:600px){.messaging{display:block;height:calc(100dvh - 250px - env(safe-area-inset-bottom));min-height:0}.messaging.has-selection{position:fixed;z-index:40;left:0;right:0;top:env(safe-area-inset-top);height:calc(var(--chat-viewport,100dvh) - 76px - env(safe-area-inset-top) - env(safe-area-inset-bottom))}.has-selection .message-stream{min-height:0}.has-selection .conversation-detail{border-radius:0}.has-selection .message-composer textarea{max-height:100px}.conversation-list,.conversation-detail{height:100%}.conversation-detail{display:none}.has-selection .conversation-list{display:none}.has-selection .conversation-detail{display:flex}.conversation-back{display:block}.message-stream{padding:14px}.message-composer{padding:12px max(12px,env(safe-area-inset-right)) max(12px,env(safe-area-inset-bottom)) max(12px,env(safe-area-inset-left))}.message-composer textarea{font-size:16px}.message-bubble{max-width:96%}}
</style>
