<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {api} from './api'
import {subscribeActivity} from './activity'
import TrackingMap from './TrackingMap.vue'
const props=defineProps<{mission:any,canTrack:boolean,userId:number}>(),points=ref<any[]>([]),tiles=ref<any>(null),error=ref(''),state=ref('waiting');let unsubscribe:()=>void,alive=true,loading=false
async function load(){if(loading)return;loading=true;try{const [context,initial]=await Promise.all([api('tracking'),api(`missions/${props.mission.id}/positions`)]);let rows=initial.positions,next=initial.next;while(next&&alive){const page=await api(`missions/${props.mission.id}/positions?after=${encodeURIComponent(next)}`);rows.push(...page.positions);next=page.next}if(alive){points.value=rows;tiles.value=context.tiles;state.value=initial.state}}catch(e:any){error.value=e.message}finally{loading=false}}
const stats=computed(()=>{let distance=0;for(let i=1;i<points.value.length;i++){const a=points.value[i-1],b=points.value[i],r=Math.PI/180,x=(b.latitude-a.latitude)*r,y=(b.longitude-a.longitude)*r;distance+=12742*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(a.latitude*r)*Math.cos(b.latitude*r)*Math.sin(y/2)**2))}const speeds=points.value.filter(p=>p.speed!=null).map(p=>p.speed*3.6);return {distance,duration:points.value.length>1?(Date.parse(points.value.at(-1).timestamp)-Date.parse(points.value[0].timestamp))/60000:0,average:speeds.length?speeds.reduce((a,b)=>a+b,0)/speeds.length:null,max:speeds.length?Math.max(...speeds):null}})
const rows=computed(()=>[{...props.mission,plate:props.mission.relations?.vehicle||props.mission.reference,driver:props.mission.relations?.driver,last:points.value.at(-1),state:state.value}])
onMounted(()=>{load();unsubscribe=subscribeActivity(e=>{if(e.type==='resync'||e.type==='tracking'&&e.mission===props.mission.id)load()})});onUnmounted(()=>{alive=false;unsubscribe?.()})
</script>
<template><section class="tracking-panel"><h3>Parcours GPS réel</h3><p v-if="error" role="alert">{{error}}</p><TrackingMap v-if="tiles&&points.length" :missions="rows" :tiles="tiles" :trace="points"/><p v-if="!points.length">Aucune position enregistrée.</p><template v-else><p>Départ GPS : {{new Date(points[0].timestamp).toLocaleString('fr-FR')}}<br/>Dernier point : {{new Date(points.at(-1).timestamp).toLocaleString('fr-FR')}}</p><p>{{points.length}} points · {{stats.duration.toFixed(1)}} min · distance GPS approximative {{stats.distance.toFixed(2)}} km<span v-if="stats.average!=null"> · vitesse moyenne mesurée {{stats.average.toFixed(1)}} km/h · maximum {{stats.max?.toFixed(1)}} km/h</span></p></template><p class="field-help">La trace relie les positions mesurées. Origine prévue : {{mission.origin}} ; destination prévue : {{mission.destination}}. Aucun itinéraire ni destination cartographique n’est inventé à partir de ces noms.</p></section></template>
