<script setup lang="ts">
import {ref,onMounted,onUnmounted,watch} from 'vue'
import {Plus,Copy,ChevronLeft,ChevronRight} from 'lucide-vue-next'
import {api} from './api'
const customers=ref<any[]>([]),rows=ref<any[]>([]),invitations=ref<any[]>([]),query=ref(''),page=ref(1),count=ref(0),invPage=ref(1),invCount=ref(0)
const mode=ref('existing'),email=ref(''),partner=ref(''),name=ref(''),contact=ref(''),phone=ref(''),link=ref(''),busy=ref(false),error=ref(''),notice=ref(''),fields=ref<Record<string,string>>({}),duplicate=ref<any>(null),searching=ref(false),customerCount=ref(0)
let timer:ReturnType<typeof setTimeout>|undefined,searchVersion=0,alive=true
const statuses:Record<string,string>={pending:'En attente',accepted:'Acceptée',expired:'Expirée',canceled:'Annulée'}
async function search(){const version=++searchVersion;searching.value=true;try{const result=await api('portal-access/customers?q='+encodeURIComponent(query.value));if(alive&&version===searchVersion){customers.value=result.results;customerCount.value=result.count}}catch(e:any){if(alive&&version===searchVersion)error.value=e.message}finally{if(alive&&version===searchVersion)searching.value=false}}
watch(query,()=>{searchVersion++;clearTimeout(timer);timer=setTimeout(search,250)})
async function load(){try{const [access,invites]=await Promise.all([api('portal-access?page='+page.value),api('portal-access/invitations?page='+invPage.value)]);if(!alive)return;rows.value=access.results;count.value=access.count;invitations.value=invites.results;invCount.value=invites.count}catch(e:any){error.value=e.message}}
function select(customer:any){mode.value='existing';partner.value=customer.id;name.value=customer.name;email.value=customer.email||'';contact.value=customer.contact_name||'';phone.value=customer.phone||'';fields.value={};duplicate.value=null;error.value=''}
function changeMode(value:string){mode.value=value;partner.value='';name.value='';email.value='';contact.value='';phone.value='';fields.value={};duplicate.value=null;error.value='';notice.value='';link.value=''}
function failure(e:any){error.value=e.data?.detail||e.message;duplicate.value=e.data?.code==='duplicate_customer'?e.data.customer:null;for(const key of ['name','email','partner','contact_name','phone'])if(e.data?.[key])fields.value[key]=Array.isArray(e.data[key])?e.data[key].join(' '):e.data[key]}
function confirmation(result:any){link.value=result.link;notice.value=result.sent?`Invitation envoyée : une invitation à l’espace client de ${result.company} a été envoyée à ${result.invitation.email}.`:`Invitation créée pour ${result.company}. L’envoi du courriel à ${result.invitation.email} n’a pas abouti. Vous pouvez renvoyer l’invitation ou transmettre le lien ci-dessous.`}
async function invite(){fields.value={};error.value='';duplicate.value=null
 if(mode.value==='existing'&&!partner.value)fields.value.partner='Sélectionnez un client existant.'
 if(mode.value==='new'&&!name.value.trim())fields.value.name='Le nom du client est requis.'
 if(!email.value.trim())fields.value.email='Le courriel est requis.'
 else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim()))fields.value.email='Saisissez une adresse courriel valide.'
 if(Object.keys(fields.value).length)return
 busy.value=true;link.value='';notice.value='';try{const result=await api('portal-access','POST',{mode:mode.value,email:email.value.trim(),...(mode.value==='new'?{name:name.value.trim(),contact_name:contact.value.trim(),phone:phone.value.trim()}:{partner:partner.value})});confirmation(result);page.value=1;invPage.value=1;await Promise.all([load(),search()])}catch(e:any){failure(e);await load()}finally{busy.value=false}}
async function action(row:any,kind:string){busy.value=true;error.value='';notice.value='';link.value='';try{const result=await api(`portal-access/invitations/${row.id}/${kind}`,'POST',{});if(kind==='resend')confirmation(result);else notice.value='Invitation annulée. Son lien ne peut plus être accepté.';invPage.value=1;await load()}catch(e:any){failure(e)}finally{busy.value=false}}
async function toggle(row:any){busy.value=true;error.value='';try{await api('portal-access','PATCH',{id:row.id,active:!row.active});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function copy(){try{await navigator.clipboard.writeText(link.value);notice.value='Lien copié.'}catch{error.value='La copie automatique est indisponible. Sélectionnez le lien pour le copier.'}}
onMounted(()=>{search();load()});onUnmounted(()=>{alive=false;searchVersion++;clearTimeout(timer)})
</script>
<template>
<section class="panel form-panel portal-invite"><h2>Inviter un client dans son espace privé</h2><p>Le client verra uniquement ses commandes, livraisons, factures émises et les documents que vous partagez explicitement.</p>
<div v-if="error" class="error-box" role="alert">{{error}}</div><div v-if="notice" class="success-box" role="status">{{notice}}</div>
<div class="mode-buttons" role="group" aria-label="Type de client"><button type="button" :class="mode==='existing'?'primary':'secondary'" :aria-pressed="mode==='existing'" @click="changeMode('existing')">Client existant</button><button type="button" :class="mode==='new'?'primary':'secondary'" :aria-pressed="mode==='new'" @click="changeMode('new')"><Plus :size="17"/>Nouveau client</button></div>
<template v-if="mode==='existing'"><label>Rechercher un client<input v-model="query" type="search" placeholder="Nom, courriel ou téléphone" @keyup.enter="search"/></label><p v-if="searching" role="status">Recherche en cours…</p><div class="customer-results" aria-label="Résultats clients"><button v-for="customer in customers" :key="customer.id" class="customer-result" :aria-pressed="partner===customer.id" @click="select(customer)"><strong>{{customer.name}}</strong><span>{{customer.email||'Courriel à compléter'}}<template v-if="customer.phone"> · {{customer.phone}}</template></span></button><p v-if="customerCount>customers.length">{{customers.length}} premiers résultats sur {{customerCount}}. Affinez votre recherche.</p><p v-if="!searching&&!customers.length">Aucun client trouvé. Vous pouvez créer un nouveau client.</p></div><small v-if="fields.partner" class="field-error" role="alert">{{fields.partner}}</small><p v-if="partner">Client sélectionné : <strong>{{name}}</strong></p></template>
<form class="form-grid" novalidate @submit.prevent="invite">
<template v-if="mode==='new'"><label>Nom / raison sociale du client<input v-model="name" maxlength="150" autocomplete="organization" :aria-invalid="!!fields.name" :aria-describedby="fields.name?'portal-name-error':undefined"/><small v-if="fields.name" id="portal-name-error" class="field-error" role="alert">{{fields.name}}</small></label><label>Nom du contact (facultatif)<input v-model="contact" maxlength="150" autocomplete="name"/><small v-if="fields.contact_name" class="field-error" role="alert">{{fields.contact_name}}</small></label></template>
<label>Courriel du client<input v-model="email" type="email" autocomplete="email" :aria-invalid="!!fields.email" :aria-describedby="fields.email?'portal-email-error':undefined"/><small v-if="fields.email" id="portal-email-error" class="field-error" role="alert">{{fields.email}}</small><small v-else-if="mode==='existing'">Le courriel corrigé sera enregistré sur la fiche client.</small></label><label v-if="mode==='new'">Téléphone (facultatif)<input v-model="phone" type="tel" maxlength="40" autocomplete="tel"/><small v-if="fields.phone" class="field-error" role="alert">{{fields.phone}}</small></label>
<button class="primary" :disabled="busy"><Plus :size="17"/>{{busy?'Traitement en cours…':mode==='new'?'Créer et inviter le client':'Créer l’invitation client'}}</button></form>
<button v-if="duplicate" class="secondary use-existing" @click="select(duplicate)">Utiliser {{duplicate.name}}</button>
<div v-if="link" class="invitation-link"><span>{{link}}</span><button class="secondary" @click="copy"><Copy :size="15"/>Copier</button></div></section>
<section class="panel"><header class="panel-heading"><h2>Invitations en attente et historique</h2></header><div v-if="!invitations.length" class="empty-state">Aucune invitation client créée.</div><div v-else class="invite-list"><article v-for="row in invitations" :key="row.id" class="invite-row"><div><strong>{{row.customer}}</strong><small>{{row.email}}</small><span class="status">{{statuses[row.status]}}</span><small>Expiration : {{new Date(row.expires_at).toLocaleString('fr-FR')}}</small></div><div class="invite-actions"><button v-if="['pending','expired'].includes(row.status)" class="secondary" :disabled="busy" @click="action(row,'resend')">Renvoyer l’invitation</button><button v-if="row.status==='pending'" class="text-btn" :disabled="busy" @click="action(row,'cancel')">Annuler l’invitation</button></div></article></div><footer class="table-pagination"><span>{{invCount}} invitation(s)</span><div><button class="icon-btn" :disabled="invPage===1" aria-label="Invitations précédentes" @click="invPage--;load()"><ChevronLeft :size="18"/></button><b>{{invPage}}</b><button class="icon-btn" :disabled="invPage*25>=invCount" aria-label="Invitations suivantes" @click="invPage++;load()"><ChevronRight :size="18"/></button></div></footer></section>
<section class="panel"><header class="panel-heading"><h2>Clients ayant accès au portail</h2></header><div v-if="!rows.length" class="empty-state">Aucun accès accepté. Les invitations créées sont suivies dans la section ci-dessus.</div><div v-else class="invite-list"><article v-for="row in rows" :key="row.id" class="invite-row"><div><strong>{{row.customer}}</strong><small>{{row.name}} · {{row.email}}</small><span class="status">{{row.active?'Actif':'Révoqué'}}</span></div><button class="secondary" :disabled="busy" @click="toggle(row)">{{row.active?'Révoquer':'Réactiver'}}</button></article></div><footer class="table-pagination"><span>{{count}} accès</span><div><button class="icon-btn" :disabled="page===1" aria-label="Page précédente" @click="page--;load()"><ChevronLeft :size="18"/></button><b>{{page}}</b><button class="icon-btn" :disabled="page*25>=count" aria-label="Page suivante" @click="page++;load()"><ChevronRight :size="18"/></button></div></footer></section>
</template>
<style scoped>
.mode-buttons{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}.portal-invite label{display:grid;gap:7px}.customer-results{display:grid;gap:8px;margin:12px 0;max-height:280px;overflow-y:auto}.customer-result{display:grid;text-align:left;gap:5px;padding:12px;border:1px solid #dce7df;border-radius:8px;background:white;color:inherit;min-height:54px}.customer-result[aria-pressed=true]{border:2px solid #176d57;background:#f1faf5}.customer-result span{font-size:14px;overflow-wrap:anywhere}.field-error{color:#a32b2b}.portal-invite form{margin-top:18px}.use-existing{margin-top:12px}.invite-list{padding:0 20px}.invite-row{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:20px 0;border-bottom:1px solid #e2eae4}.invite-row>div:first-child{display:grid;gap:7px;min-width:0;overflow-wrap:anywhere}.invite-actions{display:flex;flex-wrap:wrap;gap:10px}.invitation-link span{overflow-wrap:anywhere;min-width:0}.portal-invite button,.invite-row button{min-height:44px}.portal-invite input{font-size:16px;min-width:0}@media(max-width:600px){.invite-row{align-items:flex-start;flex-direction:column}.invite-actions{width:100%}.mode-buttons button{flex:1}.form-grid{grid-template-columns:1fr}.invitation-link{flex-wrap:wrap}.portal-invite .primary{white-space:normal}}
</style>
