<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {Plus,Copy,ChevronLeft,ChevronRight} from 'lucide-vue-next'
import {api} from './api'
const customers=ref<any[]>([]),rows=ref<any[]>([]),query=ref(''),page=ref(1),count=ref(0),email=ref(''),partner=ref(''),link=ref(''),busy=ref(false),error=ref(''),notice=ref('')
async function search(){try{customers.value=(await api('partners?page_size=100&q='+encodeURIComponent(query.value))).results.filter((x:any)=>['customer','both'].includes(x.kind))}catch(e:any){error.value=e.message}}
async function load(){try{const result=await api('portal-access?page='+page.value);rows.value=result.results;count.value=result.count}catch(e:any){error.value=e.message}}
async function invite(){busy.value=true;error.value='';link.value='';try{const result=await api('portal-access','POST',{email:email.value,partner:partner.value});link.value=result.link;notice.value=result.sent?'Invitation envoyée au client.':'Invitation créée. Transmettez ce lien au client.';await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function toggle(row:any){error.value='';try{await api('portal-access','PATCH',{id:row.id,active:!row.active});await load()}catch(e:any){error.value=e.message}}
async function copy(){try{await navigator.clipboard.writeText(link.value);notice.value='Lien copié.'}catch{error.value='La copie automatique est indisponible. Sélectionnez le lien pour le copier.'}}
onMounted(()=>{search();load()})
</script>
<template><section class="panel form-panel"><h2>Inviter un client dans son espace privé</h2><p>Le client verra uniquement ses commandes, livraisons, factures émises et les documents que vous partagez explicitement.</p><div v-if="error" class="error-box" role="alert">{{error}}</div><div v-if="notice" class="success-box" role="status">{{notice}}</div><div class="form-row"><label>Rechercher un client<input v-model="query" type="search" placeholder="Nom du client" @keyup.enter="search"/></label><button class="secondary" @click="search">Rechercher</button></div><form class="form-grid" @submit.prevent="invite"><label>Client<select v-model="partner" required><option value="">Sélectionner un client</option><option v-for="customer in customers" :value="customer.id">{{customer.name}}</option></select></label><label>Courriel du client<input v-model="email" type="email" required/></label><button class="primary" :disabled="busy"><Plus :size="17"/>Créer l’invitation client</button></form><div v-if="link" class="invitation-link"><span>{{link}}</span><button class="secondary" @click="copy"><Copy :size="15"/>Copier</button></div></section><section class="panel"><header class="panel-heading"><h2>Accès clients</h2></header><div v-if="!rows.length" class="empty-state">Les accès apparaissent après acceptation des invitations.</div><div v-else class="table-wrap"><table><thead><tr><th>CONTACT</th><th>CLIENT</th><th>ACCÈS</th><th></th></tr></thead><tbody><tr v-for="row in rows"><td>{{row.name}}<small>{{row.email}}</small></td><td>{{row.customer}}</td><td>{{row.active?'Actif':'Révoqué'}}</td><td><button class="text-btn" @click="toggle(row)">{{row.active?'Révoquer':'Réactiver'}}</button></td></tr></tbody></table></div><footer class="table-pagination"><span>{{count}} accès</span><div><button class="icon-btn" :disabled="page===1" aria-label="Page précédente" @click="page--;load()"><ChevronLeft :size="18"/></button><b>{{page}}</b><button class="icon-btn" :disabled="page*25>=count" aria-label="Page suivante" @click="page++;load()"><ChevronRight :size="18"/></button></div></footer></section></template>
