<script setup lang="ts">
import {ref,onMounted} from 'vue'
const token=location.hash.slice(1),quote=ref<any>(null),error=ref(''),busy=ref(false),decision=ref('')
history.replaceState({},'','/devis')
async function request(action:string,data:any){const r=await fetch('/api/v2/public/quotes/'+action,{method:'POST',credentials:'omit',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...data})});const result=await r.json();if(!r.ok)throw new Error(result.detail||'Cette décision ne peut plus être enregistrée.');return result}
onMounted(async()=>{try{quote.value=await request('preview',{})}catch(e:any){error.value=e.message}})
async function respond(){busy.value=true;error.value='';try{const result=await request('respond',{decision:decision.value});quote.value.state=result.state;decision.value=''}catch(e:any){error.value=e.message}finally{busy.value=false}}
</script>
<template><main class="public-quote"><header><strong>TransitFlow</strong><h1>{{quote?.company||'Votre devis'}}</h1></header><p v-if="error" role="alert">{{error}}</p><template v-if="quote"><h2>Devis {{quote.number}}</h2><p>{{quote.customer}} · Valable jusqu’au {{quote.valid_until}}</p><p>{{quote.origin}} → {{quote.destination}}</p><ul><li v-for="(line,index) in quote.lines" :key="index"><strong>{{line.description}}</strong><p>{{line.quantity}} × {{line.price}} {{quote.currency}} · Taxe {{line.tax_rate}} %</p></li></ul><dl><dt>Total HT</dt><dd>{{quote.subtotal}} {{quote.currency}}</dd><dt>Taxes</dt><dd>{{quote.tax}} {{quote.currency}}</dd><dt>Total TTC</dt><dd><strong>{{quote.total}} {{quote.currency}}</strong></dd></dl><template v-if="quote.state==='sent'"><p>Indiquez votre décision. Elle sera transmise à {{quote.company}}.</p><div class="quote-actions"><button class="primary" @click="decision='accept'">Accepter le devis</button><button class="secondary" @click="decision='refuse'">Refuser le devis</button></div><form v-if="decision" @submit.prevent="respond"><p>{{decision==='accept'?'Confirmez-vous l’acceptation de ce devis ?':'Confirmez-vous le refus de ce devis ?'}}</p><button class="primary" :disabled="busy">Confirmer {{decision==='accept'?'l’acceptation':'le refus'}}</button><button class="secondary" type="button" :disabled="busy" @click="decision=''">Annuler</button></form></template><p v-else role="status">{{quote.state==='accepted'?'Ce devis a été accepté.':quote.state==='refused'?'Ce devis a été refusé.':'Ce devis n’est plus disponible pour une réponse.'}}</p></template><p v-else-if="!error" role="status">Chargement du devis…</p><footer>Ce lien est personnel. Conservez-le de manière confidentielle.</footer></main></template>
<style scoped>.public-quote{max-width:720px;margin:24px auto;padding:24px;background:white;border-radius:12px;overflow-wrap:anywhere}.public-quote header{border-bottom:1px solid #dce5ef}.public-quote ul{padding-left:20px}.public-quote li{padding:12px 0}.public-quote dl{display:grid;grid-template-columns:1fr 1fr;gap:12px}.public-quote dd{margin:0;text-align:right}.quote-actions,.public-quote form{display:flex;flex-wrap:wrap;gap:12px}.public-quote form p{width:100%}.public-quote button{min-height:44px}.public-quote footer{margin-top:24px;font-size:13px}@media(max-width:390px){.public-quote{margin:8px;padding:16px}.quote-actions button{width:100%}}</style>
