<script setup lang="ts">
import {ref,onMounted,onUnmounted,watch} from 'vue'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import {trackingLabel} from './gps'
const props=defineProps<{missions:any[],tiles:any,selected?:string,trace?:any[]}>(),emit=defineEmits(['mission'])
const element=ref<HTMLElement>(),markers=new Map<string,L.CircleMarker>();let departure:L.CircleMarker|undefined;let map:L.Map,polyline:L.Polyline|undefined,first=true,observer:ResizeObserver
function popup(m:any){const container=document.createElement('div');for(const text of [m.plate,m.driver,'Mission '+m.reference,m.origin+' → '+m.destination,trackingLabel[m.state],m.last?.speed!=null?'Vitesse : '+(m.last.speed*3.6).toFixed(1)+' km/h':'',m.last?.accuracy!=null?'Précision : '+Math.round(m.last.accuracy)+' m':'',m.last?'Dernière position : '+new Date(m.last.timestamp).toLocaleString('fr-FR'):'']){const p=document.createElement('p');p.textContent=text;container.append(p)}const button=document.createElement('button');button.type='button';button.className='text-btn';button.textContent='Voir la mission';button.onclick=()=>emit('mission',m.id);container.append(button);return container}
function update(){if(!map)return;const present=new Set<string>();for(const mission of props.missions){if(!mission.last)continue;present.add(mission.id);const pos:L.LatLngTuple=[Number(mission.last.latitude),Number(mission.last.longitude)];let marker=markers.get(mission.id);if(!marker){marker=L.circleMarker(pos,{radius:10,weight:3,fillOpacity:0.9}).addTo(map);markers.set(mission.id,marker)}else marker.setLatLng(pos);marker.setStyle({color:['online','capturing'].includes(mission.state)?'#087b5e':mission.state==='recent'?'#a15d00':'#ae3542'});marker.bindPopup(popup(mission))}for(const [id,marker] of markers)if(!present.has(id)){marker.remove();markers.delete(id)}if(props.trace?.length){const coords=props.trace.map(p=>[Number(p.latitude),Number(p.longitude)] as L.LatLngTuple);if(!departure)departure=L.circleMarker(coords[0],{radius:7,color:'#0963ad',fillOpacity:1}).bindPopup('Départ GPS enregistré').addTo(map);if(polyline)polyline.setLatLngs(coords);else polyline=L.polyline(coords,{color:'#0963ad',weight:4}).addTo(map);if(first){map.fitBounds(polyline.getBounds(),{padding:[25,25],maxZoom:15});first=false}}else if(first&&markers.size){map.fitBounds(L.featureGroup([...markers.values()]).getBounds(),{padding:[25,25],maxZoom:14});first=false}}
watch(()=>[props.missions,props.trace],update,{deep:true});watch(()=>props.selected,()=>{const marker=markers.get(props.selected||'');if(marker){map.setView(marker.getLatLng(),15);marker.openPopup()}})
onMounted(()=>{map=L.map(element.value!,{scrollWheelZoom:false}).setView([0,0],2);const attribution=document.createElement('span');attribution.textContent=props.tiles.attribution;try{const url=new URL(props.tiles.attribution_url);if(url.protocol==='https:'){const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent=props.tiles.attribution;attribution.replaceChildren(link)}}catch{}L.tileLayer(props.tiles.url,{attribution:attribution.outerHTML,maxZoom:19,referrerPolicy:'strict-origin-when-cross-origin'}).addTo(map);observer=new ResizeObserver(()=>map.invalidateSize());observer.observe(element.value!);update()});onUnmounted(()=>{observer?.disconnect();map?.remove()})
</script>
<template><div ref="element" class="tracking-map" aria-label="Carte Leaflet des positions GPS" data-testid="tracking-map"></div></template>
