<!-- Auteur : Jonathan Kakesa (JonathanK-N). -->
<script setup lang="ts">
import {ref,computed,onMounted,watch} from 'vue'
import {Layers3 as LayersIcon,LayoutDashboard,Truck,Route,Users,Building2,Wallet,FileText,Wrench,Package,ShoppingCart,BookOpen,CalendarDays,Settings,ShieldCheck,LogOut,Search,Plus,ChevronDown,ChevronRight,ChevronLeft,ArrowUpRight,ArrowRight,Download,Filter,MoreHorizontal,Menu,X,Bell,CheckCircle2,AlertCircle,LoaderCircle,RefreshCw,Bus,MapPin,Check,Copy,SlidersHorizontal} from 'lucide-vue-next'
import {api,organization,setOrganization,download,money} from './api'
import RecordEditor from './RecordEditor.vue'
import MissionCompletion from './MissionCompletion.vue'
const props=defineProps<{session:any}>();defineEmits(['logout'])
const navigator=window.navigator
const current=ref('dashboard'),catalog=ref<any[]>([]),dashboard=ref<any>(null),rows=ref<any[]>([]),count=ref(0),page=ref(1),query=ref(''),status=ref(''),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),mobile=ref(false)
const editor=ref(false),selected=ref<any>(null),orgId=ref(organization),org=ref<any>(props.session.organizations.find((x:any)=>x.id===organization)||props.session.organizations[0]||{})
const completing=ref<any>(null)
const team=ref<any>({members:[],invitations:[]}),invitation=ref({email:'',role:'operations'}),inviteLink=ref(''),reports=ref<any>(null),settingsForm=ref<any>({}),searchTimer=ref<any>(null)
const nav=[{label:'PILOTAGE',items:[['dashboard','Vue d’ensemble',LayoutDashboard]]},{label:'EXPLOITATION',items:[['missions','Missions',Route],['orders','Commandes',Package],['vehicles','Flotte',Truck],['employees','Personnel',Users],['partners','Clients & fournisseurs',Building2],['routes','Lignes & circuits',Bus],['bookings','Réservations',CalendarDays]]},{label:'GESTION',items:[['maintenance','Entretien',Wrench],['stock','Stocks & pièces',Package],['movements','Mouvements',ArrowRight],['purchases','Achats',ShoppingCart],['invoices','Facturation',FileText],['payments','Règlements',Wallet],['expenses','Dépenses',Wallet],['journal','Comptabilité',BookOpen],['accounts','Plan de comptes',BookOpen],['reports','Rapports',LayoutDashboard],['documents','Documents',FileText]]},{label:'ENTREPRISE',items:[['team','Équipe & accès',ShieldCheck],['audit','Journal d’audit',ShieldCheck],['settings','Paramètres',Settings]]}]
const actionLabels:Record<string,string>={confirm:'Confirmer',cancel:'Annuler',start:'Démarrer',complete:'Terminer',issue:'Émettre',post:'Comptabiliser',approve:'Valider',board:'Embarquer',order:'Commander',receive:'Réceptionner'}
const columns:Record<string,string[]>={vehicles:['plate','name','kind','mileage','status'],employees:['name','job','phone','license_expiry','active'],partners:['name','kind','phone','email'],orders:['reference','customer','origin','destination','planned_date','status'],missions:['reference','vehicle','origin','destination','departure','status'],routes:['name','origin','destination','fare','active'],bookings:['passenger','mission','seats','amount','status'],maintenance:['title','vehicle','due_date','cost','status'],invoices:['number','customer','due_date','total','paid','status'],payments:['reference','invoice','date','amount','method'],expenses:['title','category','date','amount','status'],journal:['reference','date','description','status'],accounts:['code','name'],stock:['code','name','quantity','minimum','unit_cost'],movements:['item','quantity','reason','created_at'],purchases:['reference','supplier','date','total','status'],documents:['title','category','expiry'],audit:['action','resource','object_id','created_at']}
const schema=computed(()=>catalog.value.find(x=>x.key===current.value))
const visibleColumns=computed(()=>columns[current.value]||[])
const title=computed(()=>schema.value?.label||({dashboard:'Vue d’ensemble',team:'Équipe & accès',settings:'Paramètres de l’entreprise',reports:'Rapports & rentabilité'} as any)[current.value])
const admin=computed(()=>['owner','admin'].includes(org.value.role))
const date=computed(()=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:org.value.timezone||'UTC'}).format(new Date()))
function permitted(key:string){if(key==='dashboard')return true;if(['team','settings'].includes(key))return admin.value;if(key==='reports')return catalog.value.some(x=>x.key==='journal');return catalog.value.some(x=>x.key===key)}
function label(field:string){return schema.value?.fields.find((f:any)=>f.name===field)?.label||({created_at:'Date',action:'Action',resource:'Module',object_id:'Référence'} as any)[field]||field}
function display(row:any,field:string){
 if(row.relations?.[field])return row.relations[field]
 const value=row[field];if(value===null||value===undefined||value==='')return '—'
 if(typeof value==='boolean')return value?'Oui':'Non'
 const f=schema.value?.fields.find((x:any)=>x.name===field)
 if(f?.options?.length)return f.options.find((x:any)=>x.value===value)?.label||value
 if(['amount','total','paid','cost','fare','unit_cost'].includes(field))return money(value,org.value.currency)
 if(['date','due_date','planned_date','expiry','license_expiry'].includes(field))return new Date(value+'T12:00:00').toLocaleDateString('fr-FR')
 if(['departure','arrival','created_at'].includes(field))return new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short',timeZone:org.value.timezone}).format(new Date(value))
 return value
}
function navigate(key:string){current.value=key;page.value=1;query.value='';status.value='';mobile.value=false;editor.value=false;error.value='';history.replaceState({},'','/app#'+key);load()}
async function bootstrap(){
 loading.value=true;error.value=''
 try{catalog.value=(await api('catalog')).resources;await load()}catch(e:any){error.value=e.message}finally{loading.value=false}
}
async function load(){
 loading.value=true;error.value=''
 try{
  if(current.value==='dashboard')dashboard.value=await api('dashboard')
  else if(current.value==='team')team.value=await api('team')
  else if(current.value==='reports')reports.value=await api('reports')
  else if(current.value==='settings')settingsForm.value=await api('organization')
  else{const r=await api(current.value+'?page='+page.value+'&q='+encodeURIComponent(query.value)+'&status='+status.value);rows.value=r.results;count.value=r.count}
 }catch(e:any){error.value=e.message}finally{loading.value=false}
}
async function switchOrg(){setOrganization(orgId.value);org.value=props.session.organizations.find((x:any)=>x.id===orgId.value);current.value='dashboard';rows.value=[];dashboard.value=null;editor.value=false;await bootstrap()}
function open(record:any=null){selected.value=record;editor.value=true}
async function saved(){editor.value=false;notify('Enregistrement sauvegardé.');await load()}
function notify(text:string){notice.value=text;setTimeout(()=>notice.value='',5000)}
async function action(row:any,key:string){
 if(current.value==='missions'&&key==='complete'){completing.value=row;return}
 if(!window.confirm(`${actionLabels[key]} « ${row.label} » ?`))return
 busy.value=true;error.value=''
 try{await api(`${current.value}/${row.id}/actions/${key}`,'POST');notify('Opération effectuée.');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}
}
async function exportCsv(){try{await download(current.value+'/export',`transitflow-${current.value}.csv`)}catch(e:any){error.value=e.message}}
async function invite(){busy.value=true;error.value='';try{const r=await api('team','POST',invitation.value);inviteLink.value=r.link;notify(r.sent?'Invitation envoyée.':'Invitation créée. Copiez le lien pour la transmettre.');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function memberChange(member:any){error.value='';try{await api('team','PATCH',{id:member.id,role:member.role,active:member.active});notify('Accès mis à jour.')}catch(e:any){error.value=e.message;await load()}}
async function saveSettings(){busy.value=true;error.value='';try{const r=await api('organization','PATCH',settingsForm.value);Object.assign(org.value,r);notify('Paramètres enregistrés.')}catch(e:any){error.value=e.message}finally{busy.value=false}}
function search(){clearTimeout(searchTimer.value);searchTimer.value=setTimeout(()=>{page.value=1;load()},300)}
onMounted(()=>{const route=location.hash.slice(1);if(route&&[...Object.keys(columns),'reports','team','settings'].includes(route))current.value=route;bootstrap()})
</script>
<template>
 <div class="workspace">
  <div v-if="mobile" class="sidebar-overlay" @click="mobile=false"></div>
  <aside class="sidebar" :class="{shown:mobile}"><a class="brand" href="/app" @click.prevent="navigate('dashboard')"><span class="brand-mark">T</span>Transit<span>Flow</span><small>ERP</small></a>
   <div class="company-select"><span class="company-avatar">{{org.name?.slice(0,2).toUpperCase()}}</span><div><small>VOTRE ENTREPRISE</small><select v-model="orgId" @change="switchOrg" aria-label="Entreprise active"><option v-for="o in session.organizations" :value="o.id">{{o.name}}</option></select></div></div>
   <nav class="workspace-nav"><div v-for="group in nav" :key="group.label" class="nav-group"><small v-if="group.items.some(x=>permitted(String(x[0])))">{{group.label}}</small><template v-for="item in group.items" :key="String(item[0])"><button v-if="permitted(String(item[0]))" :class="{active:current===item[0]}" @click="navigate(String(item[0]))"><component :is="item[2]" :size="18"/><span>{{item[1]}}</span><span v-if="item[0]==='missions'&&dashboard?.active" class="nav-count">{{dashboard.active}}</span></button></template></div></nav>
   <div class="sidebar-bottom"><div class="space-secure"><ShieldCheck :size="16"/><span>Espace entreprise privé</span></div><button class="user-card" @click="$emit('logout')" title="Se déconnecter"><span class="user-avatar">{{session.user.name?.slice(0,1)}}</span><span><b>{{session.user.name}}</b><small>{{({owner:'Propriétaire',admin:'Administrateur',operations:'Exploitation',finance:'Finance',workshop:'Atelier',driver:'Chauffeur',viewer:'Lecture seule'} as any)[org.role]}}</small></span><LogOut :size="16"/></button></div>
  </aside>
  <div class="workspace-main">
   <header class="topbar"><button class="icon-btn mobile-only" aria-label="Menu" @click="mobile=true"><Menu/></button><div class="breadcrumb">Espace entreprise <ChevronRight :size="14"/><b>{{title}}</b></div><div class="topbar-right"><span class="region"><span class="online-dot"></span>{{org.country}} <i> / </i>{{org.currency}}</span><button class="icon-btn" aria-label="Actualiser" @click="load"><RefreshCw :size="18"/></button><button class="icon-btn" aria-label="Voir les alertes" @click="navigate('dashboard')"><Bell :size="18"/><span v-if="dashboard?.alerts?.length" class="notification-dot"></span></button><span class="user-avatar small-avatar">{{session.user.name?.slice(0,1)}}</span></div></header>
   <main class="workspace-content">
    <div v-if="notice" class="toast" role="status"><CheckCircle2 :size="18"/>{{notice}}</div>
    <div class="page-heading"><div><div class="eyebrow">{{current==='dashboard'?'VOTRE ENTREPRISE, EN MOUVEMENT':'ESPACE DE GESTION'}}</div><h1>{{title}}<span v-if="schema" class="count-label">{{count}}</span></h1><p>{{current==='dashboard'?`Bonjour ${session.user.name.split(' ')[0]}, voici le point sur votre activité.`:current==='reports'?'Des chiffres reliés à vos opérations, pour décider avec précision.':current==='settings'?'Adaptez votre espace à votre organisation.':current==='team'?'Invitez vos collaborateurs et attribuez les bons accès.':'Retrouvez, organisez et suivez les informations de votre entreprise.'}}</p></div><div class="page-actions"><span v-if="current==='dashboard'" class="date-chip"><CalendarDays :size="16"/>{{date}}</span><template v-if="schema"><button v-if="current!=='documents'" class="secondary" @click="exportCsv"><Download :size="16"/>Exporter</button><button v-if="schema.writable" class="primary" @click="open()"><Plus :size="18"/>Nouveau</button></template></div></div>
    <div v-if="error" class="error-box" role="alert"><AlertCircle :size="18"/>{{error}}<button class="text-btn" @click="load">Réessayer</button></div>
    <div v-if="loading" class="loading-panel"><LoaderCircle class="spin"/>Chargement des données…</div>
    <template v-else-if="current==='dashboard'&&dashboard">
     <div class="stat-grid"><article class="stat-card"><span><Truck :size="18"/>Véhicules en flotte</span><strong>{{dashboard.fleet}}</strong><small>Votre parc de véhicules</small><i class="stat-decoration"><Truck :size="44" stroke-width="1"/></i></article><article class="stat-card"><span><Route :size="18"/>Missions en cours</span><strong>{{dashboard.active}}<i class="live-tag">En route</i></strong><small>Opérations actuellement actives</small></article><article class="stat-card"><span><CalendarDays :size="18"/>Missions planifiées</span><strong>{{dashboard.planned}}</strong><small>Les prochains départs</small></article><article v-if="dashboard.receivable!==null" class="stat-card highlight"><span><Wallet :size="18"/>Solde clients</span><strong class="money-stat">{{money(dashboard.receivable,org.currency)}}</strong><small>Factures émises, après règlements et avoirs</small></article></div>
     <div class="dashboard-grid"><section class="panel mission-panel"><header class="panel-heading"><div><h2>Vos missions</h2><p>Les départs et opérations de votre entreprise</p></div><button v-if="permitted('missions')" class="text-btn" @click="navigate('missions')">Tout voir <ArrowUpRight :size="16"/></button></header><div v-if="!dashboard.missions.length" class="empty-state"><span class="empty-icon"><Route :size="32"/></span><h3>Votre prochaine mission commence ici.</h3><p>Ajoutez votre flotte et vos chauffeurs, puis préparez votre premier départ.</p><button v-if="permitted('vehicles')" class="primary" @click="navigate('vehicles')">Configurer ma flotte <ArrowRight :size="16"/></button></div><div v-else class="table-wrap"><table><thead><tr><th>MISSION</th><th>ITINÉRAIRE</th><th>VÉHICULE</th><th>STATUT</th></tr></thead><tbody><tr v-for="mission in dashboard.missions" @click="navigate('missions')"><td><strong>{{mission.reference}}</strong><small>{{new Date(mission.departure).toLocaleDateString('fr-FR')}}</small></td><td><span class="route-label">{{mission.origin}}<ArrowRight :size="13"/>{{mission.destination}}</span></td><td>{{mission.relations.vehicle}}</td><td><span class="status" :class="mission.status">{{({planned:'Planifiée',active:'En cours',completed:'Terminée',cancelled:'Annulée'} as any)[mission.status]}}</span></td></tr></tbody></table></div></section>
      <section class="panel alerts-panel"><header class="panel-heading"><div><h2>À surveiller</h2><p>Anticipez les prochaines échéances</p></div><span class="alert-count">{{dashboard.alerts.length}}</span></header><div v-if="!dashboard.alerts.length" class="all-clear"><ShieldCheck :size="42" stroke-width="1.3"/><h3>Aucune alerte pour le moment</h3><p>Vos échéances et seuils de stock apparaîtront ici.</p></div><button v-for="alert in dashboard.alerts" class="alert-item" @click="navigate(alert.resource)"><span class="alert-symbol"><AlertCircle :size="18"/></span><div><b>{{alert.label}}</b><small>{{alert.date?new Date(alert.date+'T12:00').toLocaleDateString('fr-FR'):'Seuil minimum atteint'}}</small></div><ChevronRight :size="16"/></button></section>
     </div><div class="dashboard-bottom"><section class="onboarding-card"><div class="onboarding-icon"><LayersIcon/></div><div><span class="eyebrow">UN ESPACE QUI VOUS RESSEMBLE</span><h2>Les bons outils, pour votre métier.</h2><p>Marchandises, voyageurs ou transport spécialisé : configurez vos activités et votre équipe.</p></div><button v-if="admin" class="secondary" @click="navigate('settings')">Personnaliser <ArrowUpRight :size="16"/></button></section><section class="panel quick-actions"><h2>Accès rapides</h2><div><button v-if="permitted('orders')" @click="navigate('orders')"><Package :size="21"/>Commandes<ArrowUpRight :size="15"/></button><button v-if="permitted('invoices')" @click="navigate('invoices')"><FileText :size="21"/>Facturation<ArrowUpRight :size="15"/></button><button v-if="permitted('maintenance')" @click="navigate('maintenance')"><Wrench :size="21"/>Entretien<ArrowUpRight :size="15"/></button></div></section></div>
    </template>
    <template v-else-if="schema">
     <section class="panel resource-panel"><div class="table-toolbar"><div class="search-box"><Search :size="18"/><input v-model="query" type="search" :placeholder="'Rechercher dans '+schema.label.toLowerCase()+'…'" aria-label="Rechercher" @input="search"/></div><div class="filter-controls"><Filter :size="16"/><select v-if="schema.fields.some((f:any)=>f.name==='status')" v-model="status" aria-label="Filtrer par statut" @change="page=1;load()"><option value="">Tous les statuts</option><option v-for="o in schema.fields.find((f:any)=>f.name==='status').options" :value="o.value">{{o.label}}</option></select><span>{{count}} résultat{{count>1?'s':''}}</span></div></div>
      <div v-if="!rows.length" class="empty-state"><span class="empty-icon"><FileText :size="30"/></span><h3>{{query?'Aucun résultat.':'Tout commence par une première fiche.'}}</h3><p>{{query?'Essayez un autre terme ou modifiez vos filtres.':'Ajoutez vos données pour retrouver ici une vue claire de votre activité.'}}</p><button v-if="schema.writable&&!query" class="primary" @click="open()"><Plus :size="16"/>Créer un enregistrement</button></div>
      <div v-else class="table-wrap"><table><thead><tr><th v-for="field in visibleColumns">{{label(field)}}</th><th class="right">ACTIONS</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="(field,i) in visibleColumns"><button v-if="i===0" class="record-link" @click="open(row)">{{display(row,field)}}</button><span v-else-if="field==='status'" class="status" :class="row.status">{{display(row,field)}}</span><span v-else>{{display(row,field)}}</span></td><td><div class="row-actions"><button v-if="current==='documents'" class="icon-btn" aria-label="Télécharger" @click="download('documents/'+row.id+'/download',row.title)"><Download :size="15"/></button><template v-if="schema.writable||schema.canAct"><button v-for="a in (schema.actions[row.status]||[]).filter((a:string)=>schema.writable||a!=='cancel')" class="action-button" :disabled="busy" @click="action(row,a)">{{actionLabels[a]}}</button></template><button class="icon-btn" aria-label="Ouvrir la fiche" @click="open(row)"><ChevronRight :size="17"/></button></div></td></tr></tbody></table></div>
      <div class="table-pagination"><span>{{count?((page-1)*25+1):0}}–{{Math.min(page*25,count)}} sur {{count}}</span><div><button class="icon-btn" aria-label="Page précédente" :disabled="page===1" @click="page--;load()"><ChevronLeft :size="18"/></button><b>{{page}}</b><button class="icon-btn" aria-label="Page suivante" :disabled="page*25>=count" @click="page++;load()"><ChevronRight :size="18"/></button></div></div>
     </section>
    </template>
    <template v-else-if="current==='team'"><section class="panel form-panel"><h2>Inviter un collaborateur</h2><form class="invite-form" @submit.prevent="invite"><label>Adresse courriel<input v-model="invitation.email" type="email" required placeholder="collaborateur@entreprise.com"/></label><label>Rôle<select v-model="invitation.role"><option value="admin">Administrateur</option><option value="operations">Exploitation</option><option value="finance">Finance</option><option value="workshop">Atelier</option><option value="driver">Chauffeur</option><option value="viewer">Lecture seule</option></select></label><button class="primary" :disabled="busy"><Plus :size="17"/>Inviter</button></form><div v-if="inviteLink" class="invitation-link"><span>{{inviteLink}}</span><button class="secondary small" @click="navigator.clipboard.writeText(inviteLink);notify('Lien copié.')"><Copy :size="14"/>Copier</button></div></section><section class="panel"><header class="panel-heading"><h2>Membres de l’entreprise</h2></header><div class="table-wrap"><table><thead><tr><th>COLLABORATEUR</th><th>RÔLE</th><th>ACCÈS ACTIF</th></tr></thead><tbody><tr v-for="member in team.members"><td><strong>{{member.name}}</strong><small>{{member.email}}</small></td><td><select v-model="member.role" aria-label="Rôle du collaborateur" @change="memberChange(member)"><option value="owner">Propriétaire</option><option value="admin">Administrateur</option><option value="operations">Exploitation</option><option value="finance">Finance</option><option value="workshop">Atelier</option><option value="driver">Chauffeur</option><option value="viewer">Lecture seule</option></select></td><td><input v-model="member.active" type="checkbox" aria-label="Accès actif" @change="memberChange(member)"/></td></tr></tbody></table></div></section></template>
    <template v-else-if="current==='settings'"><section class="panel form-panel settings-panel"><h2>Identité de l’entreprise</h2><form @submit.prevent="saveSettings"><div class="form-grid"><label>Nom de l’entreprise<input v-model="settingsForm.name" required/></label><label>Courriel<input v-model="settingsForm.email" type="email"/></label><label>Téléphone<input v-model="settingsForm.phone"/></label><label>Devise<select v-model="settingsForm.currency"><option v-for="c in ['GNF','XAF','XOF','CDF','EUR','USD','MGA','MRU','DJF']">{{c}}</option></select></label><label>Fuseau horaire<input v-model="settingsForm.timezone" required/></label><label>Registre de commerce<input v-model="settingsForm.registration"/></label><label>Identifiant fiscal<input v-model="settingsForm.tax_number"/></label><label class="span-2">Adresse<textarea v-model="settingsForm.address" rows="3"></textarea></label><div class="span-2"><h3>Vos activités</h3><div class="activity-checkboxes"><label v-for="a in [['freight','Marchandises'],['passengers','Voyageurs'],['shuttle','Navettes / scolaire'],['fuel','Carburants'],['cold','Frigorifique'],['bulk','Vrac']]" class="checkbox-label"><input v-model="settingsForm.activities" type="checkbox" :value="a[0]"/>{{a[1]}}</label></div></div></div><button class="primary" :disabled="busy"><Check :size="17"/>Enregistrer les paramètres</button></form></section></template>
    <template v-else-if="current==='reports'&&reports"><section class="panel"><header class="panel-heading"><div><h2>Balance comptable</h2><p>Écritures comptabilisées · {{reports.currency}}</p></div></header><div class="table-wrap"><table><thead><tr><th>COMPTE</th><th>LIBELLÉ</th><th>DÉBIT</th><th>CRÉDIT</th><th>SOLDE</th></tr></thead><tbody><tr v-for="row in reports.trial_balance"><td>{{row.code}}</td><td>{{row.name}}</td><td>{{money(row.debit,org.currency)}}</td><td>{{money(row.credit,org.currency)}}</td><td><strong>{{money(row.balance,org.currency)}}</strong></td></tr></tbody></table></div></section><section class="panel"><header class="panel-heading"><div><h2>Rentabilité des commandes</h2><p>{{reports.note}}</p></div></header><div class="table-wrap"><table><thead><tr><th>COMMANDE</th><th>CLIENT</th><th>PRIX CONVENU</th><th>DÉPENSES</th><th>MARGE</th></tr></thead><tbody><tr v-for="row in reports.profitability"><td>{{row.reference}}</td><td>{{row.customer}}</td><td>{{money(row.revenue,org.currency)}}</td><td>{{money(row.cost,org.currency)}}</td><td>{{money(row.margin,org.currency)}}</td></tr></tbody></table></div></section></template>
    <footer class="workspace-footer"><span>TransitFlow · Votre entreprise, unifiée.</span><span><ShieldCheck :size="13"/>{{org.name}}</span></footer>
   </main>
  </div>
  <RecordEditor v-if="editor&&schema" :key="current+(selected?.id||'new')" :schema="schema" :record="selected" :currency="org.currency" @close="editor=false" @saved="saved"/>
  <MissionCompletion v-if="completing" :mission="completing" @close="completing=null" @saved="completing=null;saved()"/>
 </div>
</template>
