# Generated by Django 5.2.17 on 2026-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon entreprise de transport', max_length=150)),
                ('courriel', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='QC', max_length=50)),
                ('code_postal', models.CharField(blank=True, default='', max_length=10)),
                ('neq', models.CharField(blank=True, default='', max_length=20, verbose_name='NEQ')),
                ('module_entretien', models.BooleanField(default=True)),
                ('module_suivi', models.BooleanField(default=True)),
                ('module_paie', models.BooleanField(default=True)),
                ('portail_trajets', models.BooleanField(default=True)),
                ('portail_incidents', models.BooleanField(default=True)),
                ('portail_vehicule', models.BooleanField(default=True)),
                ('portail_paie', models.BooleanField(default=False)),
                ('portail_profil', models.BooleanField(default=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
            },
        ),
    ]
